'use client';
import { useMemo, useState } from 'react';
import ForecastOverlayChart from '@/components/chart/forecast-overlay-chart';
import Badge from '@/components/ui/badge';

export default function ModelComparison({ detail, performance, champions, runs }: { detail: Record<string, unknown>[]; performance: Record<string, unknown>[]; champions: Record<string, unknown>[]; runs: Record<string, unknown>[] }) {
  const [runId, setRunId] = useState(String(runs[0]?.forecast_run_id ?? runs[0]?.run_id ?? ''));
  const [itemId, setItemId] = useState('ALL');
  const [models, setModels] = useState<string[]>([]);
  const items = Array.from(new Set(detail.map((r) => String(r.item_id))));
  const selected = useMemo(() => detail.filter((r) => (!runId || String(r.run_id) === runId) && (itemId === 'ALL' || String(r.item_id) === itemId) && (models.length === 0 || models.includes(String(r.model_id)))), [detail,itemId,models,runId]);
  const modelIds = Array.from(new Set(selected.map((r) => String(r.model_id))));
  const toggle = (id: string) => setModels((current) => current.includes(id) ? current.filter((v) => v !== id) : [...current, id]);
  const exportCsv = () => { const rows = [['run_id','model_id','item_id','period','actual_qty','p50','p80','p90'], ...selected.map((r) => ['run_id','model_id','item_id','period','actual_qty','p50','p80','p90'].map((k) => String(r[k] ?? '')))].map((r) => r.join(',')).join('\n'); const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows],{type:'text/csv'}));a.download='model-comparison.csv';a.click(); };
  return <><div className="button-row comparison-filters"><select className="table-select" value={runId} onChange={(e)=>setRunId(e.target.value)}>{runs.map((r)=><option key={String(r.backtest_run_id)} value={String(r.forecast_run_id)}>{String(r.backtest_run_id)}</option>)}</select><select className="table-select" value={itemId} onChange={(e)=>setItemId(e.target.value)}><option value="ALL">전체 SKU</option>{items.map((id)=><option key={id}>{id}</option>)}</select><button className="button" onClick={exportCsv}>CSV Export</button></div><div className="button-row comparison-toggles">{modelIds.map((id)=><label key={id}><input type="checkbox" checked={models.length===0||models.includes(id)} onChange={()=>toggle(id)}/>{id}</label>)}</div><ForecastOverlayChart><table className="analysis-table"><thead><tr><th>기간</th><th>Actual</th><th>Model</th><th>P50</th><th>P80</th><th>P90</th></tr></thead><tbody>{selected.map((r,i)=><tr key={`${r.model_id}-${r.period}-${i}`}><td>{String(r.period)}</td><td>{String(r.actual_qty ?? '—')}</td><td>{String(r.model_id)}</td><td>{String(r.p50 ?? '—')}</td><td>{String(r.p80 ?? '—')}</td><td>{String(r.p90 ?? '—')}</td></tr>)}</tbody></table></ForecastOverlayChart><div className="analysis-table-wrap"><table className="analysis-table"><thead><tr><th>Model</th><th>WAPE</th><th>MAPE</th><th>Bias</th><th>RMSE</th><th>MAE</th><th>Rank</th><th>Champion</th></tr></thead><tbody>{performance.filter((p)=>itemId==='ALL'||String(p.item_id)===itemId).map((p)=><tr key={`${p.backtest_run_id}-${p.item_id}-${p.model_id}`}><td>{String(p.model_id)}</td><td>{String(p.wape ?? '—')}</td><td>{String(p.mape ?? '—')}</td><td>{String(p.bias ?? '—')}</td><td>{String(p.rmse ?? '—')}</td><td>{String(p.mae ?? '—')}</td><td>{String(p.rank ?? '—')}</td><td>{champions.some((c)=>String(c.item_id)===String(p.item_id)&&String(c.champion_model_id)===String(p.model_id))?<Badge status="SAFE">Champion</Badge>:'—'}</td></tr>)}</tbody></table></div></>;
}
