import { createSupabaseServerClient } from '@/lib/supabase/server';
import type { ImportReferences, ImportRow, ImportType, ValidationResult } from './types';

export async function createImportBatch(fileName: string, importType: ImportType, importMode: string, rows: ImportRow[], userId: string) {
  const supabase = await createSupabaseServerClient();
  const { data: batch, error } = await supabase.schema('core').from('upload_batch').insert({ file_name: fileName, import_type: importType, import_mode: importMode, total_rows: rows.length, uploaded_by: userId }).select('batch_id').single();
  if (error || !batch) throw new Error(error?.message ?? '업로드 batch 생성에 실패했습니다.');
  for (let offset = 0; offset < rows.length; offset += 500) { const { error: stagingError } = await supabase.schema('core').from('import_staging').insert(rows.slice(offset, offset + 500).map((original_data, index) => ({ batch_id: batch.batch_id, row_number: offset + index + 2, original_data }))); if (stagingError) throw new Error(stagingError.message); }
  return batch.batch_id as string;
}
export async function importReferences(): Promise<ImportReferences> { const supabase = await createSupabaseServerClient(); const [{ data: items }, { data: suppliers }] = await Promise.all([supabase.schema('core').from('v_item_master').select('item_id'), supabase.schema('core').from('v_import_supplier_reference').select('supplier_id')]); return { itemIds: new Set((items ?? []).map((row) => String(row.item_id))), supplierIds: new Set((suppliers ?? []).map((row) => String(row.supplier_id))) }; }
export async function stageRows(batchId: string) { const supabase = await createSupabaseServerClient(); const { data, error } = await supabase.schema('core').from('import_staging').select('row_number, original_data').eq('batch_id', batchId).order('row_number'); if (error) throw new Error(error.message); return data ?? []; }
export async function saveValidation(batchId: string, result: ValidationResult, importType?: string, mapping?: Record<string, string | null>, userId?: string) { const supabase = await createSupabaseServerClient(); await supabase.schema('core').from('validation_error').delete().eq('batch_id', batchId); const { error: rowsError } = await supabase.schema('core').from('import_staging').upsert(result.rows.map((row) => ({ batch_id: batchId, row_number: row.rowNumber, original_data: row.data, mapped_data: row.data, validation_status: row.issues.some((issue) => issue.severity === 'ERROR') ? 'ERROR' : row.issues.length ? 'WARNING' : 'SUCCESS' })), { onConflict: 'batch_id,row_number' }); if (rowsError) throw new Error(rowsError.message); if (result.issues.length) { const { error } = await supabase.schema('core').from('validation_error').insert(result.issues.map((issue) => ({ batch_id: batchId, row_number: issue.rowNumber, field_name: issue.fieldName, error_code: issue.code, error_message: issue.message, severity: issue.severity, original_value: issue.originalValue === null ? null : String(issue.originalValue) }))); if (error) throw new Error(error.message); } if(importType&&mapping&&userId){await supabase.schema('core').from('column_mapping').upsert(Object.entries(mapping).filter(([,source])=>source).map(([target_column,source_column])=>({import_type:importType,source_column,target_column,created_by:userId})),{onConflict:'import_type,source_column,target_column'});} const { error } = await supabase.schema('core').from('upload_batch').update({ status: 'VALIDATED', ...result.summary }).eq('batch_id', batchId); if (error) throw new Error(error.message); }
