-- Task 15 fix round 2 · 5회차 더미 사용 이력 정리(되돌릴 수 있게) + 제거 표식 보강
--
-- 여기서 만드는 것
--   core.retired_usage_history                    정리한 raw.usage_history 행의 보관소(원본 그대로)
--   core.retire_unverified_usage_history(...)     ADMIN — 출처 없는 사용 이력을 보관소로 옮긴다
--   core.restore_retired_usage_history(...)       보관소의 행을 raw.usage_history로 되돌린다
--   analytics.v_practice_retired_usage            보관 현황(행 수 · 기간)
--   core.remove_practice_dataset(...) 재정의       ★ 아래 두 가지를 더한다
--
-- ══ 1. 왜 정리하는가 ═══════════════════════════════════════════════
--
-- 배포 DB의 raw.usage_history에는 5회차 실습 더미 7,038행이 batch_id = null로 남아 있습니다.
-- Task 9b의 원천 게이트는 학습·검증 기간에 출처 없는 행이 한 줄이라도 걸치면 (정상적으로) 발주량
-- 계산을 막습니다. 그래서 실습 데이터의 학습 기간을 그 더미 **뒤로** 밀어야 했고, 그 결과 실습
-- 기준월이 실제 달력보다 미래가 되는 부작용이 있었습니다.
--
-- 출처 없는 행을 보관소로 옮기면 그 제약이 사라져 학습 기간이 실제 달력 월에 놓입니다.
--
-- ★ 지우지 않습니다. 원본 행을 jsonb로 그대로 보관하고, 실습 묶음을 제거할 때 자동으로 되돌립니다.
--   제가 만들지 않은 기존 데이터이므로 복구 불가능한 방식은 쓰지 않습니다.
-- ★ 대상은 **출처가 없는 행만**입니다. 판정 조건은 원천 게이트가 보는 것과 정확히 같습니다
--   (batch_id가 없거나 · 그 배치가 IMPORTED usage_history가 아니거나 · source_type이 FILE_UPLOAD가 아님).
--   출처가 있는 행은 한 줄도 건드리지 않습니다.
--
-- ══ 2. N1 — 남는 행의 실습 표식이 벗겨지던 것 ═══════════════════════
--
-- 이전 정의는 발주계획이 있으면 FORECAST_RUN만 blocked에 넣고 v_backtests를 비웠습니다. 그래서
-- backtest_run · model_performance · champion_model_selection 행은 **남는데** BACKTEST_RUN 등기는
-- 지워졌습니다. item_policy_revision도 같은 문제였습니다(행은 남고 등기만 삭제).
-- 결과적으로 그 행들이 화면에서 더 이상 실습용으로 식별되지 않았습니다 — 표식이 무너지는 것이라
-- 이 작업의 근본 취지에 정면으로 어긋납니다.
--
-- 이번 정의는 두 가지를 바꿉니다.
--   (a) 계획 때문에 남는 Backtest 실행도 blocked에 넣습니다.
--   (b) 등기 정리를 "종류별 예외 목록"이 아니라 **그 객체가 실제로 지워졌는가**로 판정합니다.
--       살아남은 행의 등기는 종류와 무관하게 남습니다 — 같은 부류의 버그가 다시 생기지 않습니다.
--
-- ★ core.remove_practice_dataset은 20260912000400과 이 파일 두 곳에 있습니다. 파일명 순서상
--   **이 파일이 최종본**입니다. 0400의 본문을 고칠 때는 반드시 여기도 같이 고쳐야 합니다
--   (core.commit_import_batch가 STEP 4 · 0500 · 1150 세 곳에 있는 것과 같은 관례입니다).
--
-- 다시 실행해도 안전합니다. 실제 Supabase 적용은 사용자가 SQL Editor에서 수동으로 수행합니다.


-- ══ 3. 보관소 ══════════════════════════════════════════════════════

create table if not exists core.retired_usage_history (
  archive_id  bigint generated by default as identity primary key,
  dataset_id  uuid not null references core.practice_dataset(dataset_id) on delete restrict,
  -- 원본 행 전체를 그대로 보관한다. 컬럼이 늘어나도 복구가 깨지지 않는다.
  row_data    jsonb not null check (jsonb_typeof(row_data) = 'object'),
  use_date    date,
  retired_by  uuid references auth.users(id) on delete set null,
  retired_at  timestamptz not null default now()
);

create index if not exists retired_usage_history_dataset_idx on core.retired_usage_history (dataset_id);

comment on table core.retired_usage_history is
  'Task 15 fix round 2 — 출처 없는 raw.usage_history 행의 보관소. 지우지 않고 옮겨 둔다. '
  '실습 묶음을 제거하면 core.remove_practice_dataset이 자동으로 되돌린다';
comment on column core.retired_usage_history.row_data is
  '원본 raw.usage_history 행 전체(to_jsonb). 복구는 jsonb_populate_record로 원래 모양 그대로 되돌린다';


-- ══ 4. 정리 · 복구 함수 ════════════════════════════════════════════

create or replace function core.retire_unverified_usage_history(p_label text, p_confirm boolean default false)
returns jsonb
language plpgsql security definer set search_path = core, raw, public, pg_temp
as $$
declare
  v_dataset core.practice_dataset%rowtype;
  v_moved bigint;
  v_deleted bigint;
  v_min date;
  v_max date;
begin
  if not core.is_admin() then
    raise exception '관리자 권한이 필요합니다.' using errcode = '42501';
  end if;
  if not coalesce(p_confirm, false) then
    raise exception '정리를 실행하려면 p_confirm => true 를 명시해야 합니다.' using errcode = '22023';
  end if;

  select * into v_dataset from core.practice_dataset where label = btrim(p_label) and active for update;
  if not found then
    raise exception '열려 있는 실습 데이터 묶음을 찾을 수 없습니다: %', p_label using errcode = 'P0002';
  end if;

  -- ★ 판정 조건은 core.procurement_forecast_source_status가 보는 것과 정확히 같다.
  --   "검증됨" = 그 batch_id의 배치가 실재하고 · IMPORTED이고 · usage_history이고 · source_type이
  --   FILE_UPLOAD인 것. 그 밖이 전부 "출처 없음"이다.
  --
  -- ★★ 보관과 삭제는 **글자 그대로 같은 술어**를 써야 한다. 다른 술어를 쓰면
  --   (예: 보관은 left join의 b.batch_id is null, 삭제는 배치가 실재해야 하는 조건)
  --   batch_id가 존재하지 않는 배치를 가리키는 행이 보관만 되고 삭제되지 않아, 복구할 때
  --   **중복 행**이 된다. 아래 건수 비교가 그 경우를 소리 내어 막는다.
  -- ★ source_type이 null일 때 3값 논리로 조건이 null이 되지 않도록 is not distinct from을 쓴다.
  insert into core.retired_usage_history (dataset_id, row_data, use_date, retired_by)
  select v_dataset.dataset_id, to_jsonb(u), u.use_date, auth.uid()
    from raw.usage_history u
   where not (
     exists (select 1 from core.upload_batch b
              where b.batch_id = u.batch_id and b.status = 'IMPORTED' and b.import_type = 'usage_history')
     and u.source_type is not distinct from 'FILE_UPLOAD'
   );
  get diagnostics v_moved = row_count;

  delete from raw.usage_history u
   where not (
     exists (select 1 from core.upload_batch b
              where b.batch_id = u.batch_id and b.status = 'IMPORTED' and b.import_type = 'usage_history')
     and u.source_type is not distinct from 'FILE_UPLOAD'
   );
  get diagnostics v_deleted = row_count;

  if v_deleted is distinct from v_moved then
    raise exception '보관 건수(%)와 삭제 건수(%)가 다릅니다 — 복구 시 중복이 생기므로 정리를 중단합니다.',
      v_moved, v_deleted using errcode = '22023';
  end if;

  select min(use_date), max(use_date) into v_min, v_max
    from core.retired_usage_history where dataset_id = v_dataset.dataset_id;

  insert into core.audit_log (actor, action, target_type, target_id, before, after)
  values (auth.uid(), 'LEGACY_USAGE_RETIRED', 'retired_usage_history', v_dataset.dataset_id::text, null,
          jsonb_build_object('label', v_dataset.label, 'rows', v_moved, 'min_use_date', v_min, 'max_use_date', v_max));

  return jsonb_build_object(
    'label', v_dataset.label, 'retired_rows', v_moved,
    'min_use_date', v_min, 'max_use_date', v_max,
    'remaining_unverified_rows', (
      select count(*) from raw.usage_history u
       left join core.upload_batch b on b.batch_id = u.batch_id
      where b.batch_id is null or b.status <> 'IMPORTED' or b.import_type <> 'usage_history'
         or u.source_type is distinct from 'FILE_UPLOAD')
  );
end;
$$;

comment on function core.retire_unverified_usage_history(text, boolean) is
  'Task 15 fix round 2 — ADMIN. 출처 없는 raw.usage_history 행을 core.retired_usage_history로 옮긴다. '
  '지우지 않으며, 실습 묶음 제거 시 자동으로 되돌아온다. p_confirm => true 필수';

create or replace function core.restore_retired_usage_history(p_dataset_id uuid)
returns bigint
language plpgsql security definer set search_path = core, raw, public, pg_temp
as $$
declare
  v_restored bigint := 0;
  v_row record;
begin
  for v_row in
    select archive_id, row_data from core.retired_usage_history where dataset_id = p_dataset_id order by archive_id
  loop
    insert into raw.usage_history
    select * from jsonb_populate_record(null::raw.usage_history, v_row.row_data);
    v_restored := v_restored + 1;
  end loop;

  delete from core.retired_usage_history where dataset_id = p_dataset_id;
  return v_restored;
end;
$$;

comment on function core.restore_retired_usage_history(uuid) is
  'Task 15 fix round 2 — 보관소의 행을 raw.usage_history로 되돌리고 보관소를 비운다. '
  'core.remove_practice_dataset이 부른다(권한 검사는 호출자가 한다)';

revoke all on function core.restore_retired_usage_history(uuid) from public, anon, authenticated;
revoke all on function core.retire_unverified_usage_history(text, boolean) from public, anon;
grant execute on function core.retire_unverified_usage_history(text, boolean) to authenticated;


-- ══ 5. 보관 현황 뷰 ════════════════════════════════════════════════

-- ★ fix round 3 — security_invoker를 반드시 붙인다. 아래에서 core.retired_usage_history에 RLS를
--   켜고 core.is_admin()으로 제한해 놓고도, 뷰가 소유자 권한으로 돌면 일반 사용자가 이 뷰를 통해
--   보관 건수·기간을 그대로 읽는다(원본 테이블은 0행인데 뷰는 1행이 보이는 상태). 이 저장소의
--   다른 운영 뷰와 같은 관례다(SCHEMA.md — 신규 analytics 운영 뷰는 security_invoker = true).
create or replace view analytics.v_practice_retired_usage
with (security_invoker = true)
as
select d.label,
       d.active,
       count(r.archive_id)   as retired_rows,
       min(r.use_date)       as min_use_date,
       max(r.use_date)       as max_use_date,
       min(r.retired_at)     as retired_at
  from core.practice_dataset d
  join core.retired_usage_history r on r.dataset_id = d.dataset_id
 group by d.label, d.active;

comment on view analytics.v_practice_retired_usage is
  'Task 15 fix round 2 — 정리해 보관 중인 5회차 더미 사용 이력 현황. 실습 묶음을 제거하면 되돌아온다';

alter table core.retired_usage_history enable row level security;
drop policy if exists retired_usage_history_read on core.retired_usage_history;
create policy retired_usage_history_read on core.retired_usage_history
  for select to authenticated using (core.is_admin());

revoke all on core.retired_usage_history from anon, public;
revoke insert, update, delete on core.retired_usage_history from authenticated;
grant select on core.retired_usage_history to authenticated;
grant select on analytics.v_practice_retired_usage to authenticated;
revoke all on analytics.v_practice_retired_usage from anon;


-- ══ 6. core.remove_practice_dataset 재정의 ═════════════════════════
--
-- ★ 20260912000400의 정의를 그대로 두고 두 가지만 바꾼다(N1 + 보관 행 복구).
--   0400을 고칠 때는 여기도 반드시 같이 고친다 — 파일명 순서상 이쪽이 최종본이다.

create or replace function core.remove_practice_dataset(p_label text, p_confirm boolean default false)
returns jsonb
language plpgsql security definer set search_path = core, public, pg_temp
as $$
declare
  v_dataset   core.practice_dataset%rowtype;
  v_blocked   jsonb := '[]'::jsonb;
  v_removed   jsonb := '{}'::jsonb;
  v_items     text[];
  v_blocked_items text[] := '{}';
  v_batches   uuid[];
  v_runs      uuid[];
  v_backtests uuid[];
  v_plans     uuid[];
  v_n         bigint;
  v_total     bigint := 0;
  v_key       text;
begin
  if not core.is_admin() then
    raise exception '관리자 권한이 필요합니다.' using errcode = '42501';
  end if;
  if not coalesce(p_confirm, false) then
    raise exception '제거를 실행하려면 p_confirm => true 를 명시해야 합니다.' using errcode = '22023';
  end if;

  select * into v_dataset from core.practice_dataset where label = btrim(p_label) for update;
  if not found then
    raise exception '실습 데이터 묶음을 찾을 수 없습니다: %', p_label using errcode = 'P0002';
  end if;
  if not v_dataset.active then
    raise exception '이미 제거된 실습 데이터 묶음입니다: %', p_label using errcode = '22023';
  end if;

  select coalesce(array_agg(object_key), '{}') into v_items
    from core.practice_object where dataset_id = v_dataset.dataset_id and object_kind = 'ITEM';
  select coalesce(array_agg(object_key::uuid), '{}') into v_batches
    from core.practice_object where dataset_id = v_dataset.dataset_id and object_kind = 'UPLOAD_BATCH';
  select coalesce(array_agg(object_key::uuid), '{}') into v_runs
    from core.practice_object where dataset_id = v_dataset.dataset_id and object_kind = 'FORECAST_RUN';
  select coalesce(array_agg(object_key::uuid), '{}') into v_backtests
    from core.practice_object where dataset_id = v_dataset.dataset_id and object_kind = 'BACKTEST_RUN';
  select coalesce(array_agg(object_key::uuid), '{}') into v_plans
    from core.practice_object where dataset_id = v_dataset.dataset_id and object_kind = 'PROCUREMENT_PLAN';

  -- ── 사람이 이미 업무를 한 품목은 지우지 않는다 ───────────────────
  for v_key in
    select distinct acted.item_id
      from (
        select l.item_id from core.sales_order_line l
        union all select a.item_id from core.stock_allocation a
        union all select u.item_id from core.urgent_order u
        union all select m.item_id from core.supply_meeting_result m
        union all select e.item_id from core.event_demand e
      ) acted
     where acted.item_id = any(v_items)
  loop
    v_blocked := v_blocked || jsonb_build_array(jsonb_build_object(
      'kind', 'ITEM', 'key', v_key, 'reason', 'ACTED_ON_BY_USER'));
    v_items := array_remove(v_items, v_key);
    v_blocked_items := array_append(v_blocked_items, v_key);
  end loop;

  -- 발주계획 라인이 참조하는 품목도 지우지 않는다(계획은 어떤 상태에서도 삭제할 수 없다).
  for v_key in
    select distinct l.item_id from core.procurement_plan_line l where l.item_id = any(v_items)
  loop
    v_blocked := v_blocked || jsonb_build_array(jsonb_build_object(
      'kind', 'ITEM', 'key', v_key, 'reason', 'PLAN_REFERENCES_ITEM'));
    v_items := array_remove(v_items, v_key);
    v_blocked_items := array_append(v_blocked_items, v_key);
  end loop;

  if to_regclass('core.receipt_schedule_result') is not null then
    for v_key in
      select distinct s.supplier_id
        from core.procurement_schedule s
        join core.receipt_schedule_result r on r.schedule_id = s.schedule_id
       where r.actual_receipt_date is not null and s.supplier_id is not null
         and exists (select 1 from core.practice_object o
                      where o.dataset_id = v_dataset.dataset_id and o.object_kind = 'SUPPLIER' and o.object_key = s.supplier_id)
    loop
      v_blocked := v_blocked || jsonb_build_array(jsonb_build_object(
        'kind', 'SUPPLIER', 'key', v_key, 'reason', 'SCHEDULE_ACTUAL_RECORDED'));
    end loop;
  end if;

  for v_key in select p::text from unnest(v_plans) as p loop
    v_blocked := v_blocked || jsonb_build_array(jsonb_build_object(
      'kind', 'PROCUREMENT_PLAN', 'key', v_key, 'reason', 'PLAN_IMMUTABLE_HISTORY'));
  end loop;

  -- ── 지울 수 있는 것을 의존 순서대로 지운다 ───────────────────────
  if exists (select 1 from core.procurement_plan p where p.forecast_run_id = any(v_runs)) then
    for v_key in select r::text from unnest(v_runs) as r loop
      v_blocked := v_blocked || jsonb_build_array(jsonb_build_object(
        'kind', 'FORECAST_RUN', 'key', v_key, 'reason', 'PLAN_IMMUTABLE_HISTORY'));
    end loop;
    -- ★ fix round 2 (N1) — 그 실행을 참조하는 Backtest · Champion · 모델 성능 행도 함께 남는다.
    --   여기서 blocked에 넣지 않으면 행은 남는데 등기만 지워져, 그 행들이 화면에서 실습용으로
    --   식별되지 않는다(/admin/backtest-runs · champion-models 안내가 조용히 사라진다).
    for v_key in select b::text from unnest(v_backtests) as b loop
      v_blocked := v_blocked || jsonb_build_array(jsonb_build_object(
        'kind', 'BACKTEST_RUN', 'key', v_key, 'reason', 'PLAN_IMMUTABLE_HISTORY'));
    end loop;
    v_runs := '{}';
    v_backtests := '{}';
  end if;

  delete from core.champion_model_selection where backtest_run_id = any(v_backtests);
  get diagnostics v_n = row_count; v_removed := v_removed || jsonb_build_object('champion_model_selection', v_n); v_total := v_total + v_n;
  delete from core.model_performance where backtest_run_id = any(v_backtests);
  get diagnostics v_n = row_count; v_removed := v_removed || jsonb_build_object('model_performance', v_n); v_total := v_total + v_n;
  delete from core.backtest_run where backtest_run_id = any(v_backtests);
  get diagnostics v_n = row_count; v_removed := v_removed || jsonb_build_object('backtest_run', v_n); v_total := v_total + v_n;

  delete from core.forecast_run where run_id = any(v_runs);
  get diagnostics v_n = row_count; v_removed := v_removed || jsonb_build_object('forecast_run', v_n); v_total := v_total + v_n;

  delete from core.demand_submission_event e
   where e.submission_id in (select s.submission_id from core.demand_submission s
                              where s.cycle_id in (select o.object_key::uuid from core.practice_object o
                                                    where o.dataset_id = v_dataset.dataset_id and o.object_kind = 'PLANNING_CYCLE'));
  get diagnostics v_n = row_count; v_removed := v_removed || jsonb_build_object('demand_submission_event', v_n); v_total := v_total + v_n;
  delete from core.demand_submission s
   where s.cycle_id in (select o.object_key::uuid from core.practice_object o
                         where o.dataset_id = v_dataset.dataset_id and o.object_kind = 'PLANNING_CYCLE');
  get diagnostics v_n = row_count; v_removed := v_removed || jsonb_build_object('demand_submission', v_n); v_total := v_total + v_n;
  delete from core.planning_cycle c
   where c.cycle_id in (select o.object_key::uuid from core.practice_object o
                         where o.dataset_id = v_dataset.dataset_id and o.object_kind = 'PLANNING_CYCLE');
  get diagnostics v_n = row_count; v_removed := v_removed || jsonb_build_object('planning_cycle', v_n); v_total := v_total + v_n;

  delete from core.month_end_inventory_snapshot where item_id = any(v_items);
  get diagnostics v_n = row_count; v_removed := v_removed || jsonb_build_object('month_end_inventory_snapshot', v_n); v_total := v_total + v_n;
  delete from core.stock_receipt_ledger where item_id = any(v_items);
  get diagnostics v_n = row_count; v_removed := v_removed || jsonb_build_object('stock_receipt_ledger', v_n); v_total := v_total + v_n;
  delete from core.stock_balance where item_id = any(v_items);
  get diagnostics v_n = row_count; v_removed := v_removed || jsonb_build_object('stock_balance', v_n); v_total := v_total + v_n;

  delete from core.item_policy_revision where item_id = any(v_items);
  get diagnostics v_n = row_count; v_removed := v_removed || jsonb_build_object('item_policy_revision', v_n); v_total := v_total + v_n;
  delete from core.item_policy where item_id = any(v_items);
  get diagnostics v_n = row_count; v_removed := v_removed || jsonb_build_object('item_policy', v_n); v_total := v_total + v_n;

  delete from raw.usage_history
   where batch_id = any(v_batches)
     and upper(regexp_replace(coalesce(item_id, ''), '[\s\-_]', '', 'g')) <> all(v_blocked_items);
  get diagnostics v_n = row_count; v_removed := v_removed || jsonb_build_object('raw.usage_history', v_n); v_total := v_total + v_n;
  delete from raw.inventory
   where batch_id = any(v_batches)
     and upper(regexp_replace(coalesce("품목코드", ''), '[\s\-_]', '', 'g')) <> all(v_blocked_items);
  get diagnostics v_n = row_count; v_removed := v_removed || jsonb_build_object('raw.inventory', v_n); v_total := v_total + v_n;
  delete from raw.item_master
   where batch_id = any(v_batches)
     and upper(regexp_replace(coalesce("품목코드", ''), '[\s\-_]', '', 'g')) <> all(v_blocked_items);
  get diagnostics v_n = row_count; v_removed := v_removed || jsonb_build_object('raw.item_master', v_n); v_total := v_total + v_n;
  delete from raw.goods_receipt
   where batch_id = any(v_batches)
     and upper(regexp_replace(coalesce("품목코드", ''), '[\s\-_]', '', 'g')) <> all(v_blocked_items);
  get diagnostics v_n = row_count; v_removed := v_removed || jsonb_build_object('raw.goods_receipt', v_n); v_total := v_total + v_n;
  delete from raw.purchase_order
   where batch_id = any(v_batches)
     and upper(regexp_replace(coalesce("품목코드", ''), '[\s\-_]', '', 'g')) <> all(v_blocked_items);
  get diagnostics v_n = row_count; v_removed := v_removed || jsonb_build_object('raw.purchase_order', v_n); v_total := v_total + v_n;
  delete from raw.supplier_master where batch_id = any(v_batches);
  get diagnostics v_n = row_count; v_removed := v_removed || jsonb_build_object('raw.supplier_master', v_n); v_total := v_total + v_n;

  if array_length(v_blocked_items, 1) is null then
    delete from core.upload_batch where batch_id = any(v_batches);
    get diagnostics v_n = row_count;
  else
    v_n := 0;
    for v_key in select b::text from unnest(v_batches) as b loop
      v_blocked := v_blocked || jsonb_build_array(jsonb_build_object(
        'kind', 'UPLOAD_BATCH', 'key', v_key, 'reason', 'RETAINED_FOR_BLOCKED_ITEM'));
    end loop;
  end if;
  v_removed := v_removed || jsonb_build_object('upload_batch', v_n); v_total := v_total + v_n;

  delete from core.supplier_departure d
   where d.departure_id in (select o.object_key::bigint from core.practice_object o
                             where o.dataset_id = v_dataset.dataset_id and o.object_kind = 'SUPPLIER_DEPARTURE');
  get diagnostics v_n = row_count; v_removed := v_removed || jsonb_build_object('supplier_departure', v_n); v_total := v_total + v_n;

  v_n := 0;
  for v_key in
    select o.object_key from core.practice_object o
     where o.dataset_id = v_dataset.dataset_id and o.object_kind = 'SUPPLIER'
       and not exists (select 1 from jsonb_array_elements(v_blocked) b
                        where b->>'kind' = 'SUPPLIER' and b->>'key' = o.object_key)
  loop
    begin
      delete from core.supplier where supplier_id = v_key;
      v_n := v_n + 1;
    exception when foreign_key_violation then
      v_blocked := v_blocked || jsonb_build_array(jsonb_build_object(
        'kind', 'SUPPLIER', 'key', v_key, 'reason', 'FK_IN_USE'));
    end;
  end loop;
  v_removed := v_removed || jsonb_build_object('supplier', v_n); v_total := v_total + v_n;

  delete from core.business_calendar c
   where (c.country_code || ':' || c.calendar_date::text) in (
     select o.object_key from core.practice_object o
      where o.dataset_id = v_dataset.dataset_id and o.object_kind = 'BUSINESS_CALENDAR');
  get diagnostics v_n = row_count; v_removed := v_removed || jsonb_build_object('business_calendar', v_n); v_total := v_total + v_n;

  delete from core.business_calendar_readiness r
   where (r.country_code || ':' || r.cal_year::text || '-' || lpad(r.cal_month::text, 2, '0')) in (
     select o.object_key from core.practice_object o
      where o.dataset_id = v_dataset.dataset_id and o.object_kind = 'CALENDAR_READINESS');
  get diagnostics v_n = row_count; v_removed := v_removed || jsonb_build_object('business_calendar_readiness', v_n); v_total := v_total + v_n;

  update core.supply_entity e
     set prep_days = coalesce((v_dataset.restore_payload -> 'supply_entity_prep_days' ->> e.entity_id)::integer, e.prep_days),
         updated_at = now()
   where e.entity_id in (select o.object_key from core.practice_object o
                          where o.dataset_id = v_dataset.dataset_id and o.object_kind = 'SUPPLY_ENTITY');
  get diagnostics v_n = row_count; v_removed := v_removed || jsonb_build_object('supply_entity_restored', v_n);

  delete from core.forecast_setting s
   where s.setting_id in (select o.object_key::uuid from core.practice_object o
                           where o.dataset_id = v_dataset.dataset_id and o.object_kind = 'FORECAST_SETTING');
  get diagnostics v_n = row_count; v_removed := v_removed || jsonb_build_object('forecast_setting', v_n); v_total := v_total + v_n;
  if v_dataset.restore_payload ? 'previous_forecast_setting_id' then
    update core.forecast_setting
       set active = true, updated_at = now()
     where setting_id = (v_dataset.restore_payload ->> 'previous_forecast_setting_id')::uuid;
  end if;

  -- ★ fix round 2 — 정리해 둔 5회차 더미 사용 이력을 되돌린다. 제가 만들지 않은 기존 데이터이므로
  --   실습을 걷어내면 원래 자리로 돌아가야 한다.
  v_n := core.restore_retired_usage_history(v_dataset.dataset_id);
  v_removed := v_removed || jsonb_build_object('raw.usage_history_restored', v_n);

  -- ── 등기 정리 ────────────────────────────────────────────────────
  -- ★ fix round 2 (N1) — "지워졌는가"로 판정한다. 살아남은 행의 등기는 종류와 무관하게 남긴다.
  --   이전 정의는 종류별 예외 목록이라 BACKTEST_RUN · ITEM_POLICY_REVISION처럼 목록에 없는 종류의
  --   등기가 행이 남았는데도 지워졌다(표식이 벗겨졌다).
  -- ★ fix round 3 — 아래 case가 모르는 종류(나중에 추가될 object_kind)는 **남긴다**. 남겼다는
  --   사실을 결과에 함께 보고해 조용히 넘어가지 않게 한다. 모르는 것을 지우는 쪽으로 기본값을
  --   두면, 종류가 늘어날 때마다 N1과 똑같은 방식으로 표식이 벗겨진다.
  -- ★★ Task 17 리뷰 fix round 1(2026-09-12) — ITEM 존재 검사를 core.v_item_master(화면
  --   가시성, 출처 게이트가 걸린 뷰)가 아니라 raw.item_master(원본 행 존재)로 바꾼다. 이
  --   블록의 질문은 "이 등기가 가리키는 원본 행이 아직 있는가"이지 "지금 화면에 보이는가"가
  --   아니다 — 화면 가시성과 등기 유효성은 다른 축이다(리뷰어 실측: 출처 없는 품목을 ITEM으로
  --   등기하면 게이트 뒤 core.v_item_master에서 사라져 이 DELETE가 "원본이 없어졌다"고 오판해
  --   실습 표식을 지웠다 — N1과 같은 실패 모드, 이번엔 게이트가 새로 만든 구멍이다). 배포
  --   DB의 실습 11품목이 전부 batch_id를 갖는 것은 지금 데이터의 우연일 뿐
  --   core.register_practice_object가 강제하는 불변식이 아니다(그 함수는 core.practice_object
  --   에만 INSERT하고 raw.item_master.batch_id를 전혀 건드리지 않는다) — 그러니 이 존재
  --   검사도 그 우연에 기대면 안 된다.
  select v_blocked || coalesce(jsonb_agg(jsonb_build_object(
           'kind', o.object_kind, 'key', o.object_key, 'reason', 'UNKNOWN_OBJECT_KIND')), '[]'::jsonb)
    into v_blocked
    from core.practice_object o
   where o.dataset_id = v_dataset.dataset_id
     and o.object_kind not in (
       'ITEM', 'ITEM_POLICY', 'ITEM_POLICY_REVISION', 'UPLOAD_BATCH', 'FORECAST_RUN', 'BACKTEST_RUN',
       'PROCUREMENT_PLAN', 'PLANNING_CYCLE', 'DEMAND_SUBMISSION', 'SUPPLIER', 'SUPPLIER_DEPARTURE',
       'BUSINESS_CALENDAR', 'CALENDAR_READINESS', 'FORECAST_SETTING', 'SUPPLY_ENTITY'
     );

  delete from core.practice_object o
   where o.dataset_id = v_dataset.dataset_id
     and not case o.object_kind
       when 'ITEM'                 then exists (select 1 from raw.item_master m where core.normalize_item_id(m."품목코드") = o.object_key)
       when 'ITEM_POLICY'          then exists (select 1 from core.item_policy p where p.item_id = o.object_key)
       when 'ITEM_POLICY_REVISION' then exists (select 1 from core.item_policy_revision r where r.revision_id::text = o.object_key)
       when 'UPLOAD_BATCH'         then exists (select 1 from core.upload_batch b where b.batch_id::text = o.object_key)
       when 'FORECAST_RUN'         then exists (select 1 from core.forecast_run r where r.run_id::text = o.object_key)
       when 'BACKTEST_RUN'         then exists (select 1 from core.backtest_run b where b.backtest_run_id::text = o.object_key)
       when 'PROCUREMENT_PLAN'     then exists (select 1 from core.procurement_plan p where p.plan_id::text = o.object_key)
       when 'PLANNING_CYCLE'       then exists (select 1 from core.planning_cycle c where c.cycle_id::text = o.object_key)
       when 'DEMAND_SUBMISSION'    then exists (select 1 from core.demand_submission s where s.submission_id::text = o.object_key)
       when 'SUPPLIER'             then exists (select 1 from core.supplier s where s.supplier_id = o.object_key)
       when 'SUPPLIER_DEPARTURE'   then exists (select 1 from core.supplier_departure d where d.departure_id::text = o.object_key)
       when 'BUSINESS_CALENDAR'    then exists (select 1 from core.business_calendar c
                                                 where c.country_code || ':' || c.calendar_date::text = o.object_key)
       when 'CALENDAR_READINESS'   then exists (select 1 from core.business_calendar_readiness r
                                                 where r.country_code || ':' || r.cal_year::text || '-' || lpad(r.cal_month::text, 2, '0') = o.object_key)
       when 'FORECAST_SETTING'     then exists (select 1 from core.forecast_setting s where s.setting_id::text = o.object_key)
       -- 해외법인 행은 지우지 않고 준비기간만 원래 값으로 되돌리므로, 더 이상 실습 객체가 아니다.
       when 'SUPPLY_ENTITY'        then false
       -- ★ fix round 3 — 모르는 종류는 **남긴다**(위에서 UNKNOWN_OBJECT_KIND로 보고했다).
       --   이전 정의는 else false였고, 그래서 case에 없는 종류의 등기가 조용히 지워졌다.
       else true
     end;

  update core.practice_dataset
     set active = false, removed_by = auth.uid(), removed_at = clock_timestamp()
   where dataset_id = v_dataset.dataset_id;

  insert into core.audit_log (actor, action, target_type, target_id, before, after)
  values (auth.uid(), 'PRACTICE_DATASET_REMOVED', 'practice_dataset', v_dataset.dataset_id::text,
          jsonb_build_object('label', v_dataset.label),
          jsonb_build_object('removed', v_removed, 'blocked', v_blocked, 'total_rows_deleted', v_total));

  return jsonb_build_object(
    'label', v_dataset.label,
    'total_rows_deleted', v_total,
    'removed', v_removed,
    'blocked', v_blocked,
    'residual_objects', (select count(*) from core.practice_object where dataset_id = v_dataset.dataset_id)
  );
end;
$$;

comment on function core.remove_practice_dataset(text, boolean) is
  'Task 15(+fix round 2) — ADMIN. 등기된 실습 객체만 지운다. 살아남은 행의 등기는 남겨 화면이 계속 '
  '실습용으로 표시한다. 정리해 둔 5회차 더미 사용 이력도 이때 되돌린다. p_confirm => true 필수. '
  '★ 20260912000400에도 같은 함수가 있다 — 이 파일이 최종본이다';

grant execute on function core.remove_practice_dataset(text, boolean) to authenticated;
revoke all on function core.remove_practice_dataset(text, boolean) from public, anon;


-- ══ 7. 확인 쿼리 ═══════════════════════════════════════════════════

-- (a) 정리 전 — 출처 없는 행이 몇 건이고 어느 기간인가
-- select count(*) as unverified_rows, min(use_date), max(use_date)
--   from raw.usage_history u left join core.upload_batch b on b.batch_id = u.batch_id
--  where b.batch_id is null or b.status <> 'IMPORTED' or b.import_type <> 'usage_history'
--     or u.source_type is distinct from 'FILE_UPLOAD';

-- (b) 정리 — supabase/practice-data/00b-retire-legacy-usage.sql 참고
-- select jsonb_pretty(core.retire_unverified_usage_history('PRACTICE-2026-09', p_confirm => true));
-- 기대: retired_rows > 0 · remaining_unverified_rows = 0

-- (c) 보관 현황
-- select * from analytics.v_practice_retired_usage;

-- (d) 복구 — 실습 묶음을 제거하면 자동으로 돌아온다
-- select jsonb_pretty(core.remove_practice_dataset('PRACTICE-2026-09', p_confirm => true));
-- select count(*) from raw.usage_history where batch_id is null;   -- 정리 전과 같아야 한다
