create schema if not exists core;
create schema if not exists analytics;

create table if not exists core.app_user (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  name text not null default '',
  department text,
  role text not null default 'USER' check (role in ('ADMIN', 'USER')),
  active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists core.audit_log (
  id bigint generated by default as identity primary key,
  actor uuid references auth.users(id) on delete set null,
  action text not null,
  target_type text not null,
  target_id text not null,
  before jsonb,
  after jsonb,
  at timestamptz not null default now()
);

create index if not exists app_user_role_active_idx on core.app_user (role, active);
create index if not exists audit_log_target_idx on core.audit_log (target_type, target_id, at desc);
create index if not exists audit_log_actor_idx on core.audit_log (actor, at desc);

create or replace function core.set_updated_at()
returns trigger
language plpgsql
set search_path = core, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function core.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = core, auth, pg_temp
as $$
begin
  insert into core.app_user (user_id, email, name, department, role, active)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'name', new.raw_user_meta_data ->> 'full_name', split_part(coalesce(new.email, ''), '@', 1)),
    nullif(new.raw_user_meta_data ->> 'department', ''),
    'USER',
    true
  )
  on conflict (user_id) do update
    set email = excluded.email,
        name = case when core.app_user.name = '' then excluded.name else core.app_user.name end,
        updated_at = now();
  return new;
end;
$$;

create or replace function core.is_admin(check_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = core, pg_temp
as $$
  select exists (
    select 1
      from core.app_user
     where user_id = check_user_id
       and role = 'ADMIN'
       and active = true
  );
$$;

create or replace function core.is_active_user(check_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = core, pg_temp
as $$
  select exists (
    select 1
      from core.app_user
     where user_id = check_user_id
       and active = true
  );
$$;

create or replace function core.mark_login()
returns void
language sql
volatile
security definer
set search_path = core, pg_temp
as $$
  update core.app_user
     set last_login_at = now(), updated_at = now()
   where user_id = auth.uid()
     and active = true;
$$;

create or replace function core.protect_self_admin_change()
returns trigger
language plpgsql
set search_path = core, pg_temp
as $$
begin
  if auth.uid() = old.user_id and old.role = 'ADMIN' and new.role <> 'ADMIN' then
    raise exception '자신의 관리자 권한은 제거할 수 없습니다.' using errcode = '42501';
  end if;
  if auth.uid() = old.user_id and old.active = true and new.active = false then
    raise exception '자신의 계정은 비활성화할 수 없습니다.' using errcode = '42501';
  end if;
  return new;
end;
$$;

create or replace function core.audit_app_user_change()
returns trigger
language plpgsql
security definer
set search_path = core, pg_temp
as $$
begin
  if old.role is distinct from new.role then
    insert into core.audit_log (actor, action, target_type, target_id, before, after)
    values (
      auth.uid(), 'USER_ROLE_CHANGED', 'app_user', new.user_id::text,
      jsonb_build_object('role', old.role, 'active', old.active),
      jsonb_build_object('role', new.role, 'active', new.active)
    );
  end if;

  if old.active is distinct from new.active then
    insert into core.audit_log (actor, action, target_type, target_id, before, after)
    values (
      auth.uid(), 'USER_ACTIVE_CHANGED', 'app_user', new.user_id::text,
      jsonb_build_object('role', old.role, 'active', old.active),
      jsonb_build_object('role', new.role, 'active', new.active)
    );
  end if;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert or update of email, raw_user_meta_data on auth.users
  for each row execute function core.handle_new_auth_user();

drop trigger if exists app_user_set_updated_at on core.app_user;
create trigger app_user_set_updated_at
  before update on core.app_user
  for each row execute function core.set_updated_at();

drop trigger if exists app_user_protect_self_change on core.app_user;
create trigger app_user_protect_self_change
  before update of role, active on core.app_user
  for each row execute function core.protect_self_admin_change();

drop trigger if exists app_user_audit_change on core.app_user;
create trigger app_user_audit_change
  after update of role, active on core.app_user
  for each row execute function core.audit_app_user_change();

insert into core.app_user (user_id, email, name, department, role, active, created_at, updated_at)
select id,
       coalesce(email, ''),
       coalesce(raw_user_meta_data ->> 'name', raw_user_meta_data ->> 'full_name', split_part(coalesce(email, ''), '@', 1)),
       nullif(raw_user_meta_data ->> 'department', ''),
       'USER',
       true,
       created_at,
       now()
  from auth.users
on conflict (user_id) do nothing;

alter table core.app_user enable row level security;
alter table core.audit_log enable row level security;

drop policy if exists app_user_select_self_or_admin on core.app_user;
create policy app_user_select_self_or_admin
  on core.app_user
  for select
  to authenticated
  using (user_id = auth.uid() or core.is_admin());

drop policy if exists app_user_admin_update on core.app_user;
create policy app_user_admin_update
  on core.app_user
  for update
  to authenticated
  using (core.is_admin())
  with check (core.is_admin());

drop policy if exists audit_log_admin_select on core.audit_log;
create policy audit_log_admin_select
  on core.audit_log
  for select
  to authenticated
  using (core.is_admin());

do $rbac$
begin
  if to_regclass('core.leadtime_plan') is not null then
    execute 'alter table core.leadtime_plan enable row level security';
    execute 'drop policy if exists "수업용 전체 허용" on core.leadtime_plan';
    execute 'drop policy if exists leadtime_plan_user_select on core.leadtime_plan';
    execute 'drop policy if exists leadtime_plan_admin_insert on core.leadtime_plan';
    execute 'drop policy if exists leadtime_plan_admin_update on core.leadtime_plan';
    execute 'drop policy if exists leadtime_plan_admin_delete on core.leadtime_plan';
    execute 'create policy leadtime_plan_user_select on core.leadtime_plan for select to authenticated using (core.is_active_user())';
    execute 'create policy leadtime_plan_admin_insert on core.leadtime_plan for insert to authenticated with check (core.is_admin())';
    execute 'create policy leadtime_plan_admin_update on core.leadtime_plan for update to authenticated using (core.is_admin()) with check (core.is_admin())';
    execute 'create policy leadtime_plan_admin_delete on core.leadtime_plan for delete to authenticated using (core.is_admin())';
    execute 'grant select, insert, update, delete on core.leadtime_plan to authenticated';
  end if;

  if to_regclass('core.usage_profile') is not null then
    execute 'alter table core.usage_profile enable row level security';
    execute 'drop policy if exists "수업용 전체 허용" on core.usage_profile';
    execute 'drop policy if exists usage_profile_user_select on core.usage_profile';
    execute 'drop policy if exists usage_profile_admin_insert on core.usage_profile';
    execute 'drop policy if exists usage_profile_admin_update on core.usage_profile';
    execute 'drop policy if exists usage_profile_admin_delete on core.usage_profile';
    execute 'create policy usage_profile_user_select on core.usage_profile for select to authenticated using (core.is_active_user())';
    execute 'create policy usage_profile_admin_insert on core.usage_profile for insert to authenticated with check (core.is_admin())';
    execute 'create policy usage_profile_admin_update on core.usage_profile for update to authenticated using (core.is_admin()) with check (core.is_admin())';
    execute 'create policy usage_profile_admin_delete on core.usage_profile for delete to authenticated using (core.is_admin())';
    execute 'grant select, insert, update, delete on core.usage_profile to authenticated';
  end if;
end;
$rbac$;

do $public_rbac$
declare
  table_name text;
begin
  foreach table_name in array array[
    'planning_runs', 'ol_demand', 'sfdc_pipeline', 'bulk_deals',
    'historical_actuals', 'demand_confirmations'
  ] loop
    if to_regclass(format('public.%I', table_name)) is not null then
      execute format('alter table public.%I enable row level security', table_name);
      execute format('revoke all on public.%I from anon', table_name);
      execute format('grant select, insert, update, delete on public.%I to authenticated', table_name);
      execute format('drop policy if exists %I on public.%I', table_name || '_user_select', table_name);
      execute format('drop policy if exists %I on public.%I', table_name || '_admin_mutation', table_name);
      execute format('create policy %I on public.%I for select to authenticated using (core.is_active_user())', table_name || '_user_select', table_name);
      execute format('create policy %I on public.%I for all to authenticated using (core.is_admin()) with check (core.is_admin())', table_name || '_admin_mutation', table_name);
    end if;
  end loop;
end;
$public_rbac$;

revoke all on schema core from anon;
revoke all on schema analytics from anon;
revoke all on all tables in schema core from anon;
revoke all on all tables in schema analytics from anon;
alter default privileges in schema core revoke all on tables from anon;
alter default privileges in schema analytics revoke all on tables from anon;

grant usage on schema core, analytics to authenticated;
grant select on all tables in schema analytics to authenticated;
grant select on core.app_user, core.audit_log to authenticated;
grant update (role, active) on core.app_user to authenticated;
grant execute on function core.is_admin(uuid), core.is_active_user(uuid) to authenticated;
grant execute on function core.mark_login() to authenticated;

revoke insert, update, delete on core.audit_log from authenticated;
revoke execute on function core.is_admin(uuid), core.is_active_user(uuid), core.mark_login() from public, anon;
revoke execute on function core.handle_new_auth_user(), core.audit_app_user_change(), core.protect_self_admin_change() from public, anon, authenticated;

alter default privileges in schema analytics grant select on tables to authenticated;
