-- Task 4 · 정상 창고재고와 가용재고 기준 확정
--
-- 목적: Open PO와 이동 중 수량을 제외하고, 중복 배정을 방지할 수 있는 단일 가용재고
-- 기준을 만든다. 실제 Supabase 적용은 사용자가 SQL Editor에서 수동으로 수행한다.
--
-- ★ raw.inventory 는 5회차 실습 더미 43행이 그대로 남아 있는 테이블이다. 이 마이그레이션이
--   추가하는 inventory_status · snapshot_at · warehouse_code 는 모두 nullable이며, 기존
--   43행은 이 값이 전부 null이다. 이 마이그레이션은 그 행을 NORMAL로 추정하지 않는다 —
--   분류할 수 없으면 core.stock_balance에 아예 올리지 않고, analytics.v_available_stock은
--   그 품목을 null + INVENTORY_SCOPE_UNCLASSIFIED로 보여준다.
-- ★ 다시 실행해도 안전하다 (if not exists · create or replace · drop/재생성 정책).
--
-- fix round 1 (리뷰 반영):
--   1) core.commit_import_batch(STEP 4)를 재정의해 신규 컬럼을 raw에 실제로 적재하고,
--      inventory 커밋 직후 같은 트랜잭션에서 정상 창고재고를 자동 반영한다.
--   2) 그 자동 반영은 새 내부 함수 core.apply_stock_balance_from_batch로 분리했다.
--   3) stock_balance.snapshot_at은 NORMAL 행만의 최신 시각이다.
--   4) ATP_VIEW 전용 사용자는 재고 상세가 아니라 analytics.v_order_available_stock만 본다.
--   5) core.inventory_scope_rule이 창고코드+재고상태 조합을 매핑하고, 더 구체적인 규칙이
--      이긴다(창고+상태 > 창고전용 > 상태전용).
--
-- fix round 2 (리뷰 반영):
--   6) 완료된 입고가 core.stock_balance를 실제로 늘린다 — core.stock_receipt_ledger에
--      건별로 append-only 기록하고, "최신 NORMAL 스냅샷 수량 + 그 스냅샷 시각 이후 완료된
--      입고 합"으로 정상 창고재고를 계산한다. 같은 입고를 두 번 반영하지 않는다(유니크 키).
--      새 스냅샷은 그 이전 입고를 흡수한다(스냅샷 시각 이후분만 다시 더한다).
--   7) 창고전용 예시 시드(SERVICE_CENTER · PARTNER)를 지웠다 — 실제 창고 표기를 모르는데
--      가짜 마스터값을 심어 두면 실데이터를 잘못 분류할 위험이 있다. 표·우선순위 로직·유니크
--      제약은 그대로 두고, 실제 표기가 오면 채우도록 docs/데이터-요청목록.md에 요청을 남겼다.
--
-- fix round 3 (리뷰 반영):
--   8) 수량 0인 완료 입고를 core.stock_receipt_ledger에 넣지 않는다 — 그 표의 qty > 0
--      체크에 걸려 commit_import_batch 트랜잭션 전체가 롤백되는 문제였다(그 배치의 다른
--      정상 입고까지 함께 사라졌다). validate.ts는 음수만 막고 0은 통과시키므로 여기서 막는다.
--   9) core.stock_receipt_ledger의 유니크 키를 source_record_id 단독에서
--      (source_record_id, item_id)로 바꿨다 — 입고 한 건에 품목이 여러 줄인 문서에서
--      두 번째 품목부터 on conflict do nothing에 걸려 영원히 누락되는 문제였다.


-- ══ 1. raw 적재 필드 보강 ═══════════════════════════════════════

alter table raw.inventory add column if not exists inventory_status text;
alter table raw.inventory add column if not exists snapshot_at timestamptz;
alter table raw.inventory add column if not exists warehouse_code text;

comment on column raw.inventory.inventory_status is
  '원본 재고상태 텍스트. core.inventory_scope_rule로 NORMAL 등 여섯 범위에 매핑한다';
comment on column raw.inventory.snapshot_at is
  '이 재고 수량을 확인한 시각. 없으면 정상 창고재고 분류에 포함하지 않는다';
comment on column raw.inventory.warehouse_code is
  '정규화된 창고 코드. null이면 창고 범위를 알 수 없어 분류에서 제외한다. 서비스센터·파트너처럼
   창고 자체가 범위를 정하는 경우 core.inventory_scope_rule의 창고전용 규칙과 매칭된다';

-- raw.goods_receipt 증가 원장 연결에 필요한 완료 상태 — "입고일" 컬럼은 이미 있다.
-- "완료일과 완료 상태가 모두 확인된 건" = 입고일이 채워져 있고 receipt_status가 COMPLETED인 건.
alter table raw.goods_receipt add column if not exists receipt_status text;

comment on column raw.goods_receipt.receipt_status is
  '입고 완료 상태. "입고일" + receipt_status=COMPLETED 두 조건을 모두 만족해야 참고 열에 반영한다';


-- ══ 2. 분류 규칙 ═════════════════════════════════════════════════
--
-- core.supplier_alias와 같은 alias → 정규코드 매핑 표다. 실데이터의 실제 표기가
-- 확인되면 이 표에 행을 더하기만 하면 된다 (기존 앱 코드는 바뀌지 않는다).
--
-- ★ fix round 1: raw_status 단독 PK였던 1차 구현을 (warehouse_code, raw_status) 조합으로
--   바꿨다. stage1 §6은 "검사 대기재고 · 불량 · 서비스센터 보유재고 · 파트너 보유재고 · 이동 중
--   재고"를 현재고에서 제외하라고 하는데, 서비스센터·파트너는 재고상태와 무관하게 그 창고에
--   있다는 사실만으로 범위가 정해질 수 있다. 두 열 모두 nullable이며(둘 중 하나는 필수),
--   더 구체적인 규칙이 우선한다: 창고+상태(둘 다 지정) > 창고전용(상태 null) > 상태전용(창고
--   null).
-- ★ fix round 2: 창고전용 규칙은 지금 하나도 시드하지 않는다. 실제 창고 표기를 아직 모르는
--   상태(메모리: 실데이터에 재고 없음)에서 예시 코드(SERVICE_CENTER · PARTNER)를 마스터
--   데이터처럼 심어 두면, 나중에 실제 창고 표기가 그 문자열과 우연히 겹칠 때 잘못 분류할
--   위험이 있다. 표·우선순위 로직·유니크 제약은 이미 창고전용 규칙을 지원하므로, 실제 표기가
--   확인되면 행만 추가하면 된다(docs/데이터-요청목록.md에 요청을 남겼다). 창고전용 규칙이
--   실제로 상태전용 규칙을 이기는지는 스크래치 DB에서만 임시로 행을 넣어 확인한다(아래
--   "확인 쿼리" 섹션 참고).

create table if not exists core.inventory_scope_rule (
  rule_id        bigint generated by default as identity primary key,
  warehouse_code text,
  raw_status     text,
  scope_code     text not null check (scope_code in (
    'NORMAL', 'INSPECTION', 'DEFECT', 'SERVICE_CENTER', 'PARTNER', 'IN_TRANSIT'
  )),
  description    text not null,
  created_at     timestamptz not null default now(),
  constraint inventory_scope_rule_key_required
    check (warehouse_code is not null or raw_status is not null)
);

-- 창고+상태 조합이 유일해야 모호한 매칭이 생기지 않는다. null끼리도 구분한다
-- (NULLS NOT DISTINCT) — 창고전용·상태전용 규칙이 같은 값으로 중복 등록되는 것도 막는다.
create unique index if not exists inventory_scope_rule_key_uq
  on core.inventory_scope_rule (warehouse_code, raw_status) nulls not distinct;

-- 상태전용 규칙만 시드한다(창고와 무관) — stage1 §6 용어를 그대로 옮긴 alias다. 창고전용
-- 규칙은 실제 창고 표기가 확인된 뒤 추가한다(위 fix round 2 설명 참고).
insert into core.inventory_scope_rule (warehouse_code, raw_status, scope_code, description) values
  (null, '정상',           'NORMAL',         '정상 창고재고'),
  (null, 'NORMAL',         'NORMAL',         '정상 창고재고'),
  (null, '검사대기',        'INSPECTION',     '검사 대기재고'),
  (null, '검사 대기',       'INSPECTION',     '검사 대기재고'),
  (null, 'INSPECTION',     'INSPECTION',     '검사 대기재고'),
  (null, '불량',           'DEFECT',         '불량·폐기 예정재고'),
  (null, '폐기예정',        'DEFECT',         '불량·폐기 예정재고'),
  (null, 'DEFECT',         'DEFECT',         '불량·폐기 예정재고'),
  (null, '서비스센터',       'SERVICE_CENTER', '서비스센터 보유재고'),
  (null, 'SERVICE_CENTER', 'SERVICE_CENTER', '서비스센터 보유재고'),
  (null, '파트너',          'PARTNER',        '파트너 보유재고'),
  (null, 'PARTNER',        'PARTNER',        '파트너 보유재고'),
  (null, '이동중',          'IN_TRANSIT',     '이동 중 재고'),
  (null, '이동 중',         'IN_TRANSIT',     '이동 중 재고'),
  (null, 'IN_TRANSIT',     'IN_TRANSIT',     '이동 중 재고')
on conflict (warehouse_code, raw_status) do nothing;

comment on table core.inventory_scope_rule is
  'stage1 §6 — (창고코드, 재고상태) 조합을 여섯 범위로 매핑. 둘 중 하나는 null일 수 있다.
   더 구체적인 규칙이 우선한다(core.classify_inventory_scope 참고). 매핑에 없는 조합은
   분류 불가로 제외한다';

-- 창고코드·재고상태 → 범위 코드. 가장 구체적인 규칙이 이긴다:
--   3순위(가장 구체적) 창고+상태 모두 일치
--   2순위             창고전용 규칙(그 창고는 상태와 무관하게 이 범위)
--   1순위             상태전용 규칙(그 상태는 창고와 무관하게 이 범위)
-- 매칭되는 규칙이 없으면 null — 분류 불가이며 core.stock_balance 계산에서 그 행을 제외한다.
create or replace function core.classify_inventory_scope(p_warehouse_code text, p_raw_status text)
returns text
language sql
stable
set search_path = core, pg_temp
as $$
  select r.scope_code
    from core.inventory_scope_rule r
   where (r.warehouse_code = p_warehouse_code or r.warehouse_code is null)
     and (r.raw_status = p_raw_status or r.raw_status is null)
   order by
     (case when r.warehouse_code is not null and r.raw_status is not null then 3
           when r.warehouse_code is not null then 2
           when r.raw_status is not null then 1
           else 0 end) desc,
     r.rule_id
   limit 1;
$$;

comment on function core.classify_inventory_scope(text, text) is
  '창고+상태 조합에서 가장 구체적인 core.inventory_scope_rule 행 하나를 고른다. 매칭이
   없으면 null(분류 불가)';

create table if not exists core.item_visibility_rule (
  raw_item_type    text primary key,
  visibility_scope text not null check (visibility_scope in (
    'PAPER_CARD_READER', 'CONSUMABLE', 'GENERAL'
  )),
  description      text not null,
  created_at       timestamptz not null default now()
);

insert into core.item_visibility_rule (raw_item_type, visibility_scope, description) values
  ('용지',          'PAPER_CARD_READER', '용지'),
  ('PAPER',         'PAPER_CARD_READER', '용지'),
  ('카드리더기',      'PAPER_CARD_READER', '카드리더기'),
  ('CARD_READER',   'PAPER_CARD_READER', '카드리더기'),
  ('소모품',         'CONSUMABLE',        '소모품'),
  ('CONSUMABLE',    'CONSUMABLE',        '소모품')
on conflict (raw_item_type) do nothing;

comment on table core.item_visibility_rule is
  'stage1 §2 — 품목구분을 조회 범위로 매핑. 매핑에 없는 품목구분은 GENERAL로 취급한다(제외하지 않는다)';


-- ══ 3. 확정 정상 창고재고 ═════════════════════════════════════════
--
-- ★ 이 배치가 담긴 품목만 갱신한다. 배치에 없는 기존 품목은 이전 확정값을 그대로 유지한다 —
--   즉 "품목별 최신값 누적"이며, 매번 raw.inventory 전체를 다시 계산하는 전체 스냅샷이
--   아니다(리뷰에서 지적된 deferred 항목 — 지금은 이 동작을 바꾸지 않고 사실만 적어 둔다).
--
-- ★ fix round 2: normal_qty를 두 부분으로 나눠서 관리한다.
--   snapshot_qty  최근 반영된 inventory 배치에서 NORMAL로 분류된 실사 수량 그 자체.
--   normal_qty    화면·뷰가 실제로 읽는 값. snapshot_qty + "그 스냅샷 시각 이후 완료된 입고
--                 합"이다 — raw.goods_receipt는 "창고 입고 완료일과 완료 상태가 모두
--                 확인된 건만 stock_balance 증가 원장으로 연결한다"(brief 원문)는 요구를
--                 이렇게 만족한다. 새 실사 스냅샷이 들어오면 그 시점 이전 입고는 이미 실사에
--                 잡혔다고 보고 더 이상 더하지 않는다(중복 계산 방지).

create table if not exists core.stock_balance (
  item_id         text primary key,
  snapshot_qty    numeric not null default 0 check (snapshot_qty >= 0),
  normal_qty      numeric not null default 0 check (normal_qty >= 0),
  snapshot_at     timestamptz,
  source_batch_id uuid references core.upload_batch(batch_id) on delete set null,
  updated_at      timestamptz not null default now()
);

-- 이미 1차 구현을 적용해 본 DB에서도 컬럼만 보강한다(운영 반영 전이라 실제로는 없을 것이다).
alter table core.stock_balance add column if not exists snapshot_qty numeric not null default 0;

comment on table core.stock_balance is
  '품목별 확정 정상 창고재고. Task 5의 배정 함수가 FOR UPDATE로 잠그는 행이다. '
  '분류 가능한 raw.inventory 행이 하나도 없는 품목은 이 표에 올리지 않는다 '
  '(0이 아니라 "아직 모른다"를 뜻하기 때문이다). 이 배치에 없는 품목은 갱신하지 않는다 — '
  '품목별 최신값 누적이며 전체 재계산이 아니다';
comment on column core.stock_balance.snapshot_qty is
  '최근 반영된 inventory 배치에서 NORMAL로 분류된 실사 수량. 입고 반영 전 기준값이다';
comment on column core.stock_balance.normal_qty is
  '화면·뷰가 읽는 정상 창고재고. snapshot_qty + snapshot_at 이후 완료된
   core.stock_receipt_ledger 합. core.recompute_stock_balance_totals가 계산한다';
comment on column core.stock_balance.snapshot_at is
  'NORMAL로 분류된 행만의 최신 확인 시각. 그 배치에 NORMAL 행이 하나도 없으면(정상재고
   0건이 확인됨) null일 수 있다 — normal_qty=0이어도 "언제 확인했는지"는 모를 수 있다';

-- 완료된 입고를 반영한 append-only 원장. 같은 입고 건(source_record_id, item_id 조합)은
-- 한 번만 반영된다(유니크 제약 + on conflict do nothing) — 배치를 다시 커밋하거나 재반영을
-- 여러 번 호출해도 이중 계산되지 않는다. 행을 지우거나 고치지 않는다 — 반영 시점의 사실을
-- 그대로 남긴다.
--
-- ★ fix round 3: 유니크 키를 source_record_id 단독에서 (source_record_id, item_id)로
--   바꿨다. 입고 한 건(입고번호)에 품목이 여러 줄로 딸린 ERP 문서가 흔한데, source_record_id
--   단독 유니크였다면 같은 입고번호의 두 번째 품목부터는 on conflict do nothing에 걸려
--   영원히 누락됐다. raw.goods_receipt 자체의 문제는 아래 core.commit_import_batch 확장
--   설명에 남겨 뒀다 — 이번 라운드에서 STEP 4의 raw 적재 키는 바꾸지 않는다.
create table if not exists core.stock_receipt_ledger (
  ledger_id         bigint generated by default as identity primary key,
  item_id           text not null,
  source_record_id  text not null,
  qty               numeric not null check (qty > 0),
  completed_at      timestamptz not null,
  source_batch_id   uuid references core.upload_batch(batch_id) on delete set null,
  applied_at        timestamptz not null default now()
);

-- 1차 구현(fix round 2)의 source_record_id 단독 유니크 인덱스를 대체한다.
drop index if exists core.stock_receipt_ledger_source_uq;
create unique index if not exists stock_receipt_ledger_source_item_uq
  on core.stock_receipt_ledger (source_record_id, item_id);
create index if not exists stock_receipt_ledger_item_idx
  on core.stock_receipt_ledger (item_id, completed_at);

comment on table core.stock_receipt_ledger is
  '완료된 입고가 정상 창고재고를 늘린 append-only 이력. (source_record_id, item_id) 조합당
   한 행만 존재한다 — 같은 입고번호에 품목이 여러 줄이어도 품목별로 각각 반영된다.
   core.recompute_stock_balance_totals가 이 표를 읽어 core.stock_balance.normal_qty를 다시
   계산한다 — 이 표 자체는 절대 update·delete하지 않는다(감사 이력)';

-- item_id별로 normal_qty = snapshot_qty + (snapshot_at 이후 완료된 입고 합)을 다시 계산한다.
-- 스냅샷이 새로 들어오면(snapshot_at이 갱신되면) 그 이전 입고는 자동으로 빠진다 — 이미 실사에
-- 반영됐다고 보기 때문이다(원장 행 자체는 지우지 않는다). snapshot_at이 null이면(그 배치에
-- NORMAL 행이 없었다는 뜻) 모든 완료 입고를 더한다 — 배제할 근거 시각이 없기 때문이다.
create or replace function core.recompute_stock_balance_totals(p_item_ids text[])
returns void
language sql
security definer
set search_path = core, public, pg_temp
as $$
  update core.stock_balance sb
     set normal_qty = sb.snapshot_qty + coalesce((
           select sum(l.qty)
             from core.stock_receipt_ledger l
            where l.item_id = sb.item_id
              and l.completed_at > coalesce(sb.snapshot_at, '-infinity'::timestamptz)
         ), 0),
         updated_at = now()
   where sb.item_id = any(p_item_ids);
$$;

comment on function core.recompute_stock_balance_totals(text[]) is
  '내부 전용. snapshot_qty + 완료 입고 합으로 normal_qty를 다시 계산한다. 새 스냅샷이나
   새 완료 입고가 반영된 직후 영향받은 item_id 목록으로 호출한다';

-- 권한 검사가 없는 순수 계산. core.refresh_stock_balance(수동 재반영, 권한 검사 있음)와
-- core.commit_import_batch(정상 커밋 경로 — 그 함수가 이미 관리자 전용)가 이 함수를 부른다.
-- 같은 SQL을 두 곳에 복사해 두면 언젠가 갈라지므로 계산 로직은 여기 한 곳에만 둔다.
create or replace function core.apply_stock_balance_from_batch(p_batch_id uuid)
returns integer
language plpgsql
security definer
set search_path = core, public, pg_temp
as $$
declare
  v_count integer;
  v_item_ids text[];
begin
  with classified as (
    -- 상태나 창고 범위를 분류할 수 없는 행은 여기서 완전히 제외한다 — 0으로도, NORMAL로도
    -- 세지 않는다. warehouse_code가 없으면(창고 범위 미상) 분류 함수를 부르지 않고 바로
    -- 제외한다. inventory_status가 매핑되지 않아도(core.classify_inventory_scope가 null을
    -- 돌려주면) 다음 CTE에서 제외된다.
    select
      upper(regexp_replace(i."품목코드", '[\s\-_]', '', 'g')) as item_id,
      nullif(i."현재고", '')::numeric as qty,
      i.snapshot_at,
      core.classify_inventory_scope(i.warehouse_code, i.inventory_status) as scope_code
    from raw.inventory i
    where i.batch_id = p_batch_id
      and i.warehouse_code is not null
      and nullif(i."현재고", '') is not null
      and i.snapshot_at is not null
  ),
  classified_only as (
    select * from classified where scope_code is not null
  ),
  aggregated as (
    select
      item_id,
      coalesce(sum(qty) filter (where scope_code = 'NORMAL'), 0) as snapshot_qty,
      max(snapshot_at) filter (where scope_code = 'NORMAL') as snapshot_at
    from classified_only
    group by item_id
  ),
  upserted as (
    insert into core.stock_balance (item_id, snapshot_qty, normal_qty, snapshot_at, source_batch_id, updated_at)
    select item_id, snapshot_qty, snapshot_qty, snapshot_at, p_batch_id, now()
      from aggregated
    on conflict (item_id) do update
      set snapshot_qty    = excluded.snapshot_qty,
          snapshot_at     = excluded.snapshot_at,
          source_batch_id = excluded.source_batch_id,
          updated_at      = now()
    returning item_id
  )
  select array_agg(item_id) into v_item_ids from upserted;

  v_count := coalesce(array_length(v_item_ids, 1), 0);

  -- 새 스냅샷이 실린 품목은 그 스냅샷 시각을 기준으로 완료 입고 합을 다시 계산한다. 이전에
  -- 반영됐던 입고 중 새 스냅샷 시각보다 이르면 이번 실사에 이미 잡혔다고 보고 제외된다.
  if v_item_ids is not null then
    perform core.recompute_stock_balance_totals(v_item_ids);
  end if;

  return v_count;
end;
$$;

comment on function core.apply_stock_balance_from_batch(uuid) is
  '권한 검사가 없는 내부 계산. 배치 상태·타입 확인은 호출자의 책임이다. authenticated에
   직접 노출하지 않는다 — core.refresh_stock_balance와 core.commit_import_batch를 거친다';

-- 완료된 입고 배치를 core.stock_receipt_ledger에 반영하고 영향받은 품목의 normal_qty를
-- 다시 계산한다. 권한 검사가 없는 순수 계산 — core.commit_import_batch(이미 관리자 전용)만
-- 부른다.
--
-- ★ 원장에는 조건 없이 기록한다 — core.stock_balance 행이 아직 없는 품목의 완료 입고도
--   원장에는 남긴다(감사 이력은 입고 순서와 무관해야 한다). 다만 core.recompute_stock_balance_totals는
--   core.stock_balance에 이미 행이 있는 품목만 갱신하므로(그 UPDATE가 대상 행이 없으면
--   아무 일도 하지 않는다), 실사 스냅샷이 한 번도 없던 품목의 기준선을 입고만으로
--   추정하지 않는다는 원칙은 그대로 지켜진다. 나중에 그 품목의 실사 스냅샷이 들어오면,
--   이미 원장에 있는 입고 중 그 스냅샷 시각 이후인 것이 그때 자동으로 반영된다 — 입고가
--   스냅샷보다 먼저 들어와도 값이 사라지지 않는다.
create or replace function core.apply_stock_receipts_from_batch(p_batch_id uuid)
returns integer
language plpgsql
security definer
set search_path = core, public, pg_temp
as $$
declare
  v_count integer;
  v_item_ids text[];
begin
  with completed as (
    -- "창고 입고 완료일과 완료 상태가 모두 확인된 건" = 입고일이 있고 receipt_status가
    -- COMPLETED인 건. 그 밖(미완료·상태 미상)은 여기서 제외되며 0으로도 세지 않는다.
    -- ★ fix round 3: 수량이 0(또는 그 이하)인 완료 입고도 여기서 제외한다.
    --   lib/import/validate.ts는 음수만 막고 0은 통과시키므로, 0 수량 COMPLETED 행이 그대로
    --   core.stock_receipt_ledger에 들어가면 그 표의 qty > 0 체크에 걸려 예외가 나고
    --   commit_import_batch 트랜잭션 전체가 롤백된다(그 배치의 다른 정상 입고까지 함께
    --   사라진다). 수량 0인 입고는 잔액을 바꾸지 않으므로 원장에 남기지 않아도 정확하다.
    select
      upper(regexp_replace(g."품목코드", '[\s\-_]', '', 'g')) as item_id,
      nullif(g."입고수량", '')::numeric as qty,
      nullif(g."입고일", '')::timestamptz as completed_at,
      g.source_record_id
    from raw.goods_receipt g
    where g.batch_id = p_batch_id
      and g.receipt_status = 'COMPLETED'
      and nullif(g."입고일", '') is not null
      and nullif(g."입고수량", '') is not null
      and nullif(g."입고수량", '')::numeric > 0
      and g.source_record_id is not null
  ),
  inserted as (
    -- ★ fix round 3: (source_record_id, item_id) 조합으로 conflict를 판정한다. 같은
    --   입고번호에 품목이 여러 줄이면 품목마다 각각 반영된다(위 표 코멘트 참고).
    insert into core.stock_receipt_ledger (item_id, source_record_id, qty, completed_at, source_batch_id)
    select item_id, source_record_id, qty, completed_at, p_batch_id
      from completed
    on conflict (source_record_id, item_id) do nothing
    returning item_id
  )
  select array_agg(distinct item_id) into v_item_ids from inserted;

  v_count := coalesce(array_length(v_item_ids, 1), 0);

  -- core.stock_balance에 아직 행이 없는 품목은 이 호출이 그냥 건너뛴다(update 대상 0행).
  if v_item_ids is not null then
    perform core.recompute_stock_balance_totals(v_item_ids);
  end if;

  return v_count;
end;
$$;

comment on function core.apply_stock_receipts_from_batch(uuid) is
  '권한 검사가 없는 내부 계산. core.commit_import_batch(goods_receipt 분기)만 부른다.
   같은 (source_record_id, item_id) 조합은 두 번 반영되지 않는다(유니크 제약). 수량 0인
   완료 입고는 원장에 넣지 않는다. 원장에는 조건 없이 기록하고, core.stock_balance 반영
   여부는 core.recompute_stock_balance_totals가 정한다';

create or replace function core.refresh_stock_balance(p_batch_id uuid)
returns integer
language plpgsql
security definer
set search_path = core, public, pg_temp
as $$
declare
  v_actor uuid := auth.uid();
  v_batch core.upload_batch%rowtype;
begin
  if v_actor is null or not core.is_active_user(v_actor) then
    raise exception '로그인한 활성 사용자만 재고 배치를 반영할 수 있습니다.' using errcode = '42501';
  end if;

  -- 정상 창고재고 반영은 STOCK_VIEW_ALL 권한을 가진 SCM 담당자(SCM_PLANNER · SCM_LEAD)만
  -- 할 수 있다. 전용 권한 코드를 새로 만들지 않고 기존 재고 전체 조회 권한을 재사용한다.
  if not (core.has_permission('STOCK_VIEW_ALL', v_actor) or core.is_admin(v_actor)) then
    raise exception '정상 창고재고 반영 권한이 없습니다.' using errcode = '42501';
  end if;

  select * into v_batch from core.upload_batch where batch_id = p_batch_id;
  if not found then
    raise exception '재고 배치를 찾을 수 없습니다: %', p_batch_id using errcode = 'P0002';
  end if;
  if v_batch.import_type <> 'inventory' then
    raise exception 'inventory 배치만 정상 창고재고에 반영할 수 있습니다.' using errcode = '22023';
  end if;
  if v_batch.status not in ('VALIDATED', 'IMPORTED') then
    raise exception '검증 완료된 배치만 반영할 수 있습니다. 현재 상태: %', v_batch.status using errcode = '22023';
  end if;

  return core.apply_stock_balance_from_batch(p_batch_id);
end;
$$;

comment on function core.refresh_stock_balance(uuid) is
  'SCM 담당자가 수동으로 다시 반영할 때 쓴다. 정상 경로는 core.commit_import_batch가 커밋
   직후 자동으로 core.apply_stock_balance_from_batch를 부르므로 보통 다시 호출할 필요가
   없다(분류 규칙을 나중에 고쳤을 때 재반영하는 용도). 검증 완료된(VALIDATED 이상)
   inventory 배치만 반영한다';


-- ══ 3-1. Open PO 참고 열 ═══════════════════════════════════════════
--
-- ★ core.v_inbound_qty · core.v_stock_on_hand와 같은 자리의 뷰다. authenticated는 raw
--   테이블에 직접 GRANT가 없으므로(SCHEMA.md), security_invoker 분석 뷰가 raw를 직접
--   참조하면 permission denied가 난다. raw 집계는 항상 이런 소유자 권한 core 뷰를 한 번
--   거친 뒤 analytics 뷰가 그 결과만 읽는다.
-- ★ "창고 입고 완료" = 입고일이 있고 receipt_status가 COMPLETED인 건만 발주잔량 계산에
--   넣는다(stage1 §6). 발주 자체가 없는 품목은 미상이 아니라 0건이 사실이므로 0을 쓴다.

create or replace view core.v_open_po_qty as
with ordered as (
  select
    upper(regexp_replace(p."품목코드", '[\s\-_]', '', 'g')) as item_id,
    sum(nullif(p."발주수량", '')::numeric) as ordered_qty
  from raw.purchase_order p
  group by upper(regexp_replace(p."품목코드", '[\s\-_]', '', 'g'))
),
received as (
  select
    upper(regexp_replace(g."품목코드", '[\s\-_]', '', 'g')) as item_id,
    sum(nullif(g."입고수량", '')::numeric) as received_qty
  from raw.goods_receipt g
  where nullif(g."입고일", '') is not null
    and g.receipt_status = 'COMPLETED'
  group by upper(regexp_replace(g."품목코드", '[\s\-_]', '', 'g'))
)
select
  o.item_id,
  greatest(0, o.ordered_qty - coalesce(r.received_qty, 0)) as open_po_qty
from ordered o
left join received r on r.item_id = o.item_id;

comment on view core.v_open_po_qty is
  '품목별 Open PO 참고 수량 = 발주수량 합 - 입고완료(입고일 존재 + receipt_status=COMPLETED) 합. '
  '음수는 0으로 clamp한다. 가용재고 계산에는 더하지 않는 참고 열이다';

grant select on core.v_open_po_qty to authenticated;
revoke all on core.v_open_po_qty from anon, public;


-- ══ 3-2. 정상 임포트 경로에 자동 반영 연결 ═══════════════════════════
--
-- STEP 4(20260828000300_step4_import_pipeline.sql)의 core.commit_import_batch를 다시
-- 정의한다. 기존 모든 분기를 그대로 두고 두 가지만 더한다.
--   1) inventory · goods_receipt 커밋 payload에 Task 4 신규 컬럼을 포함시킨다. 이전에는
--      inventory_status · warehouse_code · snapshot_at · receipt_status가 raw에 전혀
--      실리지 않아, 화면의 정식 업로드 경로로 적재한 재고는 영원히 UNCLASSIFIED로 남았다.
--   2) inventory 배치를 성공적으로 적재한 직후, 같은 트랜잭션 안에서
--      core.apply_stock_balance_from_batch를 호출해 정상 창고재고(스냅샷 기준값)를
--      자동으로 반영한다.
--   3) (fix round 2) goods_receipt 배치를 성공적으로 적재한 직후, 같은 트랜잭션 안에서
--      core.apply_stock_receipts_from_batch를 호출해 완료된 입고를
--      core.stock_receipt_ledger에 기록하고 정상 창고재고를 늘린다.
-- core.commit_import_batch는 이미 함수 맨 위에서 core.is_admin()을 요구하므로 두 호출 모두
-- 별도 권한 검사를 추가하지 않는다. 스냅샷과 입고 이중 계산은 core.recompute_stock_balance_totals가
-- "그 스냅샷 시각 이후 완료 입고만" 더해서 막는다(core.stock_balance 코멘트 참고).
--
-- ★ 주의 — 이 함수는 Task 12(20260911001150)에서 한 번 더 재정의된다(월말 스냅샷 호출 추가).
--   파일명 순서상 그쪽이 최종본이므로, 이 본문을 고치면 20260911001150의 정의도 반드시 같이
--   고쳐야 한다. 그러지 않으면 여기 수정이 뒤 파일 정의에 덮여 사라진다(2026-09-12에 실제로 겪음).

create or replace function core.commit_import_batch(p_batch_id uuid)
returns void language plpgsql security definer set search_path = core, raw, pg_temp as $$
declare b core.upload_batch%rowtype; table_name text; r record; payload jsonb;
begin
  if not core.is_admin() then raise exception '관리자 권한이 필요합니다.' using errcode='42501'; end if;
  select * into b from core.upload_batch where batch_id=p_batch_id for update;
  if not found or b.status <> 'VALIDATED' or b.error_rows > 0 then raise exception '검증 완료 및 오류 0건인 batch만 적재할 수 있습니다.' using errcode='22023'; end if;
  table_name := core.import_target_table(b.import_type); if table_name is null then raise exception '지원하지 않는 Import Type입니다.'; end if;
  if b.import_mode='replace' then execute format('insert into core.import_row_backup(batch_id,target_table,row_data,backup_reason) select $1,$2,to_jsonb(t),''REPLACE'' from raw.%I t',table_name) using p_batch_id,table_name; execute format('delete from raw.%I',table_name); end if;
  for r in select row_number,mapped_data from core.import_staging where batch_id=p_batch_id and validation_status in ('SUCCESS','WARNING') order by row_number loop
    payload := r.mapped_data || jsonb_build_object('batch_id',p_batch_id,'source_type','FILE_UPLOAD','loaded_at',now(),'source_record_id',coalesce(r.mapped_data->>'source_record_id',r.row_number::text));
    if b.import_type='inventory' then payload := jsonb_build_object('품목코드',payload->>'item_id','창고',payload->>'warehouse','현재고',payload->>'current_stock','기준일자',payload->>'reference_date','안전재고',payload->>'safety_stock','inventory_status',payload->>'inventory_status','warehouse_code',payload->>'warehouse_code','snapshot_at',payload->>'snapshot_at','batch_id',p_batch_id,'source_type','FILE_UPLOAD','loaded_at',now(),'source_record_id',payload->>'source_record_id');
    elsif b.import_type='item_master' then payload := jsonb_build_object('품목코드',payload->>'item_id','품목명',payload->>'item_name','품목구분',payload->>'item_type','단위',payload->>'unit','supplier_id',payload->>'supplier_id','batch_id',p_batch_id,'source_type','FILE_UPLOAD','loaded_at',now(),'source_record_id',payload->>'source_record_id');
    elsif b.import_type='supplier_master' then payload := jsonb_build_object('공급업체코드',payload->>'supplier_id','공급업체명',payload->>'supplier_name','국가',payload->>'country','batch_id',p_batch_id,'source_type','FILE_UPLOAD','loaded_at',now(),'source_record_id',payload->>'source_record_id');
    elsif b.import_type='purchase_order' then payload := jsonb_build_object('발주번호',payload->>'source_record_id','발주일',payload->>'order_date','공급업체',payload->>'supplier_id','품목코드',payload->>'item_id','발주수량',payload->>'qty','batch_id',p_batch_id,'source_type','FILE_UPLOAD','loaded_at',now(),'source_record_id',payload->>'source_record_id');
    elsif b.import_type='goods_receipt' then payload := jsonb_build_object('입고번호',payload->>'source_record_id','품목코드',payload->>'item_id','입고수량',payload->>'qty','입고일',payload->>'receipt_date','receipt_status',payload->>'receipt_status','batch_id',p_batch_id,'source_type','FILE_UPLOAD','loaded_at',now(),'source_record_id',payload->>'source_record_id'); end if;
    if b.import_mode='upsert' then
      -- ★ (Task 4 후속 수정) 입고 · 발주는 한 문서번호에 품목이 여러 줄이다. source_record_id
      --   하나만 키로 삭제하면 같은 입고번호 · 발주번호의 앞 줄이 뒤 줄을 적재할 때마다 지워져
      --   마지막 품목만 raw에 남는다(core.v_open_po_qty의 발주 · 입고 수량이 함께 과소 계상됐다).
      --   이 두 유형은 (source_record_id, 품목코드)가 행의 실제 식별자다 — core.stock_receipt_ledger의
      --   유니크 키와 같은 기준이다. 나머지 유형은 문서번호 하나가 곧 한 행이라 기존 동작 그대로 둔다.
      if b.import_type in ('goods_receipt','purchase_order') then
        execute format('insert into core.import_row_backup(batch_id,target_table,row_data,backup_reason) select $1,$2,to_jsonb(t),''UPSERT'' from raw.%I t where t.source_type=''FILE_UPLOAD'' and t.source_record_id=$3 and t."품목코드" is not distinct from $4',table_name) using p_batch_id,table_name,payload->>'source_record_id',payload->>'품목코드';
        execute format('delete from raw.%I where source_type=''FILE_UPLOAD'' and source_record_id=$1 and "품목코드" is not distinct from $2',table_name) using payload->>'source_record_id',payload->>'품목코드';
      else
        execute format('insert into core.import_row_backup(batch_id,target_table,row_data,backup_reason) select $1,$2,to_jsonb(t),''UPSERT'' from raw.%I t where t.source_type=''FILE_UPLOAD'' and t.source_record_id=$3',table_name) using p_batch_id,table_name,payload->>'source_record_id';
        execute format('delete from raw.%I where source_type=''FILE_UPLOAD'' and source_record_id=$1',table_name) using payload->>'source_record_id';
      end if;
    end if;
    execute format('insert into raw.%I select * from jsonb_populate_record(null::raw.%I,$1)',table_name,table_name) using payload;
  end loop;
  update core.upload_batch set status='IMPORTED', imported_at=now(), forecast_stale_marked=b.import_type in ('usage_history','sales_order','business_event') where batch_id=p_batch_id;
  if b.import_type in ('usage_history','sales_order','business_event') and to_regclass('core.forecast_run') is not null then execute 'update core.forecast_run set stale_at=now() where data_snapshot_at < now() and stale_at is null'; end if;
  if b.import_type = 'inventory' then perform core.apply_stock_balance_from_batch(p_batch_id);
  elsif b.import_type = 'goods_receipt' then perform core.apply_stock_receipts_from_batch(p_batch_id); end if;
end; $$;

comment on function core.commit_import_batch(uuid) is
  'STEP 4 원본 + Task 4 확장: inventory·goods_receipt payload에 재고 분류 컬럼을 포함하고,
   inventory 배치 적재 직후 core.apply_stock_balance_from_batch를, goods_receipt 배치
   적재 직후 core.apply_stock_receipts_from_batch를 같은 트랜잭션에서 호출한다';

-- create or replace는 기존 GRANT를 지우지 않지만, 재적용 순서가 바뀌어도 항상 맞는 상태가
-- 되도록 명시적으로 다시 선언한다(STEP 4의 grant와 동일).
grant execute on function core.commit_import_batch(uuid) to authenticated;
revoke execute on function core.commit_import_batch(uuid) from anon, public;


-- ══ 4. 가용재고 뷰 ════════════════════════════════════════════════
--
-- available_qty = normal_warehouse_qty - temporary_allocated_qty - firm_allocated_qty
--               - approval_hold_qty
--
-- ★ temporary_allocated_qty · firm_allocated_qty · approval_hold_qty는 지금 0으로 고정한다.
--   core.stock_allocation(Task 5)이 아직 없기 때문이다 — 지금은 배정 이력이 0건이라는
--   것이 사실 그대로이므로 0은 추정이 아니다. Task 5는 이 뷰를 create or replace로
--   확장하되, 기존 열 순서는 그대로 두고 끝에 덧붙인다(error.md #16).
-- ★ open_po_qty · in_transit_qty는 참고 열이며 available_qty 계산에 더하지 않는다.
-- ★ fix round 1: ATP_VIEW만으로는 이 상세 뷰를 볼 수 없다. 영업은 재고 상세(배정 내역 ·
--   Open PO · 이동 중 · 스냅샷)를 보면 안 되고, 실제 주문 가능 수량만 봐야 한다
--   (stage1 §2). ATP 전용 조회는 analytics.v_order_available_stock을 따로 쓴다.

create or replace view analytics.v_available_stock
with (security_invoker = true)
as
select
  im.item_id,
  im.item_name,
  im.item_type,
  coalesce(ivr.visibility_scope, 'GENERAL') as visibility_scope,
  sb.normal_qty as normal_warehouse_qty,
  sb.snapshot_at,
  0::numeric as temporary_allocated_qty,
  0::numeric as firm_allocated_qty,
  0::numeric as approval_hold_qty,
  case when sb.normal_qty is null then null
       else sb.normal_qty - 0::numeric - 0::numeric - 0::numeric
  end as available_qty,
  po.open_po_qty,
  ib.inbound_qty as in_transit_qty,
  case when sb.item_id is null then 'INVENTORY_SCOPE_UNCLASSIFIED' end as reason_code
from core.v_item_master im
left join core.item_visibility_rule ivr on ivr.raw_item_type = im.item_type
left join core.stock_balance sb on sb.item_id = im.item_id
left join core.v_inbound_qty ib on ib.item_id = im.item_id
left join core.v_open_po_qty po on po.item_id = im.item_id
where
  -- 마케팅은 용지·카드리더기, 서비스는 소모품, SCM(STOCK_VIEW_ALL)은 전체. 영업(ATP_VIEW)은
  -- 여기 포함하지 않는다 — analytics.v_order_available_stock만 본다.
  core.has_permission('STOCK_VIEW_ALL')
  or (core.has_permission('STOCK_VIEW_PAPER') and coalesce(ivr.visibility_scope, 'GENERAL') = 'PAPER_CARD_READER')
  or (core.has_permission('STOCK_VIEW_SUPPLY') and coalesce(ivr.visibility_scope, 'GENERAL') = 'CONSUMABLE');

comment on view analytics.v_available_stock is
  'Task 4 — 부서 권한과 품목 범위로 제한한 정상 창고재고·가용재고 상세. security_invoker로 '
  '호출자 RLS를 그대로 적용한다. ATP_VIEW 전용 사용자는 이 뷰를 보지 않는다(v_order_available_stock 참고). '
  '분류 불가 품목은 null + INVENTORY_SCOPE_UNCLASSIFIED';


-- ══ 4-1. 영업 전용 주문 가능 수량 뷰 ═══════════════════════════════
--
-- ★ ATP_VIEW만 가진 사용자(영업담당자)는 재고 상세를 보면 안 되고 실제 주문 가능 수량만
--   본다(stage1 §2, 계획서 Task 11 "정상재고에서 모든 배정·hold를 차감한 주문 가능 수량").
-- ★ 열은 최소로 고정한다 — item_id · item_name · available_qty · reason_code. Task 5가
--   같은 뷰를 create or replace로 확장할 것이므로 이름과 순서를 여기서 고정해 둔다
--   (기존 열 중간에 끼워 넣지 않는다, error.md #16).

create or replace view analytics.v_order_available_stock
with (security_invoker = true)
as
select
  im.item_id,
  im.item_name,
  case when sb.normal_qty is null then null
       else sb.normal_qty - 0::numeric - 0::numeric - 0::numeric
  end as available_qty,
  case when sb.item_id is null then 'INVENTORY_SCOPE_UNCLASSIFIED' end as reason_code
from core.v_item_master im
left join core.stock_balance sb on sb.item_id = im.item_id
where core.has_permission('ATP_VIEW');

comment on view analytics.v_order_available_stock is
  'Task 4 — 영업(ATP_VIEW) 전용 주문 가능 수량. 재고 상세(배정 내역 · Open PO · 이동 중 ·
   스냅샷)는 노출하지 않는다. 열 이름은 Task 5가 확장할 때까지 고정한다';


-- ══ 5. RLS와 권한 ════════════════════════════════════════════════

alter table core.inventory_scope_rule  enable row level security;
alter table core.item_visibility_rule  enable row level security;
alter table core.stock_balance         enable row level security;
alter table core.stock_receipt_ledger  enable row level security;

drop policy if exists inventory_scope_rule_read on core.inventory_scope_rule;
drop policy if exists inventory_scope_rule_write on core.inventory_scope_rule;
create policy inventory_scope_rule_read on core.inventory_scope_rule
  for select to authenticated using (true);
create policy inventory_scope_rule_write on core.inventory_scope_rule
  for all to authenticated using (core.is_admin()) with check (core.is_admin());

drop policy if exists item_visibility_rule_read on core.item_visibility_rule;
drop policy if exists item_visibility_rule_write on core.item_visibility_rule;
create policy item_visibility_rule_read on core.item_visibility_rule
  for select to authenticated using (true);
create policy item_visibility_rule_write on core.item_visibility_rule
  for all to authenticated using (core.is_admin()) with check (core.is_admin());

drop policy if exists stock_balance_read on core.stock_balance;
create policy stock_balance_read on core.stock_balance
  for select to authenticated
  using (
    core.has_permission('STOCK_VIEW_ALL')
    or core.has_permission('ATP_VIEW')
    or core.has_permission('STOCK_VIEW_PAPER')
    or core.has_permission('STOCK_VIEW_SUPPLY')
    or core.is_admin()
  );

drop policy if exists stock_receipt_ledger_read on core.stock_receipt_ledger;
create policy stock_receipt_ledger_read on core.stock_receipt_ledger
  for select to authenticated
  using (
    core.has_permission('STOCK_VIEW_ALL')
    or core.has_permission('ATP_VIEW')
    or core.has_permission('STOCK_VIEW_PAPER')
    or core.has_permission('STOCK_VIEW_SUPPLY')
    or core.is_admin()
  );

revoke all on core.inventory_scope_rule, core.item_visibility_rule, core.stock_balance, core.stock_receipt_ledger from anon, public;
revoke insert, update, delete on core.stock_balance, core.stock_receipt_ledger from authenticated;
grant select on core.stock_balance, core.stock_receipt_ledger to authenticated;
grant select, insert, update, delete on core.inventory_scope_rule, core.item_visibility_rule to authenticated;
grant select on analytics.v_available_stock, analytics.v_order_available_stock to authenticated;
revoke all on analytics.v_available_stock, analytics.v_order_available_stock from anon, public;

revoke all on function core.refresh_stock_balance(uuid) from public, anon;
grant execute on function core.refresh_stock_balance(uuid) to authenticated;

-- 내부 전용 — authenticated에도 직접 실행 권한을 주지 않는다. commit_import_batch ·
-- refresh_stock_balance가 SECURITY DEFINER로 내부에서만 부른다.
revoke all on function core.apply_stock_balance_from_batch(uuid) from public, anon, authenticated;
revoke all on function core.apply_stock_receipts_from_batch(uuid) from public, anon, authenticated;
revoke all on function core.recompute_stock_balance_totals(text[]) from public, anon, authenticated;

revoke all on function core.classify_inventory_scope(text, text) from public, anon;
grant execute on function core.classify_inventory_scope(text, text) to authenticated;


-- ══ 6. 수동 적용 후 확인 쿼리 ═══════════════════════════════════

-- (a) 검사대기 10 · 정상 20 · 이동 중 30 → 정상 창고재고 20 (직접 raw insert로 단위 확인)
-- insert into raw.inventory ("품목코드","현재고",inventory_status,warehouse_code,snapshot_at,batch_id,source_type)
-- values
--   ('ITEM901','10','검사대기','MAIN',now(),'<검증용 batch_id>','FILE_UPLOAD'),
--   ('ITEM901','20','정상','MAIN',now(),'<검증용 batch_id>','FILE_UPLOAD'),
--   ('ITEM901','30','이동중','MAIN',now(),'<검증용 batch_id>','FILE_UPLOAD');
-- select core.refresh_stock_balance('<검증용 batch_id>');
-- select item_id, normal_qty from core.stock_balance where item_id = 'ITEM901';
-- 기대: normal_qty = 20

-- (a-1) 같은 시나리오를 정식 경로(staging → commit_import_batch)로 실행 — 앱이 실제로
-- 쓰는 경로다. import_staging.mapped_data에 inventory_status·warehouse_code·snapshot_at를
-- 넣고 commit_import_batch를 부르면, 별도로 refresh_stock_balance를 부르지 않아도
-- core.stock_balance가 채워져야 한다.

-- (a-2) 창고 규칙이 상태를 이기는지 확인. 창고전용 규칙은 운영 시드에 없으므로(실제 창고
-- 표기를 아직 모른다) 이 확인은 임시로 행을 넣고 지운다 — SQL Editor에서만 실행한다.
-- begin;
--   insert into core.inventory_scope_rule (warehouse_code, raw_status, scope_code, description)
--   values ('SERVICE_CENTER', null, 'SERVICE_CENTER', '검증용 임시 규칙');
--   select core.classify_inventory_scope('SERVICE_CENTER', '정상') as scope_code;
--   -- 기대: SERVICE_CENTER (NORMAL이 아니다 — 상태전용 규칙보다 창고전용 규칙이 이긴다)
-- rollback;

-- (a-3) 완료된 입고가 정상 창고재고를 늘리는지 확인 (fix round 2)
--   ① 정상 20 스냅샷(T0) 반영 → normal_qty=20
--   ② 같은 품목에 완료(COMPLETED) 입고 5, 완료 시각 T1(T1 > T0) 커밋 → normal_qty=25
--   ③ 같은 배치를 다시 반영해도(refresh_stock_balance 재호출 등) → normal_qty=25 그대로
--      (core.stock_receipt_ledger가 (source_record_id, item_id) 조합당 한 번만 반영한다)
--   ④ 입고가 COMPLETED가 아니면 → normal_qty=20 그대로 (반영되지 않는다)
--   ⑤ 새 스냅샷 30, 시각 T2(T2 > T1) 반영 → normal_qty=30 (T1 입고는 이미 실사에
--      포함됐다고 보고 다시 더하지 않는다)
select item_id, snapshot_qty, normal_qty, snapshot_at from core.stock_balance order by item_id;
select item_id, source_record_id, qty, completed_at from core.stock_receipt_ledger order by applied_at;

-- (a-4) 수량 0인 완료 입고가 배치 전체를 롤백시키지 않는지 확인 (fix round 3)
--   같은 goods_receipt 배치에 COMPLETED 수량 0인 행과 COMPLETED 수량 5인 행을 함께 커밋 →
--   commit_import_batch가 예외 없이 끝나고, 잔액은 정확히 5만큼만 늘어야 한다(0 수량 행은
--   원장에 들어가지 않는다).

-- (a-5) 같은 입고번호에 품목이 여러 줄이면 품목별로 각각 반영되는지 확인 (fix round 3)
--   같은 source_record_id, 품목 A 수량 5 · 품목 B 수량 7, 둘 다 스냅샷 시각 이후 COMPLETED로
--   커밋 → A는 +5, B는 +7. 같은 배치를 다시 반영해도 값이 그대로여야 한다.

-- (b) 상태 미입력 재고는 0이 아니라 사유 코드로 제외되는지 확인
select item_id, normal_warehouse_qty, available_qty, reason_code
from analytics.v_available_stock
where reason_code = 'INVENTORY_SCOPE_UNCLASSIFIED'
order by item_id;
-- 기대: 기존 43행처럼 상태값이 없는 품목은 normal_warehouse_qty · available_qty가 null이고
--       reason_code가 INVENTORY_SCOPE_UNCLASSIFIED. 0행으로 나오면 안 된다.

-- (c) 뷰의 security_invoker 설정 확인
select c.relname, c.reloptions
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
where n.nspname = 'analytics' and c.relname in ('v_available_stock', 'v_order_available_stock');
-- 기대: 두 뷰 모두 reloptions에 security_invoker=true

-- (c-1) ATP_VIEW만 가진 사용자는 v_available_stock에서 0행, v_order_available_stock에서는
-- 최소 열만 보이는지 확인(SQL Editor에서 SALES_REP 계정으로 로그인해 실행).
-- select count(*) from analytics.v_available_stock;         -- 기대: 0
-- select * from analytics.v_order_available_stock limit 5;  -- 기대: item_id·item_name·available_qty·reason_code만

-- (d) 익명 사용자는 조회·갱신할 수 없는지 확인 (SQL Editor에서 anon 역할로 실행)
-- set role anon;
-- select * from analytics.v_available_stock;              -- 기대: 0행 또는 42501
-- select * from analytics.v_order_available_stock;        -- 기대: 0행 또는 42501
-- select * from core.stock_balance;                        -- 기대: 42501 또는 0행
-- select * from core.stock_receipt_ledger;                 -- 기대: 42501 또는 0행
-- select core.refresh_stock_balance(gen_random_uuid());    -- 기대: 42501 (function 실행 권한 없음)
-- reset role;
