-- Task 2 · 공통 승인 및 감사 이력 엔진
--
-- 품목 정책, 우선 배정, 이벤트 추가 수요, 최종 발주계획이 같은 승인 원장을 사용합니다.
-- 도메인별 승인 후처리는 Task 5/8/9에서 core.decide_approval() 내부의 타입별 처리로 연결합니다.
-- 실제 Supabase 적용은 사용자가 SQL Editor에서 수동으로 수행합니다.


-- ══ 1. 승인 요청 원장과 append-only 이벤트 ═══════════════════

create table if not exists core.approval_request (
  approval_id       uuid primary key default gen_random_uuid(),
  approval_type     text not null check (approval_type in (
    'ITEM_POLICY', 'ALLOC_PRIORITY', 'EVENT_ORDER', 'PURCHASE_PLAN'
  )),
  target_type       text not null check (btrim(target_type) <> ''),
  target_id         text not null check (btrim(target_id) <> ''),
  payload           jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  status            text not null default 'PENDING' check (status in (
    'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'
  )),
  reason_code       text,
  reason_text       text,
  requested_by      uuid not null references auth.users(id) on delete restrict,
  requester_name    text not null check (btrim(requester_name) <> ''),
  requested_at      timestamptz not null default now(),
  decided_by        uuid references auth.users(id) on delete restrict,
  decider_name      text,
  decided_at        timestamptz,
  decision_comment  text,
  constraint approval_request_decision_check check (
    (status = 'PENDING' and decided_by is null and decider_name is null
        and decided_at is null and decision_comment is null)
    or (status = 'APPROVED' and decided_by is not null
        and nullif(btrim(decider_name), '') is not null and decided_at is not null)
    or (status = 'REJECTED' and decided_by is not null and decided_at is not null
        and nullif(btrim(decider_name), '') is not null
        and nullif(btrim(decision_comment), '') is not null)
    or (status = 'CANCELLED' and decided_by is not null
        and nullif(btrim(decider_name), '') is not null and decided_at is not null)
  )
);

-- 개발 중 이전 초안을 먼저 적용한 DB에서도 이름 열을 보존적으로 보강합니다.
alter table core.approval_request add column if not exists requester_name text;
alter table core.approval_request add column if not exists decider_name text;

update core.approval_request r
   set requester_name = coalesce(nullif(btrim(u.name), ''), nullif(btrim(u.email), ''), r.requested_by::text)
  from core.app_user u
 where u.user_id = r.requested_by
   and nullif(btrim(r.requester_name), '') is null;

update core.approval_request
   set requester_name = requested_by::text
 where nullif(btrim(requester_name), '') is null;

update core.approval_request r
   set decider_name = coalesce(nullif(btrim(u.name), ''), nullif(btrim(u.email), ''), r.decided_by::text)
  from core.app_user u
 where u.user_id = r.decided_by
   and r.decided_by is not null
   and nullif(btrim(r.decider_name), '') is null;

update core.approval_request
   set decider_name = decided_by::text
 where decided_by is not null
   and nullif(btrim(decider_name), '') is null;

alter table core.approval_request alter column requester_name set not null;
alter table core.approval_request drop constraint if exists approval_request_decision_check;
alter table core.approval_request add constraint approval_request_decision_check check (
  (status = 'PENDING' and decided_by is null and decider_name is null
      and decided_at is null and decision_comment is null)
  or (status = 'APPROVED' and decided_by is not null
      and nullif(btrim(decider_name), '') is not null and decided_at is not null)
  or (status = 'REJECTED' and decided_by is not null and decided_at is not null
      and nullif(btrim(decider_name), '') is not null
      and nullif(btrim(decision_comment), '') is not null)
  or (status = 'CANCELLED' and decided_by is not null
      and nullif(btrim(decider_name), '') is not null and decided_at is not null)
);

create table if not exists core.approval_event (
  event_id          bigint generated by default as identity primary key,
  approval_id       uuid not null references core.approval_request(approval_id) on delete restrict,
  event_type        text not null check (event_type in ('REQUESTED', 'APPROVED', 'REJECTED', 'CANCELLED')),
  previous_status   text check (previous_status is null or previous_status in ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
  next_status       text not null check (next_status in ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
  actor             uuid not null references auth.users(id) on delete restrict,
  comment           text,
  payload_snapshot  jsonb not null,
  at                timestamptz not null default now(),
  constraint approval_event_transition_check check (
    (event_type = 'REQUESTED' and previous_status is null and next_status = 'PENDING')
    or (event_type in ('APPROVED', 'REJECTED', 'CANCELLED')
        and previous_status = 'PENDING' and next_status = event_type)
  )
);

create index if not exists approval_request_inbox_idx
  on core.approval_request (status, approval_type, requested_at desc);
create index if not exists approval_request_requester_idx
  on core.approval_request (requested_by, requested_at desc);
create index if not exists approval_request_target_idx
  on core.approval_request (target_type, target_id, requested_at desc);
create index if not exists approval_event_request_idx
  on core.approval_event (approval_id, at, event_id);

comment on table core.approval_request is
  'Task 2 공통 승인 원장. 승인 후 도메인 반영은 후속 Task에서 연결합니다';
comment on table core.approval_event is
  'Task 2 승인 상태 변경 append-only 이력. UPDATE와 DELETE는 트리거로도 차단합니다';

create or replace function core.reject_approval_event_mutation()
returns trigger
language plpgsql
set search_path = core, pg_temp
as $$
begin
  raise exception '승인 이벤트 이력은 수정하거나 삭제할 수 없습니다.' using errcode = '42501';
end;
$$;

drop trigger if exists approval_event_append_only on core.approval_event;
create trigger approval_event_append_only
  before update or delete on core.approval_event
  for each row execute function core.reject_approval_event_mutation();


-- ══ 2. 승인 요청 생성 ════════════════════════════════════════

create or replace function core.request_approval(
  p_approval_type text,
  p_target_type text,
  p_target_id text,
  p_payload jsonb default '{}'::jsonb,
  p_reason_code text default null,
  p_reason_text text default null
)
returns uuid
language plpgsql
security definer
set search_path = core, public, pg_temp
as $$
declare
  v_actor uuid := auth.uid();
  v_actor_name text;
  v_required_permission text;
  v_approval_id uuid;
  v_after jsonb;
begin
  if v_actor is null or not core.is_active_user(v_actor) then
    raise exception '로그인한 활성 사용자만 승인 요청을 만들 수 있습니다.' using errcode = '42501';
  end if;

  if p_approval_type is null or p_approval_type not in (
    'ITEM_POLICY', 'ALLOC_PRIORITY', 'EVENT_ORDER', 'PURCHASE_PLAN'
  ) then
    raise exception '지원하지 않는 승인 유형입니다.' using errcode = '22023';
  end if;

  v_required_permission := case p_approval_type
    when 'ITEM_POLICY' then 'ITEM_POLICY_EDIT'
    when 'ALLOC_PRIORITY' then 'ALLOC_MANUAL'
    when 'EVENT_ORDER' then 'DEMAND_CONSOLIDATE'
    when 'PURCHASE_PLAN' then 'PLAN_CONFIRM'
  end;

  if v_required_permission is null or not core.has_permission(v_required_permission, v_actor) then
    raise exception '이 승인 유형을 요청할 업무 권한이 없습니다.' using errcode = '42501';
  end if;

  select coalesce(nullif(btrim(u.name), ''), nullif(btrim(u.email), ''), u.user_id::text)
    into v_actor_name
    from core.app_user u
   where u.user_id = v_actor;

  if nullif(btrim(p_target_type), '') is null or nullif(btrim(p_target_id), '') is null then
    raise exception '승인 대상 유형과 대상 ID는 필수입니다.' using errcode = '22023';
  end if;

  if p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    raise exception '승인 요청 payload는 JSON 객체여야 합니다.' using errcode = '22023';
  end if;

  if p_approval_type = 'EVENT_ORDER' then
    if nullif(btrim(p_payload ->> 'customer'), '') is null then
      raise exception '이벤트 추가 수요의 고객은 필수입니다.' using errcode = '22023';
    end if;
    if nullif(btrim(p_payload ->> 'model'), '') is null then
      raise exception '이벤트 추가 수요의 기종은 필수입니다.' using errcode = '22023';
    end if;
    if jsonb_typeof(p_payload -> 'quantity') is distinct from 'number' then
      raise exception '이벤트 추가 수요의 수량은 양수여야 합니다.' using errcode = '22023';
    end if;
    if (p_payload ->> 'quantity')::numeric <= 0 then
      raise exception '이벤트 추가 수요의 수량은 양수여야 합니다.' using errcode = '22023';
    end if;
  end if;

  insert into core.approval_request (
    approval_type, target_type, target_id, payload,
    reason_code, reason_text, requested_by, requester_name
  ) values (
    p_approval_type, btrim(p_target_type), btrim(p_target_id), p_payload,
    nullif(btrim(p_reason_code), ''), nullif(btrim(p_reason_text), ''), v_actor, v_actor_name
  )
  returning approval_id into v_approval_id;

  select to_jsonb(r) into v_after
    from core.approval_request r
   where r.approval_id = v_approval_id;

  insert into core.approval_event (
    approval_id, event_type, previous_status, next_status,
    actor, comment, payload_snapshot
  ) values (
    v_approval_id, 'REQUESTED', null, 'PENDING',
    v_actor, nullif(btrim(p_reason_text), ''), v_after
  );

  insert into core.audit_log (actor, action, target_type, target_id, before, after)
  values (v_actor, 'APPROVAL_REQUESTED', 'APPROVAL_REQUEST', v_approval_id::text, null, v_after);

  return v_approval_id;
end;
$$;


-- ══ 3. 승인 또는 반려 ════════════════════════════════════════

create or replace function core.decide_approval(
  p_approval_id uuid,
  p_decision text,
  p_decision_comment text default null
)
returns uuid
language plpgsql
security definer
set search_path = core, public, pg_temp
as $$
declare
  v_actor uuid := auth.uid();
  v_actor_name text;
  v_required_permission text;
  v_request core.approval_request%rowtype;
  v_before jsonb;
  v_after jsonb;
begin
  if v_actor is null or not core.is_active_user(v_actor) then
    raise exception '로그인한 활성 사용자만 승인 요청을 처리할 수 있습니다.' using errcode = '42501';
  end if;

  if p_decision is null or p_decision not in ('APPROVED', 'REJECTED') then
    raise exception '승인 결과는 APPROVED 또는 REJECTED여야 합니다.' using errcode = '22023';
  end if;

  select * into v_request
    from core.approval_request
   where approval_id = p_approval_id
   for update;

  if not found then
    raise exception '승인 요청을 찾을 수 없습니다.' using errcode = 'P0002';
  end if;

  v_required_permission := case v_request.approval_type
    when 'ITEM_POLICY' then 'ITEM_POLICY_APPROVE'
    when 'ALLOC_PRIORITY' then 'ALLOC_PRIORITY_APPROVE'
    when 'EVENT_ORDER' then 'EVENT_ORDER_APPROVE'
    when 'PURCHASE_PLAN' then 'PLAN_APPROVE'
  end;

  if v_required_permission is null or not core.has_permission(v_required_permission, v_actor) then
    raise exception '이 승인 유형을 결정할 업무 권한이 없습니다.' using errcode = '42501';
  end if;

  select coalesce(nullif(btrim(u.name), ''), nullif(btrim(u.email), ''), u.user_id::text)
    into v_actor_name
    from core.app_user u
   where u.user_id = v_actor;

  if v_request.requested_by = v_actor then
    raise exception '자신이 요청한 승인은 직접 결정할 수 없습니다.' using errcode = '42501';
  end if;

  if v_request.status <> 'PENDING' then
    raise exception '이미 처리되었거나 취소된 승인 요청입니다.' using errcode = '22023';
  end if;

  if p_decision = 'REJECTED' and nullif(btrim(p_decision_comment), '') is null then
    raise exception '반려 의견은 필수입니다.' using errcode = '22023';
  end if;

  v_before := to_jsonb(v_request);

  update core.approval_request
     set status = p_decision,
         decided_by = v_actor,
         decider_name = v_actor_name,
         decided_at = clock_timestamp(),
         decision_comment = nullif(btrim(p_decision_comment), '')
   where approval_id = p_approval_id;

  select to_jsonb(r) into v_after
    from core.approval_request r
   where r.approval_id = p_approval_id;

  insert into core.approval_event (
    approval_id, event_type, previous_status, next_status,
    actor, comment, payload_snapshot
  ) values (
    p_approval_id, p_decision, 'PENDING', p_decision,
    v_actor, nullif(btrim(p_decision_comment), ''), v_after
  );

  insert into core.audit_log (actor, action, target_type, target_id, before, after)
  values (
    v_actor,
    case p_decision when 'APPROVED' then 'APPROVAL_APPROVED' else 'APPROVAL_REJECTED' end,
    'APPROVAL_REQUEST', p_approval_id::text, v_before, v_after
  );

  return p_approval_id;
end;
$$;


-- ══ 4. 사용자별 조회 뷰 ══════════════════════════════════════

create or replace view analytics.v_my_approval_inbox
with (security_invoker = true)
as
select
  r.approval_id, r.approval_type, r.target_type, r.target_id, r.payload,
  r.status, r.reason_code, r.reason_text,
  r.requested_by, r.requested_at,
  r.decided_by, r.decided_at, r.decision_comment,
  r.requester_name, r.decider_name
from core.approval_request r
where r.status = 'PENDING'
  and r.requested_by <> auth.uid()
  and core.has_permission(
    case r.approval_type
      when 'ITEM_POLICY' then 'ITEM_POLICY_APPROVE'
      when 'ALLOC_PRIORITY' then 'ALLOC_PRIORITY_APPROVE'
      when 'EVENT_ORDER' then 'EVENT_ORDER_APPROVE'
      when 'PURCHASE_PLAN' then 'PLAN_APPROVE'
    end
  );

create or replace view analytics.v_approval_history
with (security_invoker = true)
as
select
  r.approval_id, r.approval_type, r.target_type, r.target_id, r.payload,
  r.status, r.reason_code, r.reason_text,
  r.requested_by, r.requested_at,
  r.decided_by, r.decided_at, r.decision_comment,
  r.requester_name, r.decider_name
from core.approval_request r
where r.requested_by = auth.uid()
   or r.decided_by = auth.uid()
   or core.has_permission(
     case r.approval_type
       when 'ITEM_POLICY' then 'ITEM_POLICY_APPROVE'
       when 'ALLOC_PRIORITY' then 'ALLOC_PRIORITY_APPROVE'
       when 'EVENT_ORDER' then 'EVENT_ORDER_APPROVE'
       when 'PURCHASE_PLAN' then 'PLAN_APPROVE'
     end
   );

comment on view analytics.v_my_approval_inbox is
  '현재 사용자가 권한으로 처리할 수 있고 본인이 요청하지 않은 PENDING 승인';
comment on view analytics.v_approval_history is
  '현재 사용자의 요청·처리 이력과 승인 권한 범위 이력';


-- ══ 5. RLS와 실행 권한 ═══════════════════════════════════════

alter table core.approval_request enable row level security;
alter table core.approval_event enable row level security;

drop policy if exists approval_request_read_related on core.approval_request;
create policy approval_request_read_related
  on core.approval_request
  for select
  to authenticated
  using (
    requested_by = auth.uid()
    or decided_by = auth.uid()
    or core.has_permission(
      case approval_type
        when 'ITEM_POLICY' then 'ITEM_POLICY_APPROVE'
        when 'ALLOC_PRIORITY' then 'ALLOC_PRIORITY_APPROVE'
        when 'EVENT_ORDER' then 'EVENT_ORDER_APPROVE'
        when 'PURCHASE_PLAN' then 'PLAN_APPROVE'
      end
    )
  );

drop policy if exists approval_event_read_related on core.approval_event;
create policy approval_event_read_related
  on core.approval_event
  for select
  to authenticated
  using (
    exists (
      select 1
        from core.approval_request r
       where r.approval_id = approval_event.approval_id
    )
  );

revoke all on core.approval_request, core.approval_event from anon, public;
revoke insert, update, delete on core.approval_request, core.approval_event from authenticated;
grant select on core.approval_request, core.approval_event to authenticated;
grant select on analytics.v_my_approval_inbox, analytics.v_approval_history to authenticated;

revoke all on function core.request_approval(text, text, text, jsonb, text, text) from public, anon;
revoke all on function core.decide_approval(uuid, text, text) from public, anon;
grant execute on function core.request_approval(text, text, text, jsonb, text, text) to authenticated;
grant execute on function core.decide_approval(uuid, text, text) to authenticated;
revoke all on function core.reject_approval_event_mutation() from public, anon, authenticated;


-- ══ 6. 수동 적용 후 확인 쿼리 ════════════════════════════════

select approval_type, status, requested_by, decided_by
from core.approval_request
order by requested_at desc;

select action, target_type, target_id
from core.audit_log
where target_type = 'APPROVAL_REQUEST'
order by at desc;

select c.relname, c.reloptions
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
where n.nspname = 'analytics'
  and c.relname in ('v_my_approval_inbox', 'v_approval_history')
order by c.relname;
-- 기대: 두 뷰 모두 reloptions에 security_invoker=true

select r.approval_id, r.status,
       count(distinct e.event_id) as event_count,
       count(distinct a.id) as audit_count
from core.approval_request r
left join core.approval_event e on e.approval_id = r.approval_id
left join core.audit_log a
  on a.target_type = 'APPROVAL_REQUEST'
 and a.target_id = r.approval_id::text
group by r.approval_id, r.status
order by max(r.requested_at) desc;
-- 기대: 요청 직후 event_count=1/audit_count=1, 승인·반려 후 각각 2

-- 아래 실패 검증은 SQL Editor에서 요청자와 승인자의 실제 UUID를 넣고 각각 실행합니다.
-- begin;
-- set local role authenticated;
-- select set_config('request.jwt.claim.sub', '<검증할 사용자 UUID>', true);
-- select core.decide_approval('<승인 요청 UUID>', 'APPROVED', '검증');
-- rollback;
-- 1) 권한 없는 USER UUID로 core.request_approval(...) → SQLSTATE 42501
-- 2) 요청자 본인 UUID → "자신이 요청한 승인은 직접 결정할 수 없습니다."
-- 3) 승인자 UUID로 세 번째 인자를 ''로 하고 REJECTED → "반려 의견은 필수입니다."
