-- Task 7 · 부서별 월간 수요 제출과 마감 관리
--
-- 목적: 1순위 병목인 부서별 수요 자료 취합 시간을 줄이고, 제출·회수·수정·합의 이력을 남긴다
-- (stage1.md §1 목표 우선순위, §3 "부서별 수요 자료 제출").
--
-- ★ 여기서 만든 제출 자료 자체는 조달 수요로 집계하지 않는다 — Task 8이 만들 "확정" 소스만
--   최종 발주계획에 들어간다. 이 마이그레이션은 취합 과정(제출·회수·합의)만 다룬다.
-- ★ 품목코드 검증은 STEP 4(core.v_item_master, core.normalize_item_id)를 그대로 재사용한다.
--   새 정규화 규칙을 만들지 않는다.
-- ★ 알 수 없는 품목·null 수량·잘못된 날짜는 조용히 지우지 않는다. core.demand_submission_line에
--   행을 그대로 남기고 issues(오류 사유)를 붙인다.
-- ★ 실제 Supabase 적용은 사용자가 SQL Editor에서 수동으로 수행한다. 이 파일은 다시 실행해도 안전하다.


-- ══ 1. 수요 취합 주기 ═══════════════════════════════════════════

create table if not exists core.planning_cycle (
  cycle_id            uuid primary key default gen_random_uuid(),
  plan_month          date not null check (plan_month = date_trunc('month', plan_month)::date),
  submission_deadline date not null,
  status              text not null default 'OPEN' check (status in ('OPEN', 'CLOSED')),
  is_active           boolean not null default true,
  opened_by           uuid not null references auth.users(id) on delete restrict,
  opened_at           timestamptz not null default now(),
  closed_by           uuid references auth.users(id) on delete restrict,
  closed_at           timestamptz,
  constraint planning_cycle_close_check check (
    (status = 'OPEN' and is_active and closed_by is null and closed_at is null)
    or (status = 'CLOSED' and not is_active and closed_by is not null and closed_at is not null)
  )
);

-- 한 달에 "열린" 주기는 하나만 허용한다(컨트롤러 판정 3). 닫힌 뒤 같은 달을 다시 열 수 있도록
-- 활성 행에만 유니크 제약을 건다 — 이전 이력은 지우지 않는다.
create unique index if not exists planning_cycle_active_month_idx
  on core.planning_cycle (plan_month) where is_active;

comment on table core.planning_cycle is
  'Task 7 — SCM 품목담당자(PLAN_CONFIRM) 또는 ADMIN이 여는 월별 수요 취합 주기';


-- ══ 2. 부서 제출본과 라인 ═══════════════════════════════════════

create table if not exists core.demand_submission (
  submission_id     uuid primary key default gen_random_uuid(),
  cycle_id          uuid not null references core.planning_cycle(cycle_id) on delete restrict,
  plan_month        date not null,
  department        text not null check (department in ('SCM', 'SALES', 'MARKETING', 'SERVICE', 'BIZ_DEV')),
  status            text not null default 'DRAFT' check (status in ('DRAFT', 'SUBMITTED', 'WITHDRAWN', 'AGREED')),
  created_by        uuid not null references auth.users(id) on delete restrict,
  submitted_by      uuid references auth.users(id) on delete restrict,
  submitted_at      timestamptz,
  withdrawn_by      uuid references auth.users(id) on delete restrict,
  withdrawn_at      timestamptz,
  withdraw_reason   text,
  agreed_by         uuid references auth.users(id) on delete restrict,
  agreed_at         timestamptz,
  last_modified_by  uuid not null references auth.users(id) on delete restrict,
  last_modified_at  timestamptz not null default now(),
  version           integer not null default 1 check (version > 0),
  created_at        timestamptz not null default now(),
  -- 동일 부서·기준월(취합 주기)의 활성 제출본은 하나뿐이다 — 검증 체크리스트 1번.
  unique (cycle_id, department)
);

create index if not exists demand_submission_department_idx
  on core.demand_submission (department, plan_month desc);

create table if not exists core.demand_submission_line (
  line_id        uuid primary key default gen_random_uuid(),
  submission_id  uuid not null references core.demand_submission(submission_id) on delete cascade,
  line_no        integer not null check (line_no > 0),
  raw_item_code  text,                 -- 원본 품목코드(입력 그대로)
  item_id        text,                 -- 표준 품목코드(core.normalize_item_id) — 매칭 실패 시 null
  qty            numeric,              -- 수량 — 없거나 숫자가 아니면 null(0으로 채우지 않는다)
  need_month     date,                 -- 필요월(월의 1일로 저장) — 형식이 아니면 null
  issues         jsonb not null default '[]'::jsonb check (jsonb_typeof(issues) = 'array'),
  created_at     timestamptz not null default now(),
  unique (submission_id, line_no)
);

create index if not exists demand_submission_line_submission_idx
  on core.demand_submission_line (submission_id, line_no);

comment on table core.demand_submission_line is
  'Task 7 — 부서 제출 한 줄. 품목코드 불일치·null 수량·잘못된 날짜도 행을 지우지 않고 issues로 남긴다';

create table if not exists core.demand_submission_event (
  event_id          bigint generated by default as identity primary key,
  submission_id     uuid not null references core.demand_submission(submission_id) on delete restrict,
  event_type        text not null check (event_type in ('CREATED', 'SUBMITTED', 'WITHDRAWN', 'EDITED', 'AGREED')),
  previous_status   text check (previous_status is null or previous_status in ('DRAFT', 'SUBMITTED', 'WITHDRAWN', 'AGREED')),
  next_status       text not null check (next_status in ('DRAFT', 'SUBMITTED', 'WITHDRAWN', 'AGREED')),
  version           integer not null,
  actor             uuid not null references auth.users(id) on delete restrict,
  actor_name        text not null,
  reason            text,
  payload_snapshot  jsonb not null,
  at                timestamptz not null default now()
);

create index if not exists demand_submission_event_submission_idx
  on core.demand_submission_event (submission_id, at, event_id);

comment on table core.demand_submission_event is
  'Task 7 — 제출·회수·수정·합의 append-only 이력. 버전·행위자·시각·사유(있으면)를 모두 남긴다';

create or replace function core.reject_demand_submission_event_mutation()
returns trigger
language plpgsql
set search_path = core, pg_temp
as $$
begin
  raise exception '수요 제출 이력은 수정하거나 삭제할 수 없습니다.' using errcode = '42501';
end;
$$;

drop trigger if exists demand_submission_event_append_only on core.demand_submission_event;
create trigger demand_submission_event_append_only
  before update or delete on core.demand_submission_event
  for each row execute function core.reject_demand_submission_event_mutation();


-- ══ 2-1. 닫힌 취합 주기 쓰기 잠금(구조적 안전장치) ══════════════════
--
-- fix round 2 — core.save_demand_submission_lines · submit_demand_submission ·
-- withdraw_demand_submission · agree_demand_submission이 각각 "취합 주기가 닫혔는지"를
-- 확인하지만, 그 확인을 깜빡한 함수가 나중에 하나라도 추가되면 닫힌(얼어붙은) 제출본이 다시
-- 바뀔 수 있다 — 실제로 agree_demand_submission이 1차 수정 때 이 확인을 빠뜨렸었다. 애플리케이션
-- 함수의 확인에만 기대지 않고, 테이블 자체에 BEFORE 트리거를 달아 "닫힌 주기에 묶인 행은 절대
-- 못 바뀐다"를 DB가 직접 강제한다 — 이 트리거를 우회하지 않는 한 앞으로 어떤 함수(또는 실수로
-- 권한이 열린 직접 SQL)도 이 규칙을 어길 수 없다.
--
-- 이 트리거와 "취합 주기당(월당) 활성 주기 1개"(§1 부분 유니크 인덱스) · "활성 주기당 부서
-- 제출본 1개"(§2 unique(cycle_id, department))를 합치면, "부서·기준월당 얼어붙지 않은(살아있는)
-- 제출본은 항상 하나뿐"이라는 불변식이 구조적으로 성립한다 — 닫힌 주기의 행은 이 트리거가 상태
-- 변경을 막아 영구히 얼어붙고, 새 주기의 행만 유일하게 계속 바뀔 수 있기 때문이다.

create or replace function core.guard_demand_submission_cycle_active()
returns trigger
language plpgsql
security definer
set search_path = core, pg_temp
as $$
declare
  v_is_active boolean;
begin
  select c.is_active into v_is_active from core.planning_cycle c where c.cycle_id = new.cycle_id;
  if v_is_active is distinct from true then
    raise exception '취합 주기가 닫힌 제출본은 더 이상 바꿀 수 없습니다.' using errcode = '22023';
  end if;
  return new;
end;
$$;

drop trigger if exists demand_submission_guard_cycle_active on core.demand_submission;
create trigger demand_submission_guard_cycle_active
  before insert or update on core.demand_submission
  for each row execute function core.guard_demand_submission_cycle_active();

create or replace function core.guard_demand_submission_line_cycle_active()
returns trigger
language plpgsql
security definer
set search_path = core, pg_temp
as $$
declare
  v_submission_id uuid := coalesce(new.submission_id, old.submission_id);
  v_is_active boolean;
begin
  select c.is_active into v_is_active
    from core.demand_submission s
    join core.planning_cycle c on c.cycle_id = s.cycle_id
   where s.submission_id = v_submission_id;
  if v_is_active is distinct from true then
    raise exception '취합 주기가 닫힌 제출본의 항목은 더 이상 바꿀 수 없습니다.' using errcode = '22023';
  end if;
  return coalesce(new, old);
end;
$$;

drop trigger if exists demand_submission_line_guard_cycle_active on core.demand_submission_line;
create trigger demand_submission_line_guard_cycle_active
  before insert or update or delete on core.demand_submission_line
  for each row execute function core.guard_demand_submission_line_cycle_active();


-- ══ 3. 마감일 계산 ═══════════════════════════════════════════════
--
-- stage1.md §3: "월간 수요 자료 제출 마감일은 전월 말일의 하루 전으로 한다.
-- 예를 들어 3월 31일이 말일이면 제출 마감일은 3월 30일이다." (대상월 4월 기준)
-- 전월 말일 = 대상월 1일 - 1일. 거기서 다시 하루를 빼면 대상월 1일 - 2일과 같다.
-- 영업일 보정은 하지 않는다(컨트롤러 판정 1).

create or replace function core.submission_deadline(p_plan_month date)
returns date
language sql
immutable
set search_path = core, pg_temp
as $$
  select (date_trunc('month', p_plan_month)::date - 2);
$$;

comment on function core.submission_deadline(date) is
  'Task 7 — 대상월 1일 - 2일 = 전월 말일 - 1일. lib/demand/model.ts의 submissionDeadline과 값이 같아야 한다';


-- ══ 4. 취합 주기 열기·닫기 ═══════════════════════════════════════

create or replace function core.open_planning_cycle(p_plan_month date)
returns uuid
language plpgsql
security definer
set search_path = core, public, pg_temp
as $$
declare
  v_actor uuid := auth.uid();
  v_month date;
  v_cycle_id uuid;
begin
  if v_actor is null or not core.is_active_user(v_actor) then
    raise exception '로그인한 활성 사용자만 취합 주기를 열 수 있습니다.' using errcode = '42501';
  end if;
  if not (core.has_permission('PLAN_CONFIRM', v_actor) or core.is_admin(v_actor)) then
    raise exception 'SCM 품목담당자 또는 관리자만 취합 주기를 열 수 있습니다.' using errcode = '42501';
  end if;
  if p_plan_month is null then
    raise exception '기준월은 필수입니다.' using errcode = '22023';
  end if;

  v_month := date_trunc('month', p_plan_month)::date;

  if exists (select 1 from core.planning_cycle where plan_month = v_month and is_active) then
    raise exception '이미 해당 월의 취합 주기가 열려 있습니다.' using errcode = '22023';
  end if;

  insert into core.planning_cycle (plan_month, submission_deadline, opened_by)
  values (v_month, core.submission_deadline(v_month), v_actor)
  returning cycle_id into v_cycle_id;

  return v_cycle_id;
end;
$$;

create or replace function core.close_planning_cycle(p_cycle_id uuid)
returns void
language plpgsql
security definer
set search_path = core, public, pg_temp
as $$
declare
  v_actor uuid := auth.uid();
  v_department text;
begin
  if v_actor is null or not core.is_active_user(v_actor) then
    raise exception '로그인한 활성 사용자만 취합 주기를 닫을 수 있습니다.' using errcode = '42501';
  end if;
  if not (core.has_permission('PLAN_CONFIRM', v_actor) or core.is_admin(v_actor)) then
    raise exception 'SCM 품목담당자 또는 관리자만 취합 주기를 닫을 수 있습니다.' using errcode = '42501';
  end if;

  update core.planning_cycle
     set status = 'CLOSED', is_active = false, closed_by = v_actor, closed_at = clock_timestamp()
   where cycle_id = p_cycle_id
     and is_active;

  if not found then
    raise exception '열려 있는 취합 주기를 찾을 수 없습니다.' using errcode = 'P0002';
  end if;

  -- fix round 1 — 닫힌 주기에 남아 있던 반복 미제출 알림을 전부 중단한다. 재개(reopen)는
  -- 같은 달에 새 cycle_id로 새 취합 주기를 여는 것이라, 이 닫힌 주기에 묶인 제출본(DRAFT ·
  -- WITHDRAWN · SUBMITTED 무엇이든)은 다시 살아나지 않고 읽기 전용 이력으로만 남는다
  -- (core.save_demand_submission_lines · submit_demand_submission ·
  -- withdraw_demand_submission이 is_active=false인 주기의 쓰기를 거절한다).
  for v_department in
    select distinct u.department
      from core.app_user u
      join core.role_permission rp on rp.job_role = u.job_role
     where u.active and rp.permission_code = 'DEMAND_SUBMIT' and u.department is not null
  loop
    perform core.cancel_notification_series('DEMAND_SUBMISSION', p_cycle_id::text || ':' || v_department);
  end loop;
end;
$$;


-- ══ 5. 제출본 시작·저장·제출·회수·합의 ══════════════════════════
--
-- ★ 부서 소속은 core.app_user.department로 판정한다. 별도 부서 마스터는 두지 않는다
--   (컨트롤러 판정 2). 제출 권한이 있는 부서만 이 함수들을 쓸 수 있다.
-- ★ 다른 부서 제출본에 대한 접근은 여기서 명시적으로 거절한다 — RLS는 조회만 격리하고,
--   쓰기는 아래 함수 안의 부서 비교가 최종 방어선이다(테이블 직접 쓰기는 5장에서 막는다).

create or replace function core.start_demand_submission(p_plan_month date)
returns uuid
language plpgsql
security definer
set search_path = core, public, pg_temp
as $$
declare
  v_actor uuid := auth.uid();
  v_department text;
  v_month date;
  v_cycle core.planning_cycle%rowtype;
  v_submission_id uuid;
begin
  if v_actor is null or not core.is_active_user(v_actor) then
    raise exception '로그인한 활성 사용자만 수요를 작성할 수 있습니다.' using errcode = '42501';
  end if;
  if not core.has_permission('DEMAND_SUBMIT', v_actor) then
    raise exception '부서 수요 제출 권한이 없습니다.' using errcode = '42501';
  end if;

  select department into v_department from core.app_user where user_id = v_actor;
  if nullif(btrim(v_department), '') is null then
    raise exception '소속 부서가 설정되지 않았습니다. 관리자에게 문의하세요.' using errcode = '22023';
  end if;

  v_month := date_trunc('month', p_plan_month)::date;

  select * into v_cycle from core.planning_cycle where plan_month = v_month and is_active for update;
  if not found then
    raise exception '해당 월의 수요 취합 주기가 열려 있지 않습니다.' using errcode = '22023';
  end if;

  select submission_id into v_submission_id
    from core.demand_submission
   where cycle_id = v_cycle.cycle_id and department = v_department;

  if v_submission_id is not null then
    return v_submission_id;
  end if;

  insert into core.demand_submission (
    cycle_id, plan_month, department, status, created_by, last_modified_by, last_modified_at
  ) values (
    v_cycle.cycle_id, v_cycle.plan_month, v_department, 'DRAFT', v_actor, v_actor, clock_timestamp()
  )
  returning submission_id into v_submission_id;

  insert into core.demand_submission_event (
    submission_id, event_type, previous_status, next_status, version, actor, actor_name, payload_snapshot
  )
  select v_submission_id, 'CREATED', null, 'DRAFT', 1, v_actor, core.order_actor_name(v_actor), to_jsonb(s)
    from core.demand_submission s
   where s.submission_id = v_submission_id;

  return v_submission_id;
end;
$$;

-- ★ 여기서 STEP 4와 같은 품목코드 정규화(core.normalize_item_id)를 쓰고, core.v_item_master로
--   DB측 매칭을 다시 확인한다. 클라이언트(lib/import/validate.ts)가 계산한 값을 신뢰하지 않는다 —
--   최종 저장 전 검증의 출처는 이 함수 하나다(컨트롤러 판정 4).
create or replace function core.save_demand_submission_lines(p_submission_id uuid, p_lines jsonb)
returns core.demand_submission
language plpgsql
security definer
set search_path = core, public, pg_temp
as $$
declare
  v_actor uuid := auth.uid();
  v_department text;
  v_submission core.demand_submission%rowtype;
  v_line jsonb;
  v_line_no integer := 0;
  v_raw_item text;
  v_raw_qty text;
  v_raw_month text;
  v_item_id text;
  v_qty numeric;
  v_need_month date;
  v_issues jsonb;
begin
  if v_actor is null or not core.is_active_user(v_actor) then
    raise exception '로그인한 활성 사용자만 저장할 수 있습니다.' using errcode = '42501';
  end if;
  if not core.has_permission('DEMAND_SUBMIT', v_actor) then
    raise exception '부서 수요 제출 권한이 없습니다.' using errcode = '42501';
  end if;

  select department into v_department from core.app_user where user_id = v_actor;

  select * into v_submission from core.demand_submission where submission_id = p_submission_id for update;
  if not found then
    raise exception '제출본을 찾을 수 없습니다.' using errcode = 'P0002';
  end if;
  if v_submission.department is distinct from v_department then
    raise exception '다른 부서의 제출본은 수정할 수 없습니다.' using errcode = '42501';
  end if;
  -- fix round 1 — 닫힌 취합 주기에 묶인 제출본은 얼려 둔다. 재개(open_planning_cycle)는
  -- 같은 달에 새 cycle_id를 만들 뿐 이 행을 되살리지 않는다(아래 §4 재개 정책 참고).
  if not exists (select 1 from core.planning_cycle c where c.cycle_id = v_submission.cycle_id and c.is_active) then
    raise exception '취합 주기가 닫혀 더 이상 수정할 수 없습니다.' using errcode = '22023';
  end if;
  if v_submission.status not in ('DRAFT', 'WITHDRAWN') then
    raise exception '제출되었거나 합의된 자료는 회수한 뒤에만 수정할 수 있습니다.' using errcode = '22023';
  end if;
  if p_lines is null or jsonb_typeof(p_lines) <> 'array' then
    raise exception '저장할 항목이 올바르지 않습니다.' using errcode = '22023';
  end if;

  delete from core.demand_submission_line where submission_id = p_submission_id;

  for v_line in select * from jsonb_array_elements(p_lines) loop
    v_line_no := v_line_no + 1;
    v_raw_item := nullif(btrim(v_line ->> 'item_id'), '');
    v_raw_qty := nullif(btrim(v_line ->> 'qty'), '');
    v_raw_month := nullif(btrim(v_line ->> 'need_month'), '');
    v_issues := '[]'::jsonb;

    -- 품목코드
    if v_raw_item is null then
      v_issues := v_issues || jsonb_build_array(
        jsonb_build_object('field_name', 'item_id', 'code', 'REQUIRED_VALUE', 'message', '품목코드가 없습니다.'));
      v_item_id := null;
    else
      v_item_id := core.normalize_item_id(v_raw_item);
      if not exists (select 1 from core.v_item_master im where im.item_id = v_item_id) then
        v_issues := v_issues || jsonb_build_array(
          jsonb_build_object('field_name', 'item_id', 'code', 'UNKNOWN_ITEM', 'message', '품목 마스터에 없습니다.'));
        v_item_id := null;
      end if;
    end if;

    -- 수량 — 없거나 숫자가 아니거나 음수면 null로 남기고 오류를 붙인다(0으로 채우지 않는다)
    v_qty := null;
    if v_raw_qty is null then
      v_issues := v_issues || jsonb_build_array(
        jsonb_build_object('field_name', 'qty', 'code', 'REQUIRED_VALUE', 'message', '수량이 없습니다.'));
    elsif v_raw_qty !~ '^-?[0-9]+(\.[0-9]+)?$' then
      v_issues := v_issues || jsonb_build_array(
        jsonb_build_object('field_name', 'qty', 'code', 'INVALID_NUMBER', 'message', '숫자 형식이 올바르지 않습니다.'));
    elsif v_raw_qty::numeric < 0 then
      v_issues := v_issues || jsonb_build_array(
        jsonb_build_object('field_name', 'qty', 'code', 'NEGATIVE_QUANTITY', 'message', '수량은 음수일 수 없습니다.'));
    else
      v_qty := v_raw_qty::numeric;
    end if;

    -- 필요월 — YYYY-MM만 받는다
    v_need_month := null;
    if v_raw_month is null then
      v_issues := v_issues || jsonb_build_array(
        jsonb_build_object('field_name', 'need_month', 'code', 'REQUIRED_VALUE', 'message', '필요월이 없습니다.'));
    elsif v_raw_month !~ '^\d{4}-\d{2}$' then
      v_issues := v_issues || jsonb_build_array(
        jsonb_build_object('field_name', 'need_month', 'code', 'INVALID_DATE', 'message', '연월 형식(YYYY-MM)이 올바르지 않습니다.'));
    elsif substring(v_raw_month from 6 for 2)::int not between 1 and 12 then
      v_issues := v_issues || jsonb_build_array(
        jsonb_build_object('field_name', 'need_month', 'code', 'INVALID_DATE', 'message', '연월 형식(YYYY-MM)이 올바르지 않습니다.'));
    else
      v_need_month := (v_raw_month || '-01')::date;
    end if;

    insert into core.demand_submission_line (submission_id, line_no, raw_item_code, item_id, qty, need_month, issues)
    values (p_submission_id, v_line_no, v_raw_item, v_item_id, v_qty, v_need_month, v_issues);
  end loop;

  update core.demand_submission
     set last_modified_by = v_actor, last_modified_at = clock_timestamp(), version = version + 1
   where submission_id = p_submission_id
   returning * into v_submission;

  insert into core.demand_submission_event (
    submission_id, event_type, previous_status, next_status, version, actor, actor_name, payload_snapshot
  ) values (
    p_submission_id, 'EDITED', v_submission.status, v_submission.status, v_submission.version,
    v_actor, core.order_actor_name(v_actor), jsonb_build_object('line_count', v_line_no)
  );

  return v_submission;
end;
$$;

create or replace function core.submit_demand_submission(p_submission_id uuid)
returns core.demand_submission
language plpgsql
security definer
set search_path = core, public, pg_temp
as $$
declare
  v_actor uuid := auth.uid();
  v_department text;
  v_submission core.demand_submission%rowtype;
  v_previous_status text;
  v_line_count integer;
  v_error_count integer;
begin
  if v_actor is null or not core.is_active_user(v_actor) then
    raise exception '로그인한 활성 사용자만 제출할 수 있습니다.' using errcode = '42501';
  end if;
  if not core.has_permission('DEMAND_SUBMIT', v_actor) then
    raise exception '부서 수요 제출 권한이 없습니다.' using errcode = '42501';
  end if;

  select department into v_department from core.app_user where user_id = v_actor;

  select * into v_submission from core.demand_submission where submission_id = p_submission_id for update;
  if not found then
    raise exception '제출본을 찾을 수 없습니다.' using errcode = 'P0002';
  end if;
  if v_submission.department is distinct from v_department then
    raise exception '다른 부서의 제출본은 제출할 수 없습니다.' using errcode = '42501';
  end if;
  -- fix round 1 — 닫힌 취합 주기에서는 제출도 막는다.
  if not exists (select 1 from core.planning_cycle c where c.cycle_id = v_submission.cycle_id and c.is_active) then
    raise exception '취합 주기가 닫혀 더 이상 제출할 수 없습니다.' using errcode = '22023';
  end if;
  if v_submission.status not in ('DRAFT', 'WITHDRAWN') then
    raise exception '이미 제출되었거나 합의된 자료입니다.' using errcode = '22023';
  end if;

  select count(*), count(*) filter (where jsonb_array_length(issues) > 0)
    into v_line_count, v_error_count
    from core.demand_submission_line
   where submission_id = p_submission_id;

  if v_line_count = 0 then
    raise exception '제출할 항목이 없습니다.' using errcode = '22023';
  end if;
  -- 검증 체크리스트: ERROR 행이 있으면 제출 완료로 바뀌지 않는다.
  if v_error_count > 0 then
    raise exception '오류가 있는 항목(%건)을 수정한 뒤 제출하세요.', v_error_count using errcode = '22023';
  end if;

  v_previous_status := v_submission.status;

  update core.demand_submission
     set status = 'SUBMITTED', submitted_by = v_actor, submitted_at = clock_timestamp(),
         last_modified_by = v_actor, last_modified_at = clock_timestamp(), version = version + 1
   where submission_id = p_submission_id
   returning * into v_submission;

  insert into core.demand_submission_event (
    submission_id, event_type, previous_status, next_status, version, actor, actor_name, payload_snapshot
  ) values (
    p_submission_id, 'SUBMITTED', v_previous_status, v_submission.status, v_submission.version,
    v_actor, core.order_actor_name(v_actor), to_jsonb(v_submission)
  );

  -- 제출 완료 시 해당 부서의 반복 미제출 알림을 즉시 중단한다(구현 체크리스트).
  perform core.cancel_notification_series(
    'DEMAND_SUBMISSION', v_submission.cycle_id::text || ':' || v_submission.department
  );

  return v_submission;
end;
$$;

create or replace function core.withdraw_demand_submission(p_submission_id uuid, p_reason text)
returns core.demand_submission
language plpgsql
security definer
set search_path = core, public, pg_temp
as $$
declare
  v_actor uuid := auth.uid();
  v_department text;
  v_submission core.demand_submission%rowtype;
  v_previous_status text;
  v_cycle core.planning_cycle%rowtype;
  v_series_id text;
  v_recipients uuid[];
begin
  if v_actor is null or not core.is_active_user(v_actor) then
    raise exception '로그인한 활성 사용자만 회수할 수 있습니다.' using errcode = '42501';
  end if;
  if not core.has_permission('DEMAND_SUBMIT', v_actor) then
    raise exception '부서 수요 제출 권한이 없습니다.' using errcode = '42501';
  end if;
  if nullif(btrim(p_reason), '') is null then
    raise exception '회수 사유는 필수입니다.' using errcode = '22023';
  end if;

  select department into v_department from core.app_user where user_id = v_actor;

  select * into v_submission from core.demand_submission where submission_id = p_submission_id for update;
  if not found then
    raise exception '제출본을 찾을 수 없습니다.' using errcode = 'P0002';
  end if;
  if v_submission.department is distinct from v_department then
    raise exception '다른 부서의 제출본은 회수할 수 없습니다.' using errcode = '42501';
  end if;

  select * into v_cycle from core.planning_cycle where cycle_id = v_submission.cycle_id;
  -- fix round 1 — 닫힌 취합 주기에서는 회수도 막는다(이미 확정된 이력을 건드리지 않는다).
  if not v_cycle.is_active then
    raise exception '취합 주기가 닫혀 더 이상 회수할 수 없습니다.' using errcode = '22023';
  end if;
  if v_submission.status <> 'SUBMITTED' then
    raise exception '제출된 자료만 회수할 수 있습니다.' using errcode = '22023';
  end if;
  v_previous_status := v_submission.status;

  update core.demand_submission
     set status = 'WITHDRAWN', withdrawn_by = v_actor, withdrawn_at = clock_timestamp(),
         withdraw_reason = btrim(p_reason),
         last_modified_by = v_actor, last_modified_at = clock_timestamp(), version = version + 1
   where submission_id = p_submission_id
   returning * into v_submission;

  insert into core.demand_submission_event (
    submission_id, event_type, previous_status, next_status, version, actor, actor_name, reason, payload_snapshot
  ) values (
    p_submission_id, 'WITHDRAWN', v_previous_status, v_submission.status, v_submission.version,
    v_actor, core.order_actor_name(v_actor), btrim(p_reason), to_jsonb(v_submission)
  );

  -- 마감일이 지난 뒤 회수하면 반복 미제출 알림을 즉시 재개한다(컨트롤러 판정 5).
  -- v_cycle은 위에서 이미 조회했다(닫힌 주기 여부 확인 때).
  if v_cycle.submission_deadline is not null
     and (clock_timestamp() at time zone 'Asia/Seoul')::date > v_cycle.submission_deadline then
    v_series_id := v_submission.cycle_id::text || ':' || v_submission.department;
    select array_agg(u.user_id) into v_recipients
      from core.app_user u
      join core.role_permission rp on rp.job_role = u.job_role
     where u.active and u.department = v_submission.department and rp.permission_code = 'DEMAND_SUBMIT';
    if coalesce(array_length(v_recipients, 1), 0) > 0 then
      perform core.schedule_demand_submission_reminder(v_series_id, clock_timestamp(), v_recipients);
    end if;
  end if;

  return v_submission;
end;
$$;

create or replace function core.agree_demand_submission(p_submission_id uuid)
returns core.demand_submission
language plpgsql
security definer
set search_path = core, public, pg_temp
as $$
declare
  v_actor uuid := auth.uid();
  v_submission core.demand_submission%rowtype;
  v_previous_status text;
begin
  if v_actor is null or not core.is_active_user(v_actor) then
    raise exception '로그인한 활성 사용자만 합의를 확정할 수 있습니다.' using errcode = '42501';
  end if;
  if not (core.has_permission('PLAN_CONFIRM', v_actor) or core.is_admin(v_actor)) then
    raise exception 'SCM 품목담당자 또는 관리자만 합의를 확정할 수 있습니다.' using errcode = '42501';
  end if;

  select * into v_submission from core.demand_submission where submission_id = p_submission_id for update;
  if not found then
    raise exception '제출본을 찾을 수 없습니다.' using errcode = 'P0002';
  end if;
  -- fix round 2 — 닫힌 취합 주기(재개로 이미 새 cycle_id가 열렸을 수도 있는, 옛 cycle_id에 묶인
  -- 행)에서는 합의도 막는다. save/submit/withdraw와 같은 규칙이다.
  if not exists (select 1 from core.planning_cycle c where c.cycle_id = v_submission.cycle_id and c.is_active) then
    raise exception '취합 주기가 닫혀 더 이상 합의를 확정할 수 없습니다.' using errcode = '22023';
  end if;
  if v_submission.status <> 'SUBMITTED' then
    raise exception '제출완료 상태만 합의를 확정할 수 있습니다.' using errcode = '22023';
  end if;
  v_previous_status := v_submission.status;

  update core.demand_submission
     set status = 'AGREED', agreed_by = v_actor, agreed_at = clock_timestamp(),
         last_modified_by = v_actor, last_modified_at = clock_timestamp(), version = version + 1
   where submission_id = p_submission_id
   returning * into v_submission;

  insert into core.demand_submission_event (
    submission_id, event_type, previous_status, next_status, version, actor, actor_name, payload_snapshot
  ) values (
    p_submission_id, 'AGREED', v_previous_status, v_submission.status, v_submission.version,
    v_actor, core.order_actor_name(v_actor), to_jsonb(v_submission)
  );

  return v_submission;
end;
$$;


-- ══ 6. 마감 경과 후 반복 미제출 알림 예약(Cron 전용) ══════════════
--
-- Task 3의 core.schedule_demand_submission_reminder / core.cancel_notification_series를 그대로
-- 쓴다. 여기서는 "언제 첫 알림을 예약할지"만 판정한다 — 10분 반복 자체는 Task 3의
-- core.finish_notification이 DEMAND_SUBMISSION_OVERDUE 템플릿을 계속 재예약하며 이어간다.
-- 첫 예약 시각(마감일 + 1일 00:00 Asia/Seoul)을 고정 값으로 써서, 10분마다 이 함수를 다시
-- 불러도 core.enqueue_notification의 dedupe_key가 겹쳐 중복 예약되지 않는다.

create or replace function core.raise_demand_submission_reminders()
returns integer
language plpgsql
security definer
set search_path = core, public, pg_temp
as $$
declare
  v_cycle record;
  v_department text;
  v_first_at timestamptz;
  v_series_id text;
  v_recipients uuid[];
  v_count integer := 0;
begin
  for v_cycle in
    select cycle_id, plan_month, submission_deadline
      from core.planning_cycle
     where is_active
       and (clock_timestamp() at time zone 'Asia/Seoul')::date > submission_deadline
  loop
    -- date를 timestamptz로 바로 "at time zone"하면 세션 timezone GUC를 거쳐 먼저
    -- timestamptz로 캐스팅된 뒤 다시 변환되어, 세션 timezone에 따라 결과가 달라지는 버그가
    -- 난다(Supabase 기본 UTC 세션에서 18시간까지 밀림). date를 먼저 명시적으로 timestamp로
    -- 캐스팅해 "Asia/Seoul 벽시계 자정"으로 한 번만 해석해야 세션 timezone과 무관하다.
    v_first_at := (v_cycle.submission_deadline + 1)::timestamp at time zone 'Asia/Seoul';

    -- 필수 제출 부서 = DEMAND_SUBMIT 권한을 가진 활성 사용자가 있는 부서(컨트롤러 판정 2).
    for v_department in
      select distinct u.department
        from core.app_user u
        join core.role_permission rp on rp.job_role = u.job_role
       where u.active and rp.permission_code = 'DEMAND_SUBMIT' and u.department is not null
    loop
      if not exists (
        select 1 from core.demand_submission s
         where s.cycle_id = v_cycle.cycle_id
           and s.department = v_department
           and s.status in ('SUBMITTED', 'AGREED')
      ) then
        v_series_id := v_cycle.cycle_id::text || ':' || v_department;
        select array_agg(u.user_id) into v_recipients
          from core.app_user u
          join core.role_permission rp on rp.job_role = u.job_role
         where u.active and u.department = v_department and rp.permission_code = 'DEMAND_SUBMIT';
        if coalesce(array_length(v_recipients, 1), 0) > 0 then
          v_count := v_count + core.schedule_demand_submission_reminder(v_series_id, v_first_at, v_recipients);
        end if;
      end if;
    end loop;
  end loop;
  return v_count;
end;
$$;


-- ══ 7. 조회 뷰 ════════════════════════════════════════════════════

create or replace view analytics.v_planning_cycle
with (security_invoker = true)
as
select cycle_id, plan_month, submission_deadline, status, is_active, opened_by, opened_at, closed_by, closed_at
  from core.planning_cycle;

create or replace view analytics.v_demand_submission_status
with (security_invoker = true)
as
select
  s.submission_id, s.cycle_id, s.plan_month, s.department, s.status,
  c.submission_deadline,
  coalesce(l.total_line_count, 0) as total_line_count,
  coalesce(l.error_line_count, 0) as error_line_count,
  s.submitted_by, core.order_actor_name(s.submitted_by) as submitted_by_name, s.submitted_at,
  s.withdrawn_by, core.order_actor_name(s.withdrawn_by) as withdrawn_by_name, s.withdrawn_at, s.withdraw_reason,
  s.agreed_by, core.order_actor_name(s.agreed_by) as agreed_by_name, s.agreed_at,
  s.last_modified_by, core.order_actor_name(s.last_modified_by) as last_modified_by_name, s.last_modified_at,
  s.version, s.created_at,
  (
    s.status in ('DRAFT', 'WITHDRAWN')
    -- core.raise_demand_submission_reminders와 같은 이유로 date를 먼저 timestamp로 캐스팅한다
    -- (세션 timezone에 좌우되지 않는 단일 변환 — 아래 함수 주석 참고).
    and clock_timestamp() > ((c.submission_deadline + 1)::timestamp at time zone 'Asia/Seoul')
  ) as is_overdue
from core.demand_submission s
join core.planning_cycle c on c.cycle_id = s.cycle_id
left join (
  select submission_id,
         count(*) as total_line_count,
         count(*) filter (where jsonb_array_length(issues) > 0) as error_line_count
    from core.demand_submission_line
   group by submission_id
) l on l.submission_id = s.submission_id;

comment on view analytics.v_demand_submission_status is
  'Task 7 — SCM 취합 화면용. 제출 여부·오류 건수·마지막 수정자와 시각을 한 행에 모은다';

create or replace view analytics.v_demand_submission_line
with (security_invoker = true)
as
select
  l.line_id, l.submission_id, l.line_no, l.raw_item_code, l.item_id, im.item_name,
  l.qty, l.need_month, l.issues, l.created_at
from core.demand_submission_line l
left join core.v_item_master im on im.item_id = l.item_id;


-- ══ 8. RLS와 권한 ═══════════════════════════════════════════════

alter table core.planning_cycle enable row level security;
alter table core.demand_submission enable row level security;
alter table core.demand_submission_line enable row level security;
alter table core.demand_submission_event enable row level security;

drop policy if exists planning_cycle_read on core.planning_cycle;
create policy planning_cycle_read on core.planning_cycle
  for select to authenticated using (true);

-- 검증 체크리스트: 다른 부서 제출본은 RLS로도 보이지 않는다. 본인 부서(DEMAND_SUBMIT) 또는
-- 취합 권한(DEMAND_CONSOLIDATE·PLAN_CONFIRM)·ADMIN만 조회할 수 있다(컨트롤러 판정 6).
drop policy if exists demand_submission_read_own_or_scm on core.demand_submission;
create policy demand_submission_read_own_or_scm on core.demand_submission
  for select to authenticated
  using (
    (
      core.has_permission('DEMAND_SUBMIT')
      and department = (select u.department from core.app_user u where u.user_id = auth.uid())
    )
    or core.has_permission('DEMAND_CONSOLIDATE')
    or core.has_permission('PLAN_CONFIRM')
    or core.is_admin()
  );

drop policy if exists demand_submission_line_read on core.demand_submission_line;
create policy demand_submission_line_read on core.demand_submission_line
  for select to authenticated
  using (exists (
    select 1 from core.demand_submission s where s.submission_id = demand_submission_line.submission_id
  ));

drop policy if exists demand_submission_event_read on core.demand_submission_event;
create policy demand_submission_event_read on core.demand_submission_event
  for select to authenticated
  using (exists (
    select 1 from core.demand_submission s where s.submission_id = demand_submission_event.submission_id
  ));

revoke all on core.planning_cycle, core.demand_submission, core.demand_submission_line, core.demand_submission_event
  from anon, public;
-- 모든 쓰기는 위 security definer 함수를 통해서만 한다 — 직접 INSERT/UPDATE/DELETE는 막는다
-- (검증 체크리스트: 서버와 RLS 모두에서 거절). 함수 안의 부서 비교가 최종 방어선이다.
revoke insert, update, delete on
  core.planning_cycle, core.demand_submission, core.demand_submission_line, core.demand_submission_event
  from authenticated;
grant select on
  core.planning_cycle, core.demand_submission, core.demand_submission_line, core.demand_submission_event
  to authenticated;
grant select on
  analytics.v_planning_cycle, analytics.v_demand_submission_status, analytics.v_demand_submission_line
  to authenticated;

revoke all on function core.submission_deadline(date) from public, anon;
grant execute on function core.submission_deadline(date) to authenticated, service_role;

revoke all on function core.open_planning_cycle(date) from public, anon;
grant execute on function core.open_planning_cycle(date) to authenticated;

revoke all on function core.close_planning_cycle(uuid) from public, anon;
grant execute on function core.close_planning_cycle(uuid) to authenticated;

revoke all on function core.start_demand_submission(date) from public, anon;
grant execute on function core.start_demand_submission(date) to authenticated;

revoke all on function core.save_demand_submission_lines(uuid, jsonb) from public, anon;
grant execute on function core.save_demand_submission_lines(uuid, jsonb) to authenticated;

revoke all on function core.submit_demand_submission(uuid) from public, anon;
grant execute on function core.submit_demand_submission(uuid) to authenticated;

revoke all on function core.withdraw_demand_submission(uuid, text) from public, anon;
grant execute on function core.withdraw_demand_submission(uuid, text) to authenticated;

revoke all on function core.agree_demand_submission(uuid) from public, anon;
grant execute on function core.agree_demand_submission(uuid) to authenticated;

revoke all on function core.raise_demand_submission_reminders() from public, anon, authenticated;
grant execute on function core.raise_demand_submission_reminders() to service_role;

revoke all on function core.reject_demand_submission_event_mutation() from public, anon, authenticated;
revoke all on function core.guard_demand_submission_cycle_active() from public, anon, authenticated;
revoke all on function core.guard_demand_submission_line_cycle_active() from public, anon, authenticated;


-- ══ 9. 수동 적용 후 확인 쿼리 ═════════════════════════════════════

-- 마감일 계산이 lib/demand/model.ts의 submissionDeadline과 값이 같은지 확인한다.
select
  core.submission_deadline('2026-04-01') as expect_2026_03_30,
  core.submission_deadline('2026-03-01') as expect_2026_02_27,
  core.submission_deadline('2028-03-01') as expect_2028_02_28,
  core.submission_deadline('2026-05-01') as expect_2026_04_29;

-- 동일 부서·기준월 활성 제출본이 하나만 있는지 확인한다.
select cycle_id, department, count(*)
  from core.demand_submission
 group by cycle_id, department
having count(*) > 1;
-- 기대: 0행 (unique 제약이 이미 막지만, 운영 데이터로 재확인한다)

-- SCM 취합 화면이 읽을 상태 요약.
select department, status, total_line_count, error_line_count, last_modified_by_name, last_modified_at
  from analytics.v_demand_submission_status
 order by plan_month desc, department;

-- 아래 실패 검증은 SQL Editor에서 각 역할의 실제 UUID로 실행한다.
-- begin;
-- set local role authenticated;
-- select set_config('request.jwt.claim.sub', '<다른 부서 사용자 UUID>', true);
-- select core.save_demand_submission_lines('<다른 부서 제출본 UUID>', '[]'::jsonb);
-- rollback;
-- 기대: "다른 부서의 제출본은 수정할 수 없습니다." (42501)

-- begin;
-- set local role authenticated;
-- select set_config('request.jwt.claim.sub', '<제출 부서 사용자 UUID>', true);
-- select core.submit_demand_submission('<ERROR 행이 있는 제출본 UUID>');
-- rollback;
-- 기대: "오류가 있는 항목(N건)을 수정한 뒤 제출하세요." (22023)
