-- Task 2 · 공통 승인 및 감사 이력 엔진
--
-- 품목 정책, 우선 배정, 이벤트 추가 수요, 최종 발주계획이 같은 승인 원장을 사용합니다.
-- 도메인별 승인 후처리는 Task 5/8/9에서 core.decide_approval() 내부의 타입별 처리로 연결합니다.
-- 실제 Supabase 적용은 사용자가 SQL Editor에서 수동으로 수행합니다.


-- ══ 1. 승인 요청 원장과 append-only 이벤트 ═══════════════════

create table if not exists core.approval_request (
  approval_id       uuid primary key default gen_random_uuid(),
  approval_type     text not null check (approval_type in (
    'ITEM_POLICY', 'ALLOC_PRIORITY', 'EVENT_ORDER', 'PURCHASE_PLAN'
  )),
  target_type       text not null check (btrim(target_type) <> ''),
  target_id         text not null check (btrim(target_id) <> ''),
  payload           jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  status            text not null default 'PENDING' check (status in (
    'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'
  )),
  reason_code       text,
  reason_text       text,
  requested_by      uuid not null references auth.users(id) on delete restrict,
  requester_name    text not null check (btrim(requester_name) <> ''),
  requested_at      timestamptz not null default now(),
  decided_by        uuid references auth.users(id) on delete restrict,
  decider_name      text,
  decided_at        timestamptz,
  decision_comment  text,
  constraint approval_request_decision_check check (
    (status = 'PENDING' and decided_by is null and decider_name is null
        and decided_at is null and decision_comment is null)
    or (status = 'APPROVED' and decided_by is not null
        and nullif(btrim(decider_name), '') is not null and decided_at is not null)
    or (status = 'REJECTED' and decided_by is not null and decided_at is not null
        and nullif(btrim(decider_name), '') is not null
        and nullif(btrim(decision_comment), '') is not null)
    or (status = 'CANCELLED' and decided_by is not null
        and nullif(btrim(decider_name), '') is not null and decided_at is not null)
  )
);

-- 개발 중 이전 초안을 먼저 적용한 DB에서도 이름 열을 보존적으로 보강합니다.
alter table core.approval_request add column if not exists requester_name text;
alter table core.approval_request add column if not exists decider_name text;

update core.approval_request r
   set requester_name = coalesce(nullif(btrim(u.name), ''), nullif(btrim(u.email), ''), r.requested_by::text)
  from core.app_user u
 where u.user_id = r.requested_by
   and nullif(btrim(r.requester_name), '') is null;

update core.approval_request
   set requester_name = requested_by::text
 where nullif(btrim(requester_name), '') is null;

update core.approval_request r
   set decider_name = coalesce(nullif(btrim(u.name), ''), nullif(btrim(u.email), ''), r.decided_by::text)
  from core.app_user u
 where u.user_id = r.decided_by
   and r.decided_by is not null
   and nullif(btrim(r.decider_name), '') is null;

update core.approval_request
   set decider_name = decided_by::text
 where decided_by is not null
   and nullif(btrim(decider_name), '') is null;

alter table core.approval_request alter column requester_name set not null;
alter table core.approval_request drop constraint if exists approval_request_decision_check;
alter table core.approval_request add constraint approval_request_decision_check check (
  (status = 'PENDING' and decided_by is null and decider_name is null
      and decided_at is null and decision_comment is null)
  or (status = 'APPROVED' and decided_by is not null
      and nullif(btrim(decider_name), '') is not null and decided_at is not null)
  or (status = 'REJECTED' and decided_by is not null and decided_at is not null
      and nullif(btrim(decider_name), '') is not null
      and nullif(btrim(decision_comment), '') is not null)
  or (status = 'CANCELLED' and decided_by is not null
      and nullif(btrim(decider_name), '') is not null and decided_at is not null)
);

create table if not exists core.approval_event (
  event_id          bigint generated by default as identity primary key,
  approval_id       uuid not null references core.approval_request(approval_id) on delete restrict,
  event_type        text not null check (event_type in ('REQUESTED', 'APPROVED', 'REJECTED', 'CANCELLED')),
  previous_status   text check (previous_status is null or previous_status in ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
  next_status       text not null check (next_status in ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
  actor             uuid not null references auth.users(id) on delete restrict,
  comment           text,
  payload_snapshot  jsonb not null,
  at                timestamptz not null default now(),
  constraint approval_event_transition_check check (
    (event_type = 'REQUESTED' and previous_status is null and next_status = 'PENDING')
    or (event_type in ('APPROVED', 'REJECTED', 'CANCELLED')
        and previous_status = 'PENDING' and next_status = event_type)
  )
);

create index if not exists approval_request_inbox_idx
  on core.approval_request (status, approval_type, requested_at desc);
create index if not exists approval_request_requester_idx
  on core.approval_request (requested_by, requested_at desc);
create index if not exists approval_request_target_idx
  on core.approval_request (target_type, target_id, requested_at desc);
create index if not exists approval_event_request_idx
  on core.approval_event (approval_id, at, event_id);

comment on table core.approval_request is
  'Task 2 공통 승인 원장. 승인 후 도메인 반영은 후속 Task에서 연결합니다';
comment on table core.approval_event is
  'Task 2 승인 상태 변경 append-only 이력. UPDATE와 DELETE는 트리거로도 차단합니다';

create or replace function core.reject_approval_event_mutation()
returns trigger
language plpgsql
set search_path = core, pg_temp
as $$
begin
  raise exception '승인 이벤트 이력은 수정하거나 삭제할 수 없습니다.' using errcode = '42501';
end;
$$;

drop trigger if exists approval_event_append_only on core.approval_event;
create trigger approval_event_append_only
  before update or delete on core.approval_event
  for each row execute function core.reject_approval_event_mutation();


-- ══ 2. 승인 요청 생성 ════════════════════════════════════════

create or replace function core.request_approval(
  p_approval_type text,
  p_target_type text,
  p_target_id text,
  p_payload jsonb default '{}'::jsonb,
  p_reason_code text default null,
  p_reason_text text default null
)
returns uuid
language plpgsql
security definer
set search_path = core, public, pg_temp
as $$
declare
  v_actor uuid := auth.uid();
  v_actor_name text;
  v_required_permission text;
  v_approval_id uuid;
  v_after jsonb;
begin
  if v_actor is null or not core.is_active_user(v_actor) then
    raise exception '로그인한 활성 사용자만 승인 요청을 만들 수 있습니다.' using errcode = '42501';
  end if;

  if p_approval_type is null or p_approval_type not in (
    'ITEM_POLICY', 'ALLOC_PRIORITY', 'EVENT_ORDER', 'PURCHASE_PLAN'
  ) then
    raise exception '지원하지 않는 승인 유형입니다.' using errcode = '22023';
  end if;

  v_required_permission := case p_approval_type
    when 'ITEM_POLICY' then 'ITEM_POLICY_EDIT'
    when 'ALLOC_PRIORITY' then 'ALLOC_MANUAL'
    when 'EVENT_ORDER' then 'DEMAND_CONSOLIDATE'
    when 'PURCHASE_PLAN' then 'PLAN_CONFIRM'
  end;

  if v_required_permission is null or not core.has_permission(v_required_permission, v_actor) then
    raise exception '이 승인 유형을 요청할 업무 권한이 없습니다.' using errcode = '42501';
  end if;

  select coalesce(nullif(btrim(u.name), ''), nullif(btrim(u.email), ''), u.user_id::text)
    into v_actor_name
    from core.app_user u
   where u.user_id = v_actor;

  if nullif(btrim(p_target_type), '') is null or nullif(btrim(p_target_id), '') is null then
    raise exception '승인 대상 유형과 대상 ID는 필수입니다.' using errcode = '22023';
  end if;

  if p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    raise exception '승인 요청 payload는 JSON 객체여야 합니다.' using errcode = '22023';
  end if;

  if p_approval_type = 'EVENT_ORDER' then
    if nullif(btrim(p_payload ->> 'customer'), '') is null then
      raise exception '이벤트 추가 수요의 고객은 필수입니다.' using errcode = '22023';
    end if;
    if nullif(btrim(p_payload ->> 'model'), '') is null then
      raise exception '이벤트 추가 수요의 기종은 필수입니다.' using errcode = '22023';
    end if;
    if jsonb_typeof(p_payload -> 'quantity') is distinct from 'number' then
      raise exception '이벤트 추가 수요의 수량은 양수여야 합니다.' using errcode = '22023';
    end if;
    if (p_payload ->> 'quantity')::numeric <= 0 then
      raise exception '이벤트 추가 수요의 수량은 양수여야 합니다.' using errcode = '22023';
    end if;
  end if;

  insert into core.approval_request (
    approval_type, target_type, target_id, payload,
    reason_code, reason_text, requested_by, requester_name
  ) values (
    p_approval_type, btrim(p_target_type), btrim(p_target_id), p_payload,
    nullif(btrim(p_reason_code), ''), nullif(btrim(p_reason_text), ''), v_actor, v_actor_name
  )
  returning approval_id into v_approval_id;

  select to_jsonb(r) into v_after
    from core.approval_request r
   where r.approval_id = v_approval_id;

  insert into core.approval_event (
    approval_id, event_type, previous_status, next_status,
    actor, comment, payload_snapshot
  ) values (
    v_approval_id, 'REQUESTED', null, 'PENDING',
    v_actor, nullif(btrim(p_reason_text), ''), v_after
  );

  insert into core.audit_log (actor, action, target_type, target_id, before, after)
  values (v_actor, 'APPROVAL_REQUESTED', 'APPROVAL_REQUEST', v_approval_id::text, null, v_after);

  return v_approval_id;
end;
$$;


-- ══ 3. 승인 또는 반려 ════════════════════════════════════════

create or replace function core.decide_approval(
  p_approval_id uuid,
  p_decision text,
  p_decision_comment text default null
)
returns uuid
language plpgsql
security definer
set search_path = core, public, pg_temp
as $$
declare
  v_actor uuid := auth.uid();
  v_actor_name text;
  v_required_permission text;
  v_request core.approval_request%rowtype;
  v_before jsonb;
  v_after jsonb;
begin
  if v_actor is null or not core.is_active_user(v_actor) then
    raise exception '로그인한 활성 사용자만 승인 요청을 처리할 수 있습니다.' using errcode = '42501';
  end if;

  if p_decision is null or p_decision not in ('APPROVED', 'REJECTED') then
    raise exception '승인 결과는 APPROVED 또는 REJECTED여야 합니다.' using errcode = '22023';
  end if;

  select * into v_request
    from core.approval_request
   where approval_id = p_approval_id
   for update;

  if not found then
    raise exception '승인 요청을 찾을 수 없습니다.' using errcode = 'P0002';
  end if;

  v_required_permission := case v_request.approval_type
    when 'ITEM_POLICY' then 'ITEM_POLICY_APPROVE'
    when 'ALLOC_PRIORITY' then 'ALLOC_PRIORITY_APPROVE'
    when 'EVENT_ORDER' then 'EVENT_ORDER_APPROVE'
    when 'PURCHASE_PLAN' then 'PLAN_APPROVE'
  end;

  if v_required_permission is null or not core.has_permission(v_required_permission, v_actor) then
    raise exception '이 승인 유형을 결정할 업무 권한이 없습니다.' using errcode = '42501';
  end if;

  select coalesce(nullif(btrim(u.name), ''), nullif(btrim(u.email), ''), u.user_id::text)
    into v_actor_name
    from core.app_user u
   where u.user_id = v_actor;

  if v_request.requested_by = v_actor then
    raise exception '자신이 요청한 승인은 직접 결정할 수 없습니다.' using errcode = '42501';
  end if;

  if v_request.status <> 'PENDING' then
    raise exception '이미 처리되었거나 취소된 승인 요청입니다.' using errcode = '22023';
  end if;

  if p_decision = 'REJECTED' and nullif(btrim(p_decision_comment), '') is null then
    raise exception '반려 의견은 필수입니다.' using errcode = '22023';
  end if;

  v_before := to_jsonb(v_request);

  update core.approval_request
     set status = p_decision,
         decided_by = v_actor,
         decider_name = v_actor_name,
         decided_at = clock_timestamp(),
         decision_comment = nullif(btrim(p_decision_comment), '')
   where approval_id = p_approval_id;

  select to_jsonb(r) into v_after
    from core.approval_request r
   where r.approval_id = p_approval_id;

  insert into core.approval_event (
    approval_id, event_type, previous_status, next_status,
    actor, comment, payload_snapshot
  ) values (
    p_approval_id, p_decision, 'PENDING', p_decision,
    v_actor, nullif(btrim(p_decision_comment), ''), v_after
  );

  insert into core.audit_log (actor, action, target_type, target_id, before, after)
  values (
    v_actor,
    case p_decision when 'APPROVED' then 'APPROVAL_APPROVED' else 'APPROVAL_REJECTED' end,
    'APPROVAL_REQUEST', p_approval_id::text, v_before, v_after
  );

  return p_approval_id;
end;
$$;


-- ══ 4. 사용자별 조회 뷰 ══════════════════════════════════════

create or replace view analytics.v_my_approval_inbox
with (security_invoker = true)
as
select
  r.approval_id, r.approval_type, r.target_type, r.target_id, r.payload,
  r.status, r.reason_code, r.reason_text,
  r.requested_by, r.requested_at,
  r.decided_by, r.decided_at, r.decision_comment,
  r.requester_name, r.decider_name
from core.approval_request r
where r.status = 'PENDING'
  and r.requested_by <> auth.uid()
  and core.has_permission(
    case r.approval_type
      when 'ITEM_POLICY' then 'ITEM_POLICY_APPROVE'
      when 'ALLOC_PRIORITY' then 'ALLOC_PRIORITY_APPROVE'
      when 'EVENT_ORDER' then 'EVENT_ORDER_APPROVE'
      when 'PURCHASE_PLAN' then 'PLAN_APPROVE'
    end
  );

create or replace view analytics.v_approval_history
with (security_invoker = true)
as
select
  r.approval_id, r.approval_type, r.target_type, r.target_id, r.payload,
  r.status, r.reason_code, r.reason_text,
  r.requested_by, r.requested_at,
  r.decided_by, r.decided_at, r.decision_comment,
  r.requester_name, r.decider_name
from core.approval_request r
where r.requested_by = auth.uid()
   or r.decided_by = auth.uid()
   or core.has_permission(
     case r.approval_type
       when 'ITEM_POLICY' then 'ITEM_POLICY_APPROVE'
       when 'ALLOC_PRIORITY' then 'ALLOC_PRIORITY_APPROVE'
       when 'EVENT_ORDER' then 'EVENT_ORDER_APPROVE'
       when 'PURCHASE_PLAN' then 'PLAN_APPROVE'
     end
   );

comment on view analytics.v_my_approval_inbox is
  '현재 사용자가 권한으로 처리할 수 있고 본인이 요청하지 않은 PENDING 승인';
comment on view analytics.v_approval_history is
  '현재 사용자의 요청·처리 이력과 승인 권한 범위 이력';


-- ══ 5. RLS와 실행 권한 ═══════════════════════════════════════

alter table core.approval_request enable row level security;
alter table core.approval_event enable row level security;

drop policy if exists approval_request_read_related on core.approval_request;
create policy approval_request_read_related
  on core.approval_request
  for select
  to authenticated
  using (
    requested_by = auth.uid()
    or decided_by = auth.uid()
    or core.has_permission(
      case approval_type
        when 'ITEM_POLICY' then 'ITEM_POLICY_APPROVE'
        when 'ALLOC_PRIORITY' then 'ALLOC_PRIORITY_APPROVE'
        when 'EVENT_ORDER' then 'EVENT_ORDER_APPROVE'
        when 'PURCHASE_PLAN' then 'PLAN_APPROVE'
      end
    )
  );

drop policy if exists approval_event_read_related on core.approval_event;
create policy approval_event_read_related
  on core.approval_event
  for select
  to authenticated
  using (
    exists (
      select 1
        from core.approval_request r
       where r.approval_id = approval_event.approval_id
    )
  );

revoke all on core.approval_request, core.approval_event from anon, public;
revoke insert, update, delete on core.approval_request, core.approval_event from authenticated;
grant select on core.approval_request, core.approval_event to authenticated;
grant select on analytics.v_my_approval_inbox, analytics.v_approval_history to authenticated;

revoke all on function core.request_approval(text, text, text, jsonb, text, text) from public, anon;
revoke all on function core.decide_approval(uuid, text, text) from public, anon;
grant execute on function core.request_approval(text, text, text, jsonb, text, text) to authenticated;
grant execute on function core.decide_approval(uuid, text, text) to authenticated;
revoke all on function core.reject_approval_event_mutation() from public, anon, authenticated;


-- ══ 6. 수동 적용 후 확인 쿼리 ════════════════════════════════

select approval_type, status, requested_by, decided_by
from core.approval_request
order by requested_at desc;

select action, target_type, target_id
from core.audit_log
where target_type = 'APPROVAL_REQUEST'
order by at desc;

select c.relname, c.reloptions
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
where n.nspname = 'analytics'
  and c.relname in ('v_my_approval_inbox', 'v_approval_history')
order by c.relname;
-- 기대: 두 뷰 모두 reloptions에 security_invoker=true

select r.approval_id, r.status,
       count(distinct e.event_id) as event_count,
       count(distinct a.id) as audit_count
from core.approval_request r
left join core.approval_event e on e.approval_id = r.approval_id
left join core.audit_log a
  on a.target_type = 'APPROVAL_REQUEST'
 and a.target_id = r.approval_id::text
group by r.approval_id, r.status
order by max(r.requested_at) desc;
-- 기대: 요청 직후 event_count=1/audit_count=1, 승인·반려 후 각각 2

-- 아래 실패 검증은 SQL Editor에서 요청자와 승인자의 실제 UUID를 넣고 각각 실행합니다.
-- begin;
-- set local role authenticated;
-- select set_config('request.jwt.claim.sub', '<검증할 사용자 UUID>', true);
-- select core.decide_approval('<승인 요청 UUID>', 'APPROVED', '검증');
-- rollback;
-- 1) 권한 없는 USER UUID로 core.request_approval(...) → SQLSTATE 42501
-- 2) 요청자 본인 UUID → "자신이 요청한 승인은 직접 결정할 수 없습니다."
-- 3) 승인자 UUID로 세 번째 인자를 ''로 하고 REJECTED → "반려 의견은 필수입니다."


-- ══ Task 3 · 알림 Outbox와 채널별 발송 이력 ═════════════════
--
-- 업무 트랜잭션은 알림을 직접 보내지 않고 Outbox에만 기록합니다. 이메일과 앱 알림은
-- CRON_SECRET으로 보호된 서버 작업이 due 항목을 claim한 뒤 채널별 결과를 남깁니다.

create table if not exists core.notification_outbox (
  notification_id    uuid primary key default gen_random_uuid(),
  dedupe_key          text not null check (btrim(dedupe_key) <> ''),
  template_code       text not null check (btrim(template_code) <> ''),
  recipient_user_id   uuid not null references auth.users(id) on delete restrict,
  channel             text not null check (channel in ('IN_APP', 'EMAIL')),
  scheduled_at        timestamptz not null,
  payload             jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  status              text not null default 'PENDING' check (status in ('PENDING', 'PROCESSING', 'SENT', 'FAILED', 'CANCELLED')),
  attempt_count       integer not null default 0 check (attempt_count >= 0),
  max_attempts        integer not null default 5 check (max_attempts between 1 and 20),
  claimed_at          timestamptz,
  claimed_by          uuid,
  claim_token         uuid,
  claim_expires_at    timestamptz,
  last_error          text,
  finished_at         timestamptz,
  created_at          timestamptz not null default now(),
  unique (dedupe_key, recipient_user_id, channel)
);

-- 이미 Task 3 초안을 적용한 DB에서도 drop/recreate 없이 처리 임대 열을 보강합니다.
alter table core.notification_outbox add column if not exists max_attempts integer not null default 5;
alter table core.notification_outbox add column if not exists claim_token uuid;
alter table core.notification_outbox add column if not exists claim_expires_at timestamptz;
alter table core.notification_outbox add column if not exists last_error text;

update core.notification_outbox
   set claim_expires_at = clock_timestamp()
 where status = 'PROCESSING'
   and claim_expires_at is null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
     where conname = 'notification_outbox_max_attempts_check'
       and conrelid = 'core.notification_outbox'::regclass
  ) then
    alter table core.notification_outbox
      add constraint notification_outbox_max_attempts_check check (max_attempts between 1 and 20);
  end if;
end;
$$;

create table if not exists core.notification_delivery (
  delivery_id         bigint generated by default as identity primary key,
  notification_id     uuid not null references core.notification_outbox(notification_id) on delete restrict,
  recipient_user_id   uuid not null references auth.users(id) on delete restrict,
  recipient_email     text,
  channel             text not null check (channel in ('IN_APP', 'EMAIL')),
  status              text not null check (status in ('SUCCESS', 'FAILED')),
  attempt_number      integer check (attempt_number is null or attempt_number > 0),
  retryable           boolean,
  attempted_at        timestamptz not null default now(),
  error_message       text,
  external_message_id text
);

alter table core.notification_delivery add column if not exists attempt_number integer;
alter table core.notification_delivery add column if not exists retryable boolean;

create table if not exists core.user_notification (
  user_notification_id bigint generated by default as identity primary key,
  notification_id      uuid not null unique references core.notification_outbox(notification_id) on delete restrict,
  recipient_user_id    uuid not null references auth.users(id) on delete restrict,
  created_at           timestamptz not null default now(),
  read_at              timestamptz
);

create index if not exists notification_outbox_due_idx
  on core.notification_outbox (status, scheduled_at, created_at);
create index if not exists notification_outbox_recipient_idx
  on core.notification_outbox (recipient_user_id, created_at desc);
create index if not exists notification_delivery_notice_idx
  on core.notification_delivery (notification_id, attempted_at desc);
create index if not exists user_notification_recipient_idx
  on core.user_notification (recipient_user_id, read_at, created_at desc);

comment on table core.notification_outbox is
  'Task 3 발송 대기 원장. 업무 트랜잭션은 외부 통신 대신 이 테이블에 중복 없이 예약합니다';
comment on table core.notification_delivery is
  '앱 알림과 이메일의 성공·실패를 채널별로 보존하는 append-only 이력';
comment on table core.user_notification is
  '사용자 앱 알림과 읽음 상태. 이메일 실패와 독립적으로 유지합니다';


-- ══ 7. 예약·claim·완료 함수 ══════════════════════════════════

create or replace function core.enqueue_notification(
  p_dedupe_key text,
  p_template_code text,
  p_recipient_user_id uuid,
  p_channel text,
  p_scheduled_at timestamptz,
  p_payload jsonb default '{}'::jsonb
)
returns uuid
language plpgsql
security definer
set search_path = core, public, pg_temp
as $$
declare
  v_notification_id uuid;
begin
  if nullif(btrim(p_dedupe_key), '') is null
     or nullif(btrim(p_template_code), '') is null
     or p_recipient_user_id is null
     or p_scheduled_at is null
     or p_channel not in ('IN_APP', 'EMAIL')
     or p_payload is null
     or jsonb_typeof(p_payload) <> 'object' then
    raise exception '알림 예약 입력값이 올바르지 않습니다.' using errcode = '22023';
  end if;

  if not exists (
    select 1 from core.app_user u
     where u.user_id = p_recipient_user_id and u.active
  ) then
    raise exception '활성 수신자를 찾을 수 없습니다.' using errcode = '22023';
  end if;

  insert into core.notification_outbox (
    dedupe_key, template_code, recipient_user_id, channel, scheduled_at, payload
  ) values (
    btrim(p_dedupe_key), btrim(p_template_code), p_recipient_user_id,
    p_channel, p_scheduled_at, p_payload
  )
  on conflict (dedupe_key, recipient_user_id, channel) do nothing
  returning notification_id into v_notification_id;

  if v_notification_id is null then
    select o.notification_id into v_notification_id
      from core.notification_outbox o
     where o.dedupe_key = btrim(p_dedupe_key)
       and o.recipient_user_id = p_recipient_user_id
       and o.channel = p_channel;
  end if;

  return v_notification_id;
end;
$$;

drop function if exists core.claim_due_notifications(integer, uuid);

create function core.claim_due_notifications(
  p_limit integer default 50,
  p_worker_id uuid default gen_random_uuid()
)
returns table (
  notification_id uuid,
  claim_token uuid,
  template_code text,
  recipient_user_id uuid,
  recipient_email text,
  channel text,
  payload jsonb
)
language plpgsql
security definer
set search_path = core, public, pg_temp
as $$
begin
  if p_limit < 1 or p_limit > 50 then
    raise exception '한 번에 처리할 알림 수는 1~50건이어야 합니다.' using errcode = '22023';
  end if;
  if p_worker_id is null then
    raise exception '알림 작업자 식별자는 필수입니다.' using errcode = '22023';
  end if;

  -- 임대시간이 끝났고 최대 시도 횟수에 도달한 작업은 최종 실패 이력을 남깁니다.
  with exhausted as (
    update core.notification_outbox as o
       set status = 'FAILED',
           finished_at = clock_timestamp(),
           last_error = '처리 임대 만료 후 최대 재시도 횟수를 초과했습니다.',
           claimed_by = null,
           claim_token = null,
           claim_expires_at = null
     where o.status = 'PROCESSING'
       and o.claim_expires_at <= clock_timestamp()
       and o.attempt_count >= o.max_attempts
    returning o.notification_id, o.recipient_user_id, o.channel, o.attempt_count, o.last_error
  )
  insert into core.notification_delivery (
    notification_id, recipient_user_id, recipient_email, channel,
    status, attempt_number, retryable, error_message
  )
  select e.notification_id, e.recipient_user_id, nullif(btrim(u.email), ''),
         e.channel, 'FAILED', e.attempt_count, false, e.last_error
    from exhausted e
    left join core.app_user u on u.user_id = e.recipient_user_id;

  -- 작업자가 중단한 PROCESSING 행은 임대 만료 뒤 같은 알림 ID로 다시 처리합니다.
  update core.notification_outbox as o
     set status = 'PENDING',
         claimed_at = null,
         claimed_by = null,
         claim_token = null,
         claim_expires_at = null,
         scheduled_at = clock_timestamp()
   where o.status = 'PROCESSING'
     and o.claim_expires_at <= clock_timestamp()
     and o.attempt_count < o.max_attempts;

  -- 예약 후 계정이 비활성화되면 발송하지 않고 취소합니다. claim 후 반환되지 않아
  -- PROCESSING 상태에 고립되는 행이 생기지 않게 같은 함수 안에서 정리합니다.
  update core.notification_outbox o
     set status = 'CANCELLED', finished_at = clock_timestamp()
   where o.status = 'PENDING'
     and o.scheduled_at <= clock_timestamp()
     and not exists (
       select 1 from core.app_user u
        where u.user_id = o.recipient_user_id and u.active
     );

  return query
  with due as (
    select o.notification_id
      from core.notification_outbox o
     where o.status = 'PENDING'
       and o.scheduled_at <= clock_timestamp()
     order by o.scheduled_at, o.created_at
     for update skip locked
     limit p_limit
  ), claimed as (
    update core.notification_outbox o
       set status = 'PROCESSING',
           attempt_count = o.attempt_count + 1,
           claimed_at = clock_timestamp(),
           claimed_by = p_worker_id,
           claim_token = gen_random_uuid(),
           claim_expires_at = clock_timestamp() + interval '2 minutes',
           finished_at = null
      from due
     where o.notification_id = due.notification_id
    returning o.notification_id, o.claim_token, o.template_code, o.recipient_user_id, o.channel, o.payload
  )
  select c.notification_id, c.claim_token, c.template_code, c.recipient_user_id, u.email,
         c.channel, c.payload
    from claimed c
    join core.app_user u on u.user_id = c.recipient_user_id;
end;
$$;

create or replace function core.validate_claimed_notification(
  p_notification_id uuid,
  p_worker_id uuid,
  p_claim_token uuid
)
returns boolean
language plpgsql
security definer
set search_path = core, public, pg_temp
as $$
declare
  v_notice core.notification_outbox%rowtype;
begin
  select * into v_notice
    from core.notification_outbox
   where notification_id = p_notification_id
   for update;

  if not found
     or v_notice.status <> 'PROCESSING'
     or v_notice.claimed_by <> p_worker_id
     or v_notice.claim_token <> p_claim_token
     or v_notice.claim_expires_at <= clock_timestamp() then
    return false;
  end if;

  if not exists (
    select 1 from core.app_user u
     where u.user_id = v_notice.recipient_user_id and u.active
  ) then
    update core.notification_outbox
       set status = 'CANCELLED', finished_at = clock_timestamp(),
           claimed_by = null, claim_token = null, claim_expires_at = null
     where notification_id = p_notification_id;
    return false;
  end if;

  if v_notice.template_code = 'APPROVAL_PENDING'
     and not exists (
       select 1 from core.approval_request r
        where r.approval_id::text = v_notice.payload ->> 'approval_id'
          and r.status = 'PENDING'
     ) then
    update core.notification_outbox
       set status = 'CANCELLED', finished_at = clock_timestamp(),
           claimed_by = null, claim_token = null, claim_expires_at = null
     where notification_id = p_notification_id;
    return false;
  end if;

  return true;
end;
$$;

drop function if exists core.finish_notification(uuid, boolean, text, text);
drop function if exists core.finish_notification(uuid, uuid, uuid, boolean, boolean, text, text);

create function core.finish_notification(
  p_notification_id uuid,
  p_worker_id uuid,
  p_claim_token uuid,
  p_success boolean,
  p_retryable boolean default false,
  p_error_message text default null,
  p_external_message_id text default null
)
returns void
language plpgsql
security definer
set search_path = core, public, pg_temp
as $$
declare
  v_notice core.notification_outbox%rowtype;
  v_recipient_email text;
  v_next_at timestamptz;
begin
  select * into v_notice
    from core.notification_outbox
   where notification_id = p_notification_id
   for update;

  if not found then
    raise exception '처리할 알림을 찾을 수 없습니다.' using errcode = 'P0002';
  end if;
  if v_notice.status <> 'PROCESSING' then
    raise exception 'claim되지 않은 알림은 완료할 수 없습니다.' using errcode = '22023';
  end if;
  if v_notice.claimed_by <> p_worker_id or v_notice.claim_token <> p_claim_token then
    raise exception '알림 claim 소유권이 일치하지 않습니다.' using errcode = '42501';
  end if;
  if v_notice.claim_expires_at <= clock_timestamp() then
    raise exception '알림 처리 임대시간이 만료되었습니다.' using errcode = '55000';
  end if;
  if not p_success and nullif(btrim(p_error_message), '') is null then
    raise exception '실패 알림에는 오류 내용이 필요합니다.' using errcode = '22023';
  end if;

  select nullif(btrim(u.email), '') into v_recipient_email
    from core.app_user u
   where u.user_id = v_notice.recipient_user_id;

  insert into core.notification_delivery (
    notification_id, recipient_user_id, recipient_email, channel,
    status, attempt_number, retryable, error_message, external_message_id
  ) values (
    v_notice.notification_id, v_notice.recipient_user_id, v_recipient_email,
    v_notice.channel, case when p_success then 'SUCCESS' else 'FAILED' end,
    v_notice.attempt_count, case when p_success then false else p_retryable end,
    case when p_success then null else btrim(p_error_message) end,
    nullif(btrim(p_external_message_id), '')
  );

  if not p_success and p_retryable and v_notice.attempt_count < v_notice.max_attempts then
    update core.notification_outbox
       set status = 'PENDING',
           scheduled_at = clock_timestamp() + make_interval(
             secs => least(21600, 600 * power(2, greatest(v_notice.attempt_count - 1, 0)))::integer
           ),
           claimed_at = null,
           claimed_by = null,
           claim_token = null,
           claim_expires_at = null,
           last_error = btrim(p_error_message),
           finished_at = null
     where notification_id = p_notification_id;
    return;
  end if;

  update core.notification_outbox
     set status = case when p_success then 'SENT' else 'FAILED' end,
         claimed_by = null,
         claim_token = null,
         claim_expires_at = null,
         last_error = case when p_success then null else btrim(p_error_message) end,
         finished_at = clock_timestamp()
   where notification_id = p_notification_id;

  if p_success and v_notice.channel = 'IN_APP' then
    insert into core.user_notification (notification_id, recipient_user_id)
    values (v_notice.notification_id, v_notice.recipient_user_id)
    on conflict (notification_id) do nothing;
  end if;

  -- 승인 대기는 24시간 운영하며, 처리되지 않은 동안에만 정확히 10분 뒤 다음 건을 예약합니다.
  if p_success and v_notice.template_code = 'APPROVAL_PENDING'
     and exists (
       select 1 from core.approval_request r
        where r.approval_id::text = v_notice.payload ->> 'approval_id'
          and r.status = 'PENDING'
     ) then
    v_next_at := greatest(v_notice.scheduled_at + interval '10 minutes', clock_timestamp() + interval '10 minutes');
    perform core.enqueue_notification(
      'approval:' || (v_notice.payload ->> 'approval_id') || ':pending:' || extract(epoch from v_next_at)::bigint,
      'APPROVAL_PENDING', v_notice.recipient_user_id, v_notice.channel, v_next_at, v_notice.payload
    );
  elsif p_success and v_notice.template_code = 'DEMAND_SUBMISSION_OVERDUE' then
    v_next_at := greatest(v_notice.scheduled_at + interval '10 minutes', clock_timestamp() + interval '10 minutes');
    perform core.enqueue_notification(
      'demand:' || (v_notice.payload ->> 'series_id') || ':overdue:' || extract(epoch from v_next_at)::bigint,
      'DEMAND_SUBMISSION_OVERDUE', v_notice.recipient_user_id, v_notice.channel, v_next_at, v_notice.payload
    );
  end if;
end;
$$;


-- ══ 8. 승인 알림 연결과 반복 예약 취소 ════════════════════════

create or replace function core.sync_approval_notifications()
returns trigger
language plpgsql
security definer
set search_path = core, public, pg_temp
as $$
declare
  v_permission text;
  v_recipient record;
  v_channel text;
  v_payload jsonb;
begin
  if tg_op = 'INSERT' then
    v_permission := case new.approval_type
      when 'ITEM_POLICY' then 'ITEM_POLICY_APPROVE'
      when 'ALLOC_PRIORITY' then 'ALLOC_PRIORITY_APPROVE'
      when 'EVENT_ORDER' then 'EVENT_ORDER_APPROVE'
      when 'PURCHASE_PLAN' then 'PLAN_APPROVE'
    end;
    v_payload := jsonb_build_object(
      'approval_id', new.approval_id,
      'target_id', new.target_id,
      'approval_type', new.approval_type,
      'title', '승인 요청이 대기 중입니다',
      'message', new.requester_name || ' 님이 등록한 요청을 확인해 주세요.'
    );

    for v_recipient in
      select distinct u.user_id
        from core.app_user u
        join core.role_permission rp on rp.job_role = u.job_role
       where u.active
         and u.user_id <> new.requested_by
         and rp.permission_code = v_permission
    loop
      foreach v_channel in array array['IN_APP', 'EMAIL'] loop
        perform core.enqueue_notification(
          'approval:' || new.approval_id || ':pending:' || extract(epoch from new.requested_at)::bigint,
          'APPROVAL_PENDING', v_recipient.user_id, v_channel, new.requested_at, v_payload
        );
      end loop;
    end loop;
    return new;
  end if;

  if old.status = 'PENDING' and new.status in ('APPROVED', 'REJECTED', 'CANCELLED') then
    update core.notification_outbox
       set status = 'CANCELLED', finished_at = clock_timestamp(),
           claimed_by = null, claim_token = null, claim_expires_at = null
     where status in ('PENDING', 'PROCESSING')
       and payload ->> 'approval_id' = new.approval_id::text;

    v_payload := jsonb_build_object(
      'approval_id', new.approval_id,
      'target_id', new.target_id,
      'approval_type', new.approval_type,
      'decision', new.status,
      'title', case new.status when 'APPROVED' then '승인 요청이 승인되었습니다'
                               when 'REJECTED' then '승인 요청이 반려되었습니다'
                               else '승인 요청이 취소되었습니다' end,
      'message', coalesce(new.decision_comment, '승인함에서 처리 결과를 확인해 주세요.')
    );
    foreach v_channel in array array['IN_APP', 'EMAIL'] loop
      perform core.enqueue_notification(
        'approval:' || new.approval_id || ':decision:' || new.status,
        'APPROVAL_DECIDED', new.requested_by, v_channel, clock_timestamp(), v_payload
      );
    end loop;
  end if;
  return new;
end;
$$;

drop trigger if exists approval_notification_sync on core.approval_request;
create trigger approval_notification_sync
  after insert or update of status on core.approval_request
  for each row execute function core.sync_approval_notifications();


-- ══ 9. 후속 업무에서 재사용할 예약 계약 ══════════════════════

create or replace function core.cancel_notification_series(
  p_series_type text,
  p_series_id text
)
returns integer
language plpgsql
security definer
set search_path = core, public, pg_temp
as $$
declare
  v_count integer;
begin
  update core.notification_outbox
     set status = 'CANCELLED', finished_at = clock_timestamp(),
         claimed_by = null, claim_token = null, claim_expires_at = null
   where status in ('PENDING', 'PROCESSING')
     and payload ->> 'series_type' = p_series_type
     and payload ->> 'series_id' = p_series_id;
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

create or replace function core.schedule_demand_submission_reminder(
  p_submission_cycle_id text,
  p_first_at timestamptz,
  p_recipient_user_ids uuid[]
)
returns integer
language plpgsql
security definer
set search_path = core, public, pg_temp
as $$
declare
  v_user_id uuid;
  v_channel text;
  v_count integer := 0;
begin
  if nullif(btrim(p_submission_cycle_id), '') is null or p_first_at is null
     or coalesce(cardinality(p_recipient_user_ids), 0) = 0 then
    raise exception '수요 미제출 알림 입력값이 올바르지 않습니다.' using errcode = '22023';
  end if;
  foreach v_user_id in array p_recipient_user_ids loop
    foreach v_channel in array array['IN_APP', 'EMAIL'] loop
      perform core.enqueue_notification(
        'demand:' || p_submission_cycle_id || ':overdue:' || extract(epoch from p_first_at)::bigint,
        'DEMAND_SUBMISSION_OVERDUE', v_user_id, v_channel, p_first_at,
        jsonb_build_object(
          'series_type', 'DEMAND_SUBMISSION', 'series_id', p_submission_cycle_id,
          'submission_cycle_id', p_submission_cycle_id,
          'title', '수요자료 제출이 지연되고 있습니다',
          'message', '제출 마감일이 지났습니다. 수요자료를 제출해 주세요.'
        )
      );
      v_count := v_count + 1;
    end loop;
  end loop;
  return v_count;
end;
$$;

create or replace function core.schedule_temporary_allocation_expiry(
  p_allocation_id text,
  p_expires_at timestamptz,
  p_recipient_user_ids uuid[]
)
returns integer
language plpgsql
security definer
set search_path = core, public, pg_temp
as $$
declare
  v_days integer;
  v_user_id uuid;
  v_channel text;
  v_count integer := 0;
  v_when timestamptz;
begin
  if nullif(btrim(p_allocation_id), '') is null or p_expires_at is null
     or coalesce(cardinality(p_recipient_user_ids), 0) = 0 then
    raise exception '임시배정 만료 알림 입력값이 올바르지 않습니다.' using errcode = '22023';
  end if;

  foreach v_days in array array[10, 5, 3, 2, 1] loop
    v_when := p_expires_at - make_interval(days => v_days);
    foreach v_user_id in array p_recipient_user_ids loop
      foreach v_channel in array array['IN_APP', 'EMAIL'] loop
        perform core.enqueue_notification(
          'allocation:' || p_allocation_id || ':expires:' || v_days,
          'TEMP_ALLOCATION_EXPIRY_WARNING', v_user_id, v_channel, v_when,
          jsonb_build_object(
            'series_type', 'TEMP_ALLOCATION', 'series_id', p_allocation_id,
            'allocation_id', p_allocation_id, 'expires_at', p_expires_at,
            'days_before', v_days, 'title', '임시배정 만료 알림',
            'message', '임시배정이 ' || v_days || '일 후 만료됩니다.'
          )
        );
        v_count := v_count + 1;
      end loop;
    end loop;
  end loop;
  return v_count;
end;
$$;

-- 만료 당일에는 예정 문구를 예약하지 않습니다. Task 6의 실제 자동 해제 성공 트랜잭션이
-- 이 함수를 호출해야만 "자동 해제되었습니다" 완료 알림이 생성됩니다.
create or replace function core.enqueue_temporary_allocation_released(
  p_allocation_id text,
  p_recipient_user_ids uuid[]
)
returns integer
language plpgsql
security definer
set search_path = core, public, pg_temp
as $$
declare
  v_user_id uuid;
  v_channel text;
  v_count integer := 0;
begin
  perform core.cancel_notification_series('TEMP_ALLOCATION', p_allocation_id);
  foreach v_user_id in array p_recipient_user_ids loop
    foreach v_channel in array array['IN_APP', 'EMAIL'] loop
      perform core.enqueue_notification(
        'allocation:' || p_allocation_id || ':released',
        'TEMP_ALLOCATION_RELEASED', v_user_id, v_channel, clock_timestamp(),
        jsonb_build_object(
          'series_type', 'TEMP_ALLOCATION', 'series_id', p_allocation_id,
          'allocation_id', p_allocation_id, 'title', '임시배정이 자동 해제되었습니다',
          'message', '만료된 임시배정과 연결된 주문 상태를 확인해 주세요.'
        )
      );
      v_count := v_count + 1;
    end loop;
  end loop;
  return v_count;
end;
$$;


-- ══ 10. 사용자·관리자 조회 뷰와 읽음 처리 ════════════════════

create or replace view analytics.v_my_notification
with (security_invoker = true)
as
select
  o.notification_id, o.template_code,
  coalesce(nullif(o.payload ->> 'title', ''), '알림') as title,
  coalesce(o.payload ->> 'message', '') as message,
  o.payload, n.created_at, n.read_at
from core.user_notification n
join core.notification_outbox o on o.notification_id = n.notification_id
where n.recipient_user_id = auth.uid();

create or replace view analytics.v_notification_delivery
with (security_invoker = true)
as
select
  d.delivery_id, d.notification_id, o.template_code,
  d.recipient_user_id, d.recipient_email,
  coalesce(nullif(u.name, ''), u.email, d.recipient_user_id::text) as recipient_name,
  d.channel, d.status, d.attempted_at, d.error_message, d.external_message_id,
  d.attempt_number, d.retryable
from core.notification_delivery d
join core.notification_outbox o on o.notification_id = d.notification_id
left join core.app_user u on u.user_id = d.recipient_user_id
where core.is_admin();

create or replace function core.mark_notification_read(p_notification_id uuid)
returns void
language plpgsql
security definer
set search_path = core, public, pg_temp
as $$
begin
  if auth.uid() is null then
    raise exception '로그인이 필요합니다.' using errcode = '42501';
  end if;
  update core.user_notification
     set read_at = coalesce(read_at, clock_timestamp())
   where notification_id = p_notification_id
     and recipient_user_id = auth.uid();
  if not found then
    raise exception '읽을 알림을 찾을 수 없습니다.' using errcode = 'P0002';
  end if;
end;
$$;


-- ══ 11. RLS와 실행 권한 ══════════════════════════════════════

alter table core.notification_outbox enable row level security;
alter table core.notification_delivery enable row level security;
alter table core.user_notification enable row level security;

drop policy if exists notification_outbox_read_own on core.notification_outbox;
create policy notification_outbox_read_own on core.notification_outbox
  for select to authenticated using (recipient_user_id = auth.uid() or core.is_admin());
drop policy if exists notification_delivery_read_admin on core.notification_delivery;
create policy notification_delivery_read_admin on core.notification_delivery
  for select to authenticated using (core.is_admin());
drop policy if exists user_notification_read_own on core.user_notification;
create policy user_notification_read_own on core.user_notification
  for select to authenticated using (recipient_user_id = auth.uid());

revoke all on core.notification_outbox, core.notification_delivery, core.user_notification from anon, public;
revoke insert, update, delete on core.notification_outbox, core.notification_delivery, core.user_notification from authenticated;
grant select on core.notification_outbox, core.user_notification to authenticated;
grant select on core.notification_delivery to authenticated;
grant select on analytics.v_my_notification, analytics.v_notification_delivery to authenticated;

revoke all on function core.enqueue_notification(text, text, uuid, text, timestamptz, jsonb) from public, anon, authenticated;
revoke all on function core.claim_due_notifications(integer, uuid) from public, anon, authenticated;
revoke all on function core.validate_claimed_notification(uuid, uuid, uuid) from public, anon, authenticated;
revoke all on function core.finish_notification(uuid, uuid, uuid, boolean, boolean, text, text) from public, anon, authenticated;
revoke all on function core.cancel_notification_series(text, text) from public, anon, authenticated;
revoke all on function core.schedule_demand_submission_reminder(text, timestamptz, uuid[]) from public, anon, authenticated;
revoke all on function core.schedule_temporary_allocation_expiry(text, timestamptz, uuid[]) from public, anon, authenticated;
revoke all on function core.enqueue_temporary_allocation_released(text, uuid[]) from public, anon, authenticated;
revoke all on function core.sync_approval_notifications() from public, anon, authenticated;
grant execute on function core.enqueue_notification(text, text, uuid, text, timestamptz, jsonb) to service_role;
grant execute on function core.claim_due_notifications(integer, uuid) to service_role;
grant execute on function core.validate_claimed_notification(uuid, uuid, uuid) to service_role;
grant execute on function core.finish_notification(uuid, uuid, uuid, boolean, boolean, text, text) to service_role;
grant execute on function core.cancel_notification_series(text, text) to service_role;
grant execute on function core.schedule_demand_submission_reminder(text, timestamptz, uuid[]) to service_role;
grant execute on function core.schedule_temporary_allocation_expiry(text, timestamptz, uuid[]) to service_role;
grant execute on function core.enqueue_temporary_allocation_released(text, uuid[]) to service_role;
revoke all on function core.mark_notification_read(uuid) from public, anon;
grant execute on function core.mark_notification_read(uuid) to authenticated;


-- ══ 12. 수동 적용 후 확인 쿼리 ═══════════════════════════════

select status, channel, count(*)
from core.notification_outbox
group by status, channel
order by status, channel;

select template_code, recipient_name, channel, status, attempted_at, error_message
from analytics.v_notification_delivery
order by attempted_at desc;

-- 같은 업무 이벤트를 다시 예약해도 아래 조합은 한 행이어야 합니다.
select dedupe_key, recipient_user_id, channel, count(*)
from core.notification_outbox
group by dedupe_key, recipient_user_id, channel
having count(*) > 1;
-- 기대: 0행

-- 승인 처리 후 예약된 반복 알림 확인
select count(*) as pending_followups
from core.notification_outbox
where status = 'PENDING'
  and template_code = 'APPROVAL_PENDING'
  and payload ->> 'approval_id' = '<처리한 승인 UUID>';
-- 기대: 0
